### ISSUE TITLE
Results for GB-postcodes are not always correct

### ISSUE THREAD

**Issue by karussell** [komoot/photon#108]
When I try 'W1W 6YT' or 'ME7 9AA' as postcodes on osm.org the geocoding will return me a result in Great Britain. Photon only returns a proper result for the last string. For W1W 6YT it returns a result in Canada.

**Comment by karussell** [comment]
Before closing ... couldn't this different database also be integrated into nominatim/photon :) ?

**Comment by christophlingg** [comment]
which source are you using @lonvia ?

**Comment by lonvia** [comment]
OS seems to publish the postcodes freely for the UK. I believe that's our source. More info: http://www.freepostcodes.org.uk/
