### ISSUE TITLE
Unable to find "Via Ca' de Volpi" even with exact string

### ISSUE THREAD

**Issue by CristianCantoro** [komoot/photon#11]
Searching
`Via Ca' de Volpi`
yields no result even if a street with the exact name exists, see [this way](http://www.openstreetmap.org/way/184991140#map=18/45.74130/9.46893)

Thanks.

Cristian

**Comment by christophlingg** [comment]
works http://photon.komoot.de/api?q=Via+Ca%27+de+Volpi

**Comment by CristianCantoro** [comment]
Confirm.
