### ISSUE TITLE
Search by osm_id

### ISSUE THREAD

**Issue by g4vroche** [komoot/photon#111]
I would like to be able to retrieve a specific point via its osm_id.

If I query directly ES I can do : 

```
curl -XGET "http://localhost:9200/photon/place/_search?q=osm_id:284531536"
```

But it fails if I try directly on photon: 

```
curl -XGET "http://localhost:2322/api?q=osm_id:284531536"
```

Is there a way to pass low level query through Photon ?

**Comment by raphodn** [comment]
Interested as well !
In the meantime, I detect if the user has inputed an ID, and I do an alternative search
```
https://nominatim.openstreetmap.org/lookup?osm_ids=N${id},W${id},R${id}&addressdetails=1&format=json
```

**Comment by henrik242** [comment]
@g4vroche Here's a workaround in case you import manually: Set the OSM id as a category (`"categories":["osm_id.12345"]`) and search for it afterwards with `api?include=osm_id.12345`.  (Searching for categories without a query was recently introduced to the codebase.)
