### ISSUE TITLE
Allow https calls for api

### ISSUE THREAD

**Issue by amnesia7** [komoot/photon#113]
Would it be possible for you to add an SSL certificate to the api site so that the api can be called from a https site?

I've also checked out pelias (https://mapzen.com/pelias) which has an https api but for the examples that I've tested yours seems to be a better autosuggest.

Or would I need to create a proxy page on my https site to call the http api? 
I'm worried this extra step could slow the response too much when trying to use it for autocompleting.

**Comment by amnesia7** [comment]
@christophlingg I'm not sure if anything's changed but there appears to be an issue with SSL certificate being used.
It looks like it might be something to do with an intermediate/chain certificate being used.
I think it is preventing me calling the API from Chrome on an android phone that I'm testing although the issue could possibly affect other browsers as well.
https://www.sslshopper.com/ssl-checker.html#hostname=https://photon.komoot.de
http://www.networking4all.com/en/support/tools/site+check/report/?fqdn=https%3A%2F%2Fphoton.komoot.de&protocol=https

**Comment by amnesia7** [comment]
Looks like this kind of issue does actually affect android and not pc in some cases: http://stackoverflow.com/questions/11340298/certificate-trusted-on-pc-but-not-in-android

**Comment by amnesia7** [comment]
@christophlingg I think it is just a case of concatenating your site certificate with the intermediate certificate from the ssl vendor and then using that new ssl certificate file.

**Comment by christophlingg** [comment]
can you send me a mail please?

**Comment by amnesia7** [comment]
Sorted!

**Comment by amnesia7** [comment]
@christophlingg I've had a look at `website\photon\templates\index.html` and with a couple of tweaks you could make it so that your actual website can be made to work as both `http` and `https`.

You would need to change the css file to come from a cdn that serves assets via http as well as https so change:
```html
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css"/>
```
to be:
```html
<link rel="stylesheet" href="//cdn.jsdelivr.net/leaflet/0.7.3/leaflet.css"/>
```
You would also need to change the leaflet js file to come from that cdn as well:
```html
<script src="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet-src.js"></script>
```
to be:
```html
<script src="//cdn.jsdelivr.net/leaflet/0.7.3/leaflet.js"></script>
```
In case you weren't aware, starting with `//` rather than `http://` or `https://` means it will just use the same protocol as the page is currently using.

You would need to make sure it works ok when you make the following change but you should then just need to update the `API_URL`:
```js
API_URL = 'http://photon.komoot.de/api/?';
```
to be
```js
API_URL = '//photon.komoot.de/api/?';
```
and `TILELAYER` values that you set in the python code:
```js
TILELAYER = 'http://{s}.tile.komoot.de/komoot/{z}/{x}/{y}.png';
```
to be:
```js
TILELAYER = '//{s}.tile.komoot.de/komoot/{z}/{x}/{y}.png';
```
I would've sent a PR but I wasn't sure where you were setting the `API_URL`.

**Comment by christophlingg** [comment]
that would be a nice PR!

I assume that an api_url was not set as it uses the default one: https://github.com/komoot/leaflet.photon#options

**Comment by amnesia7** [comment]
I might get chance to do a PR tomorrow evening. 
It won't work with the default one because that's http but it would need to be https if it is running on https.
I wasn't sure how your python(?) code was generating the url that it was using in the index page:
```html
<script type="text/javascript">
    API_URL = 'http://photon.komoot.de/api/?';
    TILELAYER = 'http://{s}.tile.komoot.de/komoot/{z}/{x}/{y}.png';
    CENTER = [52.3879, 13.0582];
    MAXZOOM = 18;
</script>
```
so I wasn't sure if this was generated automatically somehow based on the web address the site was running on.
@christophlingg Is it automatic somehow or would this need to be set in the code?

**Comment by christophlingg** [comment]
the template file is here: https://github.com/komoot/photon/blob/master/website/photon/templates/index.html#L154

and here is where the variables are defined: https://github.com/komoot/photon/blob/master/website/photon/app.py#L21

**Comment by amnesia7** [comment]
Unfortunately there's a small issue of the fact that your map tiles are actually provided by thunderforest so trying to access them over https doesn't seem to work.
eg https://a.tile.komoot.de/komoot/10/180/150.png shows:
```
This server could not prove that it is a.tile.komoot.de; its security certificate is from tile.hosted.thunderforest.com
```
so I suppose to get this to work I'd need to know what the https url would be for the map tiles (thunderforest may be able to advise you on this) otherwise the browser will not show the map tiles because they'll either throw a security error or would be provided by http for a https site which browsers (eg Chrome) would prevent from being used.

**Comment by christophlingg** [comment]
try to use this ones: https://www.komoot.de/tiles/b/9/274/168.png

**Comment by amnesia7** [comment]
That seems fine. Looks to offer `a`, `b` and `c` for `{s}` for the tile layers url. 

Can you tell me how `API_URL` is set (https://github.com/komoot/photon/blob/master/website/photon/templates/index.html#L155) which outputs:
```
API_URL = 'http://photon.komoot.de/api/?';
```

**Comment by christophlingg** [comment]
it is set here: https://github.com/komoot/photon/blob/master/website/photon/app.py#L13
You can overwrite the default value with an environment variable. To make things easy, i would overwrite the default value `http://localhost:5001/api/?` to be 'https://photon.komoot.de/api/?'

**Comment by amnesia7** [comment]
Would it not be better for the environment variable used on your website to be `https://photon.komoot.de/api/?` so the PR doesn't affect anyone downloading photon to run on their own server leaving the API_URL code as it is now?

**Comment by christophlingg** [comment]
We can also do it this way, that's not a problem!

**Comment by amnesia7** [comment]
See https://github.com/komoot/photon/pull/167. 

Hopefully that should work fine but be aware that PR changes have been made with no easy way to test.

I've set the tile layer variable to start `//` rather than`http` or `https` because I wasn't sure if you used an environment variable for that url or not.

And changing the `API_URL` environment variable to `//photon.komoot.de/api/?` should allow it to work correctly whether using http or https but be aware if you are using that environment variable for anything else. If you are then it may be best to just set it as the https version `https://photon.komoot.de/api/?`

Just remember what they were before making any changes just in case you need to put them back...hopefully all should be fine though.
