### ISSUE TITLE
adding OPTIONS request for cross site access 

### ISSUE THREAD

**Issue by christophlingg** [komoot/photon#117]
closes https://github.com/komoot/leaflet.photon/issues/3

see:
- http://stackoverflow.com/questions/1743845/jquery-i-get-options-request-instead-of-get
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by Hacktivista** [comment]
Is this still implemented? I'm getting the following message:

```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://photon.komoot.de/api/?q=c. (Reason: CORS header 'Access-Control-Allow-Origin' missing).```

While requesting with JQuery

**Comment by christophlingg** [comment]
we are setting this header, check

```
curl -i "https://photon.komoot.de/api/?q=c&limit=1" 
HTTP/1.1 200 OK
Server: nginx/1.9.3 (Ubuntu)
Date: Tue, 02 Feb 2016 00:05:58 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 335
Connection: keep-alive
Access-Control-Allow-Origin: *

{"features":[{"geometry":{"coordinates":[35.38202481867126,31.9469543],"type":"Point"},"type":"Feature","properties":{"osm_id":3791785,"osm_type":"R","extent":[34.8810553,32.5521479,35.5734946,31.3416904],"country":"Palestinian Territory","osm_key":"boundary","osm_value":"administrative","name":"Area C"}}],"type":"FeatureCollection"}
```

Are you sure you make a proper GET request? I just found out by mistake that HEAD requests don't have this header.

**Comment by Hacktivista** [comment]
The problem is with Ajax requests, its behaviour commonly is to ask for CORS when remote asking for data. I had to hack JQuery in order to make it work, of course this is not what I should do. I know it's weird to process something not really needed, but is what everybody does, and generates incompatibility, maybe in a few years this will not be needed, check #122 .

**Comment by christophlingg** [comment]
Hi @Hacktivista, I added OPTIONS endpoints to the API. It looks like this:

```
$ curl -i -X OPTIONS "http://photon.komoot.de/api?q=munich"
HTTP/1.1 200 OK
Server: nginx/1.9.3 (Ubuntu)
Date: Tue, 02 Feb 2016 08:23:15 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 0
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Max-Age: 2592000
```

Could you please verify that it's working and let me know what else is needed – if needed. Thanks

**Comment by Hacktivista** [comment]
It does not work for me, OPTIONS gets a 200 response while GET is pending indefinitely.

I think this might help a lot: http://amodernstory.com/2014/12/27/using-cors-headers-with-java-example/

Other resources might be:
https://github.com/ebay/cors-filter
http://software.dzhuvinov.com/cors-filter.html

**Comment by christophlingg** [comment]
This works for me: https://jsfiddle.net/wu74w1rc/1/

Does it for you, which browser do you use?

**Comment by Hacktivista** [comment]
Ok, looks like it has nothing to do with CORS, but with a X-CSRF-TOKEN I send with all my ajax petitions. (Check https://jsfiddle.net/wu74w1rc/2/)

Thanks a lot for your help!!

**Comment by christophlingg** [comment]
you owe me a beer ;-)

**Comment by lonvia** [comment]
@christophlingg now photon.komoot.de is reporting cross scripting issues. Might have something to do with the recent changes for this ticket.

**Comment by christophlingg** [comment]
can you be more specific?

**Comment by lonvia** [comment]
Firefox reports: Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://photon.komoot.de/api/?q=munich&limit=5&lat=52.387963405382365&lon=13.058109283447266. (Reason: missing token 'x-requested-with' in CORS header 'Access-Control-Allow-Headers' from CORS preflight channel).

**Comment by lonvia** [comment]
So the issue is only with the http version of the site. Requesting https content does not work.

**Comment by christophlingg** [comment]
I will remove the OPTIONS endpoint again, just making trouble for nothing.

**Comment by christophlingg** [comment]
done, let me know if it still does not work (maybe there is some caching)

**Comment by dhannumanikpuri** [comment]
I have solved that issue:

https://stackoverflow.com/a/45974116/6053781
