### ISSUE TITLE
Town duplicates and missing county info?

### ISSUE THREAD

**Issue by amnesia7** [komoot/photon#120]
I've just tried doing a search for `chorley` using http://photon.komoot.de/ (the request was actually http://photon.komoot.de/api/?q=chorley&limit=5&lat=52.38796340538239&lon=13.058280944824217) which returned 2 entries both listed as `Chorley, United Kingdom (administrative)`. 
The response also included 2 entries listed as `Chorley, United Kingdom (village)` that are both different villages but the response gives no information to differentiate between them until you see where they are on the map.

Are the 2 administrative entries duplicates? 
Is there anything that can be done about duplicates like this from the api point of view? 
I could filter the response before showing them in the suggestions list (eg request limit=10, remove duplicates, output the first 5) but I wonder if the response shouldn't be actually including them anyway.

Is there some info missing with respect to the 2 village entries in the list, eg county name, to give the user more of a clue which is which?

**Comment by amnesia7** [comment]
@christophlingg it's great that you've added `state` to the api response but for the above queries they are still indistinguishable because the state returned is `state: "England"`.
Is there any sign of `county` being added to the response as well so that they are shown differently in the response?
Photon: http://photon.komoot.de/api?q=chorley&limit=3
Nominatim (without extra address details): http://open.mapquestapi.com/nominatim/v1/search.php?format=json&addressdetails=0&limit=3&q=chorley
Nominatim (with extra address details): http://open.mapquestapi.com/nominatim/v1/search.php?format=json&addressdetails=1&limit=3&q=chorley

**Comment by christophlingg** [comment]
Thanks for your feedback, did not know about nominatim's feature of extracting county information. It should not be too hard to include it, however I assume it is not as urgent as it was for the state attribute. It also seems that mapping coverage of county is not that good: http://taginfo.openstreetmap.org/tags/?key=place&value=county#map

**Comment by lonvia** [comment]
Counties are mostly tagged as administrative boundary with admin level 6.

**Comment by amnesia7** [comment]
@christophlingg county is very important for distinguishing between locations in the UK. 
I didn't actually realise until it was implemented but the `county` field is probably more important than `state` for UK locations. I thought UK county names would've been in the `state` field until I found out there was a `county` field as well.
As I highlight above there are plenty of places with the same name but are located in different counties so they are difficult to distinguish between.
It looks to be pretty important for america as well:
http://photon.komoot.de/api?q=springfield+virginia
http://open.mapquestapi.com/nominatim/v1/search.php?format=json&addressdetails=1&q=springfield+virginia&limit=15

**Comment by amnesia7** [comment]
@christophlingg I was just wondering if there was any chance of county being added to the response (where it exists) with it being important (at least for UK and USA locations).
I've just had another look at OpenCage Geocoder (uses the address-formatting project) that was mentioned above and the demo includes the county in the address output.

**Comment by christophlingg** [comment]
It is a good idea and could help users. We need to elaborate first how big the impact of a new field (search performance and index size).

**Comment by amnesia7** [comment]
Cool. 
Let me know if you need me to try it out or anything once you've checked the impact of adding it. 
I know it would make uk addresses far more useful that are returned (at least) so I'm hoping it's ok for you to add it.

**Comment by amnesia7** [comment]
In the meantime, if anyone is looking to remove duplicates like `Phones 4u Arena in Manchester` it can be done using:
```
function mergeJson (json) {
    //invalid object
    if (!json || !json.features) {
      return;
    }
    var features = json.features;
    var added = {};
    for (var i = 0, l = features.length; i < l; i++) {
      var o = features[i].properties;
      if (!o) {
        continue;
      }
      var ref = o.osm_type + '~' + o.osm_id;
      if (added.hasOwnProperty(ref)) {
        if (added[ref].osm_value.indexOf(o.osm_value) === -1) {
          added[ref].osm_value = added[ref].osm_value + ', ' + o.osm_value;
        }
        //remove the object and subtract and size
        json.features.splice(i--, 1), l--;
      } else {
        added[ref] = o;
      }
    }
  }

mergeJson(data);
```
which will use a comma separated list for osm_values of duplicates, `stadium, attraction`

**Comment by amnesia7** [comment]
@christophlingg 

> We need to elaborate first how big the impact of a new field (search performance and index size).

If I add the county name into my search query photon does return a resultset that is filtered down as expected, matching those in that county, so I assume county is in the search index already (and in use). 
Does that mean that it just needs county adding to the resultset that are returned for the query and shouldn't actually affect the index size anyway?

**Comment by amnesia7** [comment]
@christophlingg just wondered if there was any news about a release date or progress update on milestone 0.3.0

**Comment by christophlingg** [comment]
sorry @amnesia7 I am quite busy with other stuff which leaves me with no time for photon at the moment

**Comment by amnesia7** [comment]
That's a shame, photon was making really good progress. Hurry back.

**Comment by amnesia7** [comment]
@christophlingg just wondered whether you are working on photon again yet to be able to add county to the response which already appears to be part of the index anyway because when searching and including the county in the query the results look to be filtered down as expected.

**Comment by amnesia7** [comment]
@karussell would `county` field not be of use with GraphHopper when selecting start and end locations? Particularly when searching UK and USA locations.

**Comment by lonvia** [comment]
API now returns county. Closing.
