### ISSUE TITLE
some requests take very long

### ISSUE THREAD

**Issue by christophlingg** [komoot/photon#133]
Matt reported via email that this request takes http://photon.komoot.de/api?q=austr&lon=10&lat=47 takes very long (more than 20 seconds).

this is understandable as the request takes _every_ address in <strong>Austr</strong>ialia and <strong>Austr</strong>ia into account and calculates the distance to location 10,47 - it is a request with location bias. this leads to millions of non-trivial calculations.

Things are even worse for `United` – think of United States, United Kingdom, ...

I assume that the address context is not needed for many queries. We could make a staged request: first we query index without taking context into account and only if there are no results found we could extend the query to the context. it would avoid long results as above and would speed up all the others too.

@yohanboniface what do you think of it? maybe there are some side effects also with fuzzy search, but still it should be a reasonable step.

**Comment by lonvia** [comment]
Works fine these days, so I assume that this got fixed with the location bias rewrite.
