### ISSUE TITLE
consider extent of linked places

### ISSUE THREAD

**Issue by christophlingg** [komoot/photon#137]
when [searching for berlin](http://photon.komoot.de/api?q=berlin&debug&limit=1) we are missing the extent attribute. It should be available via the `linked_place_id` as it was mentioned in [this thread](https://github.com/komoot/photon/issues/134#issuecomment-70513599).

**Comment by lonvia** [comment]
This is actually an issue of missing linkage in Nominatim. If a node gets linked, then the linked area is returned and the node does not show up. Berlin should get better with #457. Closing here.
