### ISSUE TITLE
Replave mvel with groovy?

### ISSUE THREAD

**Issue by karussell** [komoot/photon#145]
I'm fighting a bit to make the separation of photon and elasticsearch happening and one of the issues is that mvel is no longer the default scripting language for elasticsearch https://github.com/elasticsearch/elasticsearch/issues/7029

**Comment by karussell** [comment]
Also it looks elasticsearch should be updated to at least 1.4.3: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-scripting.html

**Comment by karussell** [comment]
For the external ES you have to install:
`plugin -install elasticsearch/elasticsearch-lang-mvel/1.4.1`

**Comment by christophlingg** [comment]
are you using elasticsearch without photon there? this dep should ensure the plugin to be installed: https://github.com/komoot/photon/blob/master/pom.xml#L16

**Comment by karussell** [comment]
I mean a plain 'external' installation via the debian package, for this one needs the `scripts` folder in the `config/` and this mvel plugin
