### ISSUE TITLE
QUESTION : Photon extensive usage ?

### ISSUE THREAD

**Issue by MarcelPitch** [komoot/photon#148]
Hi,

We are very interesting by using your Public API in the project we're currently developing.

We've read on your demo page :

 "You can use the API for your project, but please be fair - extensive usage will be throttled"

We would use your API for permitting the end-user to :
- search a city
- store the osm_id and the labels in database
- re-use the data later in order to connect people with nearest other ones

Your API will be only used "on-the-fly" by end-users.
No massive queries, we prefer to populate our database day by day.

Here's the question (*finally* :smile: ) :
**From which amount of queries do you consider it's a extensive usage of your API ?**

Thanks for your answer and congratulations for your work !!!

**Comment by christophlingg** [comment]
first of all: we cannot guarantee any uptime, availability or performance. it is very easy to setup your own photon instance, you might want to consider this if you include it in your service.

an ip gets throttled once it exceed 7 request per second.

**Comment by MarcelPitch** [comment]
OK @christophlingg,

Thanks for your answer and have a nice day :+1:

**Comment by amnesia7** [comment]
@MarcelPitch if you use the public API (although the same should apply to any autocomplete calling a remote API) I would suggest making sure the autocomplete code/plugin that you use uses some form of [`debounce`](http://davidwalsh.name/function-debounce) to control the requests to the API on key strokes.
[Typeahead.js](https://github.com/twitter/typeahead.js) by Twitter does it.
@yohanboniface should be able to confirm that https://github.com/komoot/leaflet.photon does it in some form as well.

**Comment by MarcelPitch** [comment]
OK @amnesia7,

Thanks for the tips ! 
We think we'll host our own photon instance. But your suggestion is still useful. We'll consider that. :+1: 

Have a nice day !!!
