### ISSUE TITLE
Data separated by Countries

### ISSUE THREAD

**Issue by Shelvak** [komoot/photon#149]
Hi people that's a wonderful work. I need only "autocomplete" for Argentina, that's some way that you can upload a argentina-data-file (that the size isn't 31Gb) ? Because We have a ver very low connection and plus that... we don't have a lot of space to allocate that. So if you were so friendly i'll appreciate that ^^

Thanks =)

**Comment by christophlingg** [comment]
Hi Shelvak, there is no easy way of providing you a country specific dataset. You can do it by your own by installing nominatim and import an Argentinean country extract. Another option would be installing the world-wide dataset and removing all elastic search documents that aren't assigned to Argentina.

**Comment by Shelvak** [comment]
Ok, thanks for answer me
