### ISSUE TITLE
Spark server not starting after data import

### ISSUE THREAD

**Issue by mrsmn** [komoot/photon#154]
Hi there,

I've been running into a strange issue when trying to get photon to work.
I'm using the following command to start photon

```
java -jar photon-0.2.3.jar -nominatim-import -host <host> -port <port> -database nominatim -user nominatim -password <password>
```

And get the following output:

```
[main] INFO de.komoot.photon.App - starting import from nominatim to photon with languages: en,fr,de,it
[main] INFO de.komoot.photon.nominatim.NominatimConnector - start importing documents from nominatim ...
[main] INFO de.komoot.photon.nominatim.NominatimConnector - imported 50,000 documents [965.2/second]
[main] INFO de.komoot.photon.nominatim.NominatimConnector - imported 100,000 documents [1044.9/second]
[main] INFO de.komoot.photon.nominatim.NominatimConnector - finished import of 131,505 photon documents.
[main] INFO de.komoot.photon.App - imported data from nominatim to photon with languages: en,fr,de,it
```

I can leave this running for hours, _Sparks_ never starts so I can't query the API.

I've tried killing photon and restarting it again with

```
java -jar photon-0.2.3.jar
```

but then I get the following output 

```
[main] INFO de.komoot.photon.elasticsearch.Server - started elastic search node
== Spark has ignited ...
>> Listening on 0.0.0.0:2322
[Thread-1] INFO org.eclipse.jetty.server.Server - jetty-9.0.z-SNAPSHOT
[Thread-1] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@4e1b2ed9{HTTP/1.1}{0.0.0.0:2322}
[elasticsearch[Jubilee][clusterService#updateTask][T#1]] INFO org.elasticsearch.gateway - [Jubilee] recovered [1] indices into cluster_state
[qtp1596204804-37] ERROR spark.webserver.MatcherFilter -
org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query_fetch], all shards failed
    at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:233)
    at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:179)
    at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:565)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

and `curl http://localhost:2322/api?q=<query>`simply returns `<html><body><h2>500 Internal Error</h2></body></html>`

Hope this is clear enough for someone to understand.

Cheers.

**Comment by christophlingg** [comment]
Hi, which version have you used? 

    [main] INFO de.komoot.photon.App - imported data from nominatim to photon with languages: en,fr,de,it

was this really your output, you specified en,fr only. It is true, photon does not stop automatically after a nominatim import is finished. I think it changed once we updated to a newer version of elastic search.

You did the right thing, so I can't tell you why it did not work. Did you get that error on booting or after your sample query?

btw. the folder 'photon_data' must be in the same directory where you start photon from

**Comment by c0ding** [comment]
Hi,

I've tried it with photon 0.2.1, 0.2.2 and 0.2.3. Nevermind the language, that was a copy/paste mistake and the ```-languages``` was not used.
The error appears after I restart photon using the ```java -jar photon-0.2.3.jar```command, not during a query.

**Comment by christophlingg** [comment]
what's the output after you got the 500 repsonse?

**Comment by c0ding** [comment]
The stacktrace from photon is
```
[qtp701563010-36] ERROR spark.webserver.MatcherFilter -
org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query_fetch], all shards failed
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:233)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:179)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:565)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by christophlingg** [comment]
I am confused too, why would that happen. I would have expected a more detailed exception too,

**Comment by karussell** [comment]
Maybe the index was corrupted somewhere in the middle? Or too few RAM?

**Comment by c0ding** [comment]
The strange thing is there is no output about a corrupt index and the system has about 8GB of free RAM to play with so that should not be the issue.

**Comment by karussell** [comment]
but did you give the JVM this RAM via -Xmx?

**Comment by c0ding** [comment]
Just did, gave it 4GB minimum and 6GB maximum, does not change anything: photon still hangs after data import.

**Comment by c0ding** [comment]
Well after some more testing it seems that when I first launch photon it never properly imports the data from nominatim and therefor never starts Spark. I used this as a workaround for now:

-start photon with ```java -jar photon-* -nominatim-import -host <host> -port <port> -database nominatim -user postgres -password <password>```, wait for it to say ```imported data from nominatim to photon with languages```and then kill it
- restart photon with ```java -jar photon-*```and wait for it to recover index
- Sparks starts and I can query it successfully.

Will have to dig deeper into this issue to find a more permanent solution though.
Cheers.

**Comment by christophlingg** [comment]
it makes totally sense to me to make photon less confusing, I added it to the new milestone

**Comment by karussell** [comment]
Probably also related to #163?
