### ISSUE TITLE
Search index updates

### ISSUE THREAD

**Issue by jessbringlarsen** [komoot/photon#160]
Hi just found your great project and was wondering:
Is the Elasticsearch search index listed on the site (http://photon.komoot.de/data/photon_data_021_150112.tar.bz2) only there as way to get going or are they updated regularly - so we do not have to update data using Nominatum?

thanks, 
Jess

**Comment by christophlingg** [comment]
well, regularly in the sense of every six month ;-)

If you need to be more up-to-date with the latest OSM changes you need your own nominatim setup. But it's true, this has to be done only once by one person / company. The photon search index could then be shared with all other users.
