### ISSUE TITLE
Photon doesn’t quit after import/dump actions

### ISSUE THREAD

**Issue by paulmenzel** [komoot/photon#163]
Currently, with Photon from commit 1abeb523, running the command below

    java -jar /photon/target/photon-0.2.3-SNAPSHOT.jar -nominatim-import -host localhost -port 5432 -database nominatim -user root -languages de

the following message is printed to the screen but Photon does not terminate.

    […]
    [main] INFO de.komoot.photon.nominatim.NominatimConnector - finished import of 927,553 photon documents.
    [main] INFO de.komoot.photon.App - imported data from nominatim to photon with languages: de

Reading issue #64, Photon should actually stop and reading Photon’s source code in file `App.java`, it should actually return.

                if(args.isNominatimImport()) {
                        startNominatimImport(args, esServer, esClient);
                        return;
                }

Could there be a problem with closing the connection to the database server or some other process?

**Comment by christophlingg** [comment]
This behaviour came up after we upgraded the elastic search version. So I presume that the elastic search client is blocking the process to be terminated.

**Comment by paulmenzel** [comment]
@christophlingg, please reopen this ticket then after reverting the fix in commit db21633.

**Comment by karussell** [comment]
Ouch, my fault. This means we need to shutdown but not if startApi is called I think

**Comment by christophlingg** [comment]
yes, exactly

**Comment by zohaibAsif-tes** [comment]
### Photon not running

I started nominatim using:
`docker run -p 8080:8080 --name nominatim_container --detach helvalius/nominatim-docker-development`

and to start photon I used:
`docker run -p 2322:2322  --link nominatim_container:nominatim -ti helvalius/photon-docker `

when I go to:
`http://localhost:2322/api?q=Monacco` 

**I get site not found error**

**Comment by lonvia** [comment]
@zohaibAsif-tes Do not add comments to unrelated closed issues, always open a new one. That said, you are in the wrong repository anyway. If you have a problem with a docker setup, then you have to talk to the people who maintain the docker setup. In this case: https://github.com/helvalius/photon-docker/issues
