### ISSUE TITLE
Search results bias for osm types/values

### ISSUE THREAD

**Issue by amnesia7** [komoot/photon#165]
If I run http://photon.komoot.de/api?q=london+eye I get a bus stop called London Eye as the first result.

From a technical point of view I can see why this is first; because it is an exact match but from a user point of view I would've thought that the second result (EDF Energy London Eye) would be the more likely to be the result the user was searching for.

Should the weighting of bus stops in search results be reduced compared to attractions/places or was there talk of using wikipedia to help add weighting to the search index results.

**Comment by lonvia** [comment]
This has been solved with wikipedia importances.
