### ISSUE TITLE
Nominatim import is hanging 

### ISSUE THREAD

**Issue by maraev** [komoot/photon#170]
Hi!
When i star import from nominatim db i get exeption like:

[main] ERROR de.komoot.photon.elasticsearch.Server - cannot install plugin: mobz
/elasticsearch-head: java.io.IOException: plugin directory c:\gis\photon\photon_
data\elasticsearch\plugins\head already exists. To update the plugin, uninstall
it first using --remove mobz/elasticsearch-head command
[main] ERROR de.komoot.photon.elasticsearch.Server - cannot install plugin: poly
fractal/elasticsearch-inquisitor: java.io.IOException: plugin directory c:\gis\p
hoton\photon_data\elasticsearch\plugins\inquisitor already exists. To update the
 plugin, uninstall it first using --remove polyfractal/elasticsearch-inquisitor
command
[main] INFO org.elasticsearch.node - [Ringmaster] version[1.4.1], pid[4056], bui
ld[89d3241/2014-11-26T15:49:29Z]
[main] INFO org.elasticsearch.node - [Ringmaster] initializing ...
[main] INFO org.elasticsearch.plugins - [Ringmaster] loaded [lang-mvel, wordendi
ng], sites [head, inquisitor]
[main] INFO org.elasticsearch.script - [Ringmaster] compiling script file [c:\gi
s\photon\photon_data\elasticsearch\config\scripts\general-score.mvel]
[main] INFO org.elasticsearch.script - [Ringmaster] compiling script file [c:\gi
s\photon\photon_data\elasticsearch\config\scripts\location-biased-score.mvel]
[main] INFO org.elasticsearch.node - [Ringmaster] initialized
[main] INFO org.elasticsearch.node - [Ringmaster] starting ...
[main] INFO org.elasticsearch.transport - [Ringmaster] bound_address {inet[/127.
0.0.1:9301]}, publish_address {inet[/127.0.0.1:9301]}
[main] INFO org.elasticsearch.discovery - [Ringmaster] photon/QbPSEUuYQiyuDWm0aH
R0tg
[elasticsearch[Ringmaster][clusterService#updateTask][T#1]] INFO org.elasticsear
ch.cluster.service - [Ringmaster] new_master [Ringmaster][QbPSEUuYQiyuDWm0aHR0tg
][WS-1882][inet[/127.0.0.1:9301]], reason: zen-disco-join (elected_as_master)
[main] INFO org.elasticsearch.http - [Ringmaster] bound_address {inet[/127.0.0.1
:9201]}, publish_address {inet[/127.0.0.1:9201]}
[main] INFO org.elasticsearch.node - [Ringmaster] started
[main] INFO de.komoot.photon.elasticsearch.Server - started elastic search node
[elasticsearch[Ringmaster][clusterService#updateTask][T#1]] INFO org.elasticsear
ch.gateway - [Ringmaster] recovered [1] indices into cluster_state
Exception in thread "main" org.elasticsearch.indices.IndexAlreadyExistsException
: [photon] already exists
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validat
eIndexName(MetaDataCreateIndexService.java:167)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validat
e(MetaDataCreateIndexService.java:559)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$
200(MetaDataCreateIndexService.java:87)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execu
te(MetaDataCreateIndexService.java:243)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.r
un(InternalClusterService.java:329)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecu
tor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Is that normal mode and i should have to wait or what,s going wrong with it?

**Comment by christophlingg** [comment]
the exceptions are about plugins that photon want's to install but are already installed, I assume it was not your first photon start. Its not a critical error, actually it isn't even an error. we prevent to log them.

you will need to wait a little bit at startup, depending on your machine and the data size. it can be even one or two hours if you have the world wide dataset.

**Comment by maraev** [comment]
Yes, right. I aborted session and tried it again. It seems to hangs again and I get error:
[main] ERROR de.komoot.photon.elasticsearch.Server - cannot install plugin: mobz/elasticsearch-head: java.io.IOException: plugin directory c:\gis\photon\photon_data\elasticsearch\plugins\head already exists. To update the plugin, uninstall it first using --remove mobz/elasticsearch-head command
[main] ERROR de.komoot.photon.elasticsearch.Server - cannot install plugin: polyfractal/elasticsearch-inquisitor: java.io.IOException: plugin directory c:\gis\photon\photon_data\elasticsearch\plugins\inquisitor already exists. To update the plugin, uninstall it first using --remove polyfractal/elasticsearch-inquisitor command
[main] INFO org.elasticsearch.node - [Black Cat] version[1.4.1], pid[3516], build[89d3241/2014-11-26T15:49:29Z]
[main] INFO org.elasticsearch.node - [Black Cat] initializing ...
[main] INFO org.elasticsearch.plugins - [Black Cat] loaded [lang-mvel, wordending], sites [head, inquisitor]
[main] INFO org.elasticsearch.script - [Black Cat] compiling script file [c:\gis\photon\photon_data\elasticsearch\config\scripts\general-score.mvel]
[main] INFO org.elasticsearch.script - [Black Cat] compiling script file [c:\gis\photon\photon_data\elasticsearch\config\scripts\location-biased-score.mvel]
[main] INFO org.elasticsearch.node - [Black Cat] initialized
[main] INFO org.elasticsearch.node - [Black Cat] starting ...
[main] INFO org.elasticsearch.transport - [Black Cat] bound_address {inet[/127.0.0.1:9301]}, publish_address {inet[/127.0.0.1:9301]}
[main] INFO org.elasticsearch.discovery - [Black Cat] photon/FgmsEG63TwO39-ZyYh9-sQ
[elasticsearch[Black Cat][clusterService#updateTask][T#1]] INFO org.elasticsearch.cluster.service - [Black Cat] new_master [Black Cat][FgmsEG63TwO39-ZyYh9-sQ][WS-1882][inet[/127.0.0.1:9301]], reason: zen-disco-join (elected_as_master)
[main] INFO org.elasticsearch.http - [Black Cat] bound_address {inet[/127.0.0.1:9201]}, publish_address {inet[/127.0.0.1:9201]}
[main] INFO org.elasticsearch.node - [Black Cat] started
[main] INFO de.komoot.photon.elasticsearch.Server - started elastic search node
[elasticsearch[Black Cat][clusterService#updateTask][T#1]] INFO org.elasticsearch.gateway - [Black Cat] recovered [1] indices into cluster_state
[elasticsearch[Black Cat][clusterService#updateTask][T#1]] INFO org.elasticsearch.cluster.metadata - [Black Cat] [photon] deleting index
[elasticsearch[Black Cat][clusterService#updateTask][T#1]] INFO org.elasticsearch.cluster.metadata - [Black Cat] [photon] creating index, cause [api], shards [5]/[1], mappings []
[elasticsearch[Black Cat][clusterService#updateTask][T#1]] INFO org.elasticsearch.cluster.metadata - [Black Cat] [photon] create_mapping [place]
[main] INFO de.komoot.photon.elasticsearch.Server - mapping created: {"place":{"dynamic":"false","_source":{"excludes":["context.*"]},"_id":{"path":"id"},"_all":{"enabled":false},"properties":{"osm_id":{"type":"long"},"country":{"properties":{"de":{"copy_to":["collector.de"],"index":"no","type":"string"},"default":{"copy_to":["collector.default"],"index":"no","type":"string"},"en":{"copy_to":["collector.en"],"index":"no","type":"string"},"it":{"copy_to":["collector.it"],"index":"no","type":"string"},"fr":{"copy_to":["collector.fr"],"index":"no","type":"string"}}},"coordinate":{"type":"geo_point"},"city":{"properties":{"de":{"copy_to":["collector.de"],"index":"no","type":"string"},"default":{"copy_to":["collector.default"],"index":"no","type":"string"},"en":{"copy_to":["collector.en"],"index":"no","type":"string"},"it":{"copy_to":["collector.it"],"index":"no","type":"string"},"fr":{"copy_to":["collector.fr"],"index":"no","type":"string"}}},"importance":{"type":"float"},"postcode":{"copy_to":["collector.default
"],"index":"no","type":"string"},"collector":{"similarity":"photonsimilarity","properties":{"de":{"copy_to":["collector.de"],"index":"no","type":"string","fields":{"raw":{"index_analyzer":"index_raw","type":"string"},"ngrams":{"index_analyzer":"index_ngram","type":"string"}}},"default":{"analyzer":"index_ngram","type":"string","fields":{"raw":{"analyzer":"index_raw","type":"string"}}},"en":{"copy_to":["collector.en"],"index":"no","type":"string","fields":{"raw":{"index_analyzer":"index_raw","type":"string"},"ngrams":{"index_analyzer":"index_ngram","type":"string"}}},"it":{"copy_to":["collector.it"],"index":"no","type":"string","fields":{"raw":{"index_analyzer":"index_raw","type":"string"},"ngrams":{"index_analyzer":"index_ngram","type":"string"}}},"fr":{"copy_to":["collector.fr"],"index":"no","type":"string","fields":{"raw":{"index_analyzer":"index_raw","type":"string"},"ngrams":{"index_analyzer":"index_ngram","type":"string"}}}}},"osm_type":{"index":"no","type":"string"},"osm_key":{"index":"not_analyzed","ty
pe":"string"},"housenumber":{"copy_to":["collector.default"],"index":"not_analyzed","type":"string"},"street":{"type":"object","properties":{"de":{"copy_to":["collector.de"],"index":"no","type":"string"},"default":{"copy_to":["collector.default"],"index":"no","type":"string"},"en":{"copy_to":["collector.en"],"index":"no","type":"string"},"it":{"copy_to":["collector.it"],"index":"no","type":"string"},"fr":{"copy_to":["collector.fr"],"index":"no","type":"string"}}},"osm_value":{"index":"not_analyzed","type":"string"},"context":{"properties":{"de":{"copy_to":["collector.de"],"index":"no","type":"string"},"default":{"copy_to":["collector.default"],"index":"no","type":"string"},"en":{"copy_to":["collector.en"],"index":"no","type":"string"},"it":{"copy_to":["collector.it"],"index":"no","type":"string"},"fr":{"copy_to":["collector.fr"],"index":"no","type":"string"}}},"name":{"similarity":"photonsimilarity","properties":{"loc":{"copy_to":["collector.default"],"index":"no","type":"string","fields":{"raw":{"index_analy
zer":"index_raw","type":"string"}}},"de":{"copy_to":["collector.de"],"index":"no","type":"string","fields":{"raw":{"index_analyzer":"index_raw","type":"string"},"ngrams":{"index_analyzer":"index_ngram","type":"string"}}},"default":{"copy_to":["collector.default","name.en","name.fr","name.de","name.it"],"index":"no","type":"string"},"reg":{"copy_to":["collector.default"],"index":"no","type":"string","fields":{"raw":{"index_analyzer":"index_raw","type":"string"}}},"old":{"copy_to":["collector.default"],"index":"no","type":"string","fields":{"raw":{"index_analyzer":"index_raw","type":"string"}}},"alt":{"copy_to":["collector.default"],"index":"no","type":"string","fields":{"raw":{"index_analyzer":"index_raw","type":"string"}}},"en":{"copy_to":["collector.en"],"index":"no","type":"string","fields":{"raw":{"index_analyzer":"index_raw","type":"string"},"ngrams":{"index_analyzer":"index_ngram","type":"string"}}},"it":{"copy_to":["collector.it"],"index":"no","type":"string","fields":{"raw":{"index_analyzer":"index_raw
","type":"string"},"ngrams":{"index_analyzer":"index_ngram","type":"string"}}},"fr":{"copy_to":["collector.fr"],"index":"no","type":"string","fields":{"raw":{"index_analyzer":"index_raw","type":"string"},"ngrams":{"index_analyzer":"index_ngram","type":"string"}}},"int":{"copy_to":["collector.default"],"index":"no","type":"string","fields":{"raw":{"index_analyzer":"index_raw","type":"string"}}}}},"state":{"properties":{"de":{"copy_to":["collector.de"],"index":"no","type":"string"},"default":{"copy_to":["collector.default"],"index":"no","type":"string"},"en":{"copy_to":["collector.en"],"index":"no","type":"string"},"it":{"copy_to":["collector.it"],"index":"no","type":"string"},"fr":{"copy_to":["collector.fr"],"index":"no","type":"string"}}}}}}
[main] INFO de.komoot.photon.App - starting import from nominatim to photon with languages: en,fr,de,it
[main] INFO de.komoot.photon.nominatim.NominatimConnector - start importing documents from nominatim ...

**Comment by christophlingg** [comment]
> password authentication failed for user "nominatim"

you did not provide the correct database credentials

**Comment by maraev** [comment]
Sorry to keep you but how can I make it clean and start again? I didn't change anything.

**Comment by christophlingg** [comment]
just delete the `photon_data` directory, that's how you start from scratch

**Comment by maraev** [comment]
I've got one more question, if I'm not keeping you) Can I import just osm like files form geofabrik via  photon? I have to take a lot of trouble over nominatim database.

**Comment by christophlingg** [comment]
you have to take the hard way with nominatim yes. it is because nominatim is processing the data to a format we need it.

**Comment by maraev** [comment]
Well, it means we haven't any other ways , right?

**Comment by christophlingg** [comment]
well, you can take the prebuilt dumps mentioned on the readme of this project. but the might not be available for your language.

**Comment by maraev** [comment]
Hm..ok. I'd really appreciate your help

**Comment by christophlingg** [comment]
you are welcom

**Comment by phibo23** [comment]
I also had the "password authentication failed for user "nominatim"" problem. But I'm quite sure, that I used the default credentials when installing nominatim (user "nominatim", no password), which are also the default params for photon.

I had a look into the posgresql log file:
```
2015-06-22 15:51:05 CEST FATAL:  password authentication failed for user "nominatim"
2015-06-22 15:51:05 CEST DETAIL:  Connection matched pg_hba.conf line 92: "host    all             all             127.0.0.1/32            md5"
```
If you follow the nominatim installation guide, you don't create a password at all, nominatim relies on ident authentication (linux username == postgresql username). Therefore there is no password that could match the md5 authentication. this is also stated in the postgresql doc:
> If no password has been set up for a user, the stored password is null and password authentication will always fail for that user.
> http://www.postgresql.org/docs/9.3/static/auth-methods.html#AUTH-PASSWORD

so the solution is to create a password for the nominatim postresql user. You can create an empty string password as follows:
```
su postgres
psql
ALTER USER username WITH ENCRYPTED PASSWORD '';
```
Afterwards, photon nominatim-import should work using the default params.

**Comment by christophlingg** [comment]
I remember we allowed to skip the command line argument for the database password. And I remembered that it worked, however maybe this is also system dependend...?

**Comment by phibo23** [comment]
hm... I think the only things this can depend on are postgresql in general, the actual postgresql instance config/user and the authentication mechanism you use in your code.

According to the docs, the "default password is null, thus password authentication will fail if you don't provide one to the user" behaviour has been the same since at least postgresql 7.1 http://www.postgresql.org/docs/7.1/static/auth-methods.html#AEN13285 (that was 14 years ago)

Maybe you did setup your own nominatim database with an (empty) password or you used ident authentication in earlier versions of photon?

btw: yes, you do allow to skip the command line parameter for the password, that's what I meant by using the default params of photon. ;)

**Comment by karussell** [comment]
Is this related to #177 ?

**Comment by karussell** [comment]
As the import works now again - can this be closed?

**Comment by phibo23** [comment]
is this question directed at me? I found a solution for my import and because importing is something you do rather infrequently I haven't tried again since (and I also don't have the resources to do so just for testing).

**Comment by karussell** [comment]
@phibo23 import is working fine for us (we are doing it weekly). Which problems did you stumbled over?

**Comment by phibo23** [comment]
see my other comments. ;) something with postgresql authentication as nominatim user. I don't remember all the details, that was over half a year ago.

As far as I'm concerned, you can close, but I don't know if OP's problem was solved.

**Comment by karussell** [comment]
And would you have time to verify that the import is now working for you?

**Comment by phibo23** [comment]
sorry, our photon installation is part of a project we currently cannot spend much time on and I don't want to risk anything going wrong and causing downtime. never touch a running system. 

just close the ticket. I promise I will report any problems that might occur in future. :wink:

**Comment by RhinoDevel** [comment]
The password-problem is still happening, e.g. with:

- Debian 9.3 / Stretch
- PostgreSQL 9.6
- Nominatim 3.0.1 without password for user nominatim
- Photon [4f4942e01ce410428a1793b8c0f996f596b7a7ad](https://github.com/komoot/photon/commit/4f4942e01ce410428a1793b8c0f996f596b7a7ad)

BUT phibo32's solution only works, if the password chosen is not empty.

**Comment by karussell** [comment]
Thanks for testing the latest version! Why do you need an empty password?

**Comment by RhinoDevel** [comment]
Thanks to you for photon!

There is no need for an empty password.

Just wanted to update this site for anybody having the same problem.

Is there a way to let photon try to use Postgres's peer authentication (without any password)
before attempting to use MD5 password authentication?

As most people IMHO do not have a nominatim user password set
(because they were following the official Nominatim installation instructions - like me),
this would be nice.

**Comment by karussell** [comment]
I do not know, sorry.
