### ISSUE TITLE
question regarding place names in different languages

### ISSUE THREAD

**Issue by phibo23** [komoot/photon#171]
How are the different language entries indexed and searched? I created a custom index of Europe for German and English. After playing around a bit I noticed that I could not find some foreign citys, if I used their German names. For example:

api?q=warschau&osm_tag=place:city returns no results
api?q=warsaw&osm_tag=place:city returns the entry for warsaw in English
api?q=warsaw&osm_tag=place:city&lang=de returns the same entry with the German name "Warschau"
I can also successfully search for the native Polish name "Warszawa"

So my first guess was, that only the native names are indexed for search (the English name being close enough to match in this case), and the other languages only being used for output.

But then I tried some more and found some few counterexamples. For example, I can find Florence, no matter if I use the English name or the German "Florenz" or the native "Firenze"

**Comment by christophlingg** [comment]
when you select english, you can search for native and english place names, in case of the Danish capital this is: `København` and `Copenhagen`. When german is selected you won't find the capital via `Copenhagen` but with `Kopenhagen`.

So you were guessing right. Counterexamples are most likely due to similarities.

**Comment by phibo23** [comment]
hm... that does not seem to work in my case. Neither Kopenhagen with lang=de nor Copenhagen with lang=en return any results, even though the result for København is shown in the language I choose in the query. Any Ideas?

**Comment by phibo23** [comment]
It appears that the language specific indices are empty... when I do
```
curl 'http://localhost:9200/photon/place/_search' -d '{
  "query": {
    "bool": {
      "must": {
        "match": {
          "collector.default": {
            "fuzziness": 1,
            "query": "ko*",
            "analyzer": "search_ngram",
            "prefix_length": 2
          }
        }
      }
    }
  },
  "filter": {
    "and": {
      "filters": [
        {
          "term": {
            "osm_key": "place"
          }
        },
        {
          "term": {
            "osm_value": "city"
          }
        }
      ]
    }
  }
}'
```
I get results which include the following:
```
{
  "_index": "photon",
  "_type": "place",
  "_id": "106465",
  "_score": 2.088108,
  "_source": {
    "osm_key": "place",
    "importance": 0.375,
    "coordinate": {
      "lon": 12.5700724,
      "lat": 55.6867243
    },
    "name": {
      "de": "Kopenhagen",
      "default": "København",
      "en": "Copenhagen"
    },
    "context": {},
    "state": {
      "de": "Hauptstadtregion",
      "default": "Region Hovedstaden",
      "en": "Capital Region of Denmark"
    },
    "osm_id": 13707878,
    "osm_type": "N",
    "osm_value": "city",
    "country": {
      "de": "Dänemark",
      "default": "Danmark",
      "en": "Denmark"
    }
  }
}
```
But if I use "collector.de" or "collector.en", I get
```
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}
```

**Comment by christophlingg** [comment]
Reasons can be manyfolded, could be that the copenhagen item was not proccessed right by nominatim or photon's importer (wrongly calculated score, wrong attached information). That's not so unlikely because entities are mapped very differently in various countries. Maybe it's also a problem with photon's search logic.

**Comment by maraev** [comment]
I'd be greatful if the names in cyrilic will apear

**Comment by phibo23** [comment]
@maraev that should be possible if you create your own index with the "-languages ru" option, also use this option when starting photon and add "&lang=ru" to the URL
Do you still have problems with the import? Did my solution (https://github.com/komoot/photon/issues/170#issuecomment-114134568) not help in your case?

@christophlingg I'm not sure if you see the same problem that I see and if I understand your code correctly. I modeled the elastic search query in my previous comment as a simplified version of https://github.com/komoot/photon/blob/master/es/query_tag_key_value_filter.json#L24 The highlighted line is the one that should enable language specific search, right? What I tried to investigate is whether there is any content in the collector.${lang} indices at all. Because I used a query string of just two letters and did not get any results, I think it's safe to say that no language specific names were indexed. 

Now my first assumption was, that something went wrong during my import, but it appears that your own index has the same problem:
http://photon.komoot.de/api/?q=københavn&osm_tag=place:city (1 result)
http://photon.komoot.de/api/?q=copenhagen&osm_tag=place:city&lang=en (0 results)
http://photon.komoot.de/api/?q=kopenhagen&osm_tag=place:city&lang=de (0 results)

http://photon.komoot.de/api/?q=warschau&lang=de (no result actually in Poland)

http://photon.komoot.de/api/?q=köln&lang=de (correct results, does not return the actual city, but that's probably another issue)
http://photon.komoot.de/api/?q=cologne&lang=en (wrong results)

http://photon.komoot.de/api/?q=strasbourg (correct results)
http://photon.komoot.de/api/?q=straßburg&lang=de(wrong results)

http://photon.komoot.de/api/?q=bratislava&osm_tag=place:city (correct result)
http://photon.komoot.de/api/?q=pressburg&osm_tag=place:city&lang=de (0 results)

I did not find a single case that convinced me that language specific search actually works.

**Comment by maraev** [comment]
Now, that is fine.
I've just downloaded the full world index and assumed that it was compiled
without a ru-language support

2015-06-30 12:33 GMT+03:00 Philipp <notifications@github.com>:

> @maraev <https://github.com/maraev> that should be possible if you create
> your own index with the "-languages ru" option, also use this option when
> starting photon and add "&lang=ru" to the URL
> Do you still have problems with the import? Did my solution (#170
> (comment)
> <https://github.com/komoot/photon/issues/170#issuecomment-114134568>) not
> help in your case?
>
> @christophlingg <https://github.com/christophlingg> I'm not sure if you
> see the same problem that I see and if I understand your code correctly. I
> modeled the elastic search query in my previous comment as a simplified
> version of
> https://github.com/komoot/photon/blob/master/es/query_tag_key_value_filter.json#L24
> The highlighted line is the one that should enable language specific
> search, right? What I tried to investigate is whether there is any content
> in the collector.${lang} indices at all. Because I used a query string of
> just two letters and did not get any results, I think it's safe to say that
> no language specific names were indexed.
>
> Now my first assumption was, that something went wrong during my import,
> but it appears that your own index has the same problem:
> http://photon.komoot.de/api/?q=københavn&osm_tag=place:city (1 result)
> http://photon.komoot.de/api/?q=copenhagen&osm_tag=place:city&lang=en (0
> results)
> http://photon.komoot.de/api/?q=kopenhagen&osm_tag=place:city&lang=de (0
> results)
>
> http://photon.komoot.de/api/?q=warschau&lang=de (no result actually in
> Poland)
>
> http://photon.komoot.de/api/?q=köln&lang=de (correct results, does not
> return the actual city, but that's probably another issue)
> http://photon.komoot.de/api/?q=cologne&lang=en (wrong results)
>
> http://photon.komoot.de/api/?q=strasbourg (correct results)
> http://photon.komoot.de/api/?q=straßburg&lang=de(wrong results)
>
> http://photon.komoot.de/api/?q=bratislava&osm_tag=place:city (correct
> result)
> http://photon.komoot.de/api/?q=pressburg&osm_tag=place:city&lang=de (0
> results)
>
> I did not find a single case that convinced me that language specific
> search actually works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/komoot/photon/issues/171#issuecomment-117085530>.
>



-- 
Best Regards!
Andrey Maraev

**Comment by christophlingg** [comment]
@phibo23 I had a deeper look on the problem with copenhagen. The document is stored correctly in photon:

```json
{
    "_index": "photon",
    "_type": "place",
    "_id": "AUtzFjGKstrGvgk0i6Vy",
    "_version": 1,
    "_score": 1,
    "_source": {
        "osm_key": "place",
        "importance": 0.7405828604198337,
        "coordinate": {
            "lon": 12.5700724,
            "lat": 55.6867243
        },
        "name": {
            "de": "Kopenhagen",
            "default": "København",
            "it": "Copenaghen",
            "fr": "Copenhague",
            "en": "Copenhagen"
        },
        "context": { },
        "state": {
            "de": "Hauptstadtregion",
            "default": "Region Hovedstaden",
            "en": "Capital Region of Denmark"
        },
        "osm_id": 13707878,
        "osm_type": "N",
        "osm_value": "city",
        "country": {
            "de": "Dänemark",
            "default": "Danmark",
            "it": "Danimarca",
            "fr": "Danemark",
            "en": "Denmark"
        }
    }
}
```
Note the correct international names and the high score (0.74). From a data perspective everythings seems fine, so it must be a problem with the elasticsearch query. And in fact, with the addition of osm tags filter, the language filter got broken apparently.

I will provide a fix

**Comment by christophlingg** [comment]
@phibo23 thanks for opening this ticket and keep asking. the bug is fixed and you can see that your example urls are working as expected.

**Comment by phibo23** [comment]
great, thanks! :) 
does this mean that the index is fine and the bug was only in the query code? Or do I have to recreate my custom index?

**Comment by christophlingg** [comment]
Thanksfully I had to change the query only, the index is fine.
