### ISSUE TITLE
Can't search for localized names

### ISSUE THREAD

**Issue by jk** [komoot/photon#172]
It looks like it's not possible to search for localized names. For instance: searching for ["france"](photon.komoot.de/api/?q=frankreich) will give you want to expect: The border of france. But if you search for the german name of france ["frankreich"](photon.komoot.de/api/?q=frankreich) you get embassy's etc. but not the border of france.

Did I miss something or is this not possible with Photon?

**Comment by christophlingg** [comment]
That is a bug that I am currently fixing, see also #171

**Comment by jk** [comment]
@christophlingg Thanks for the quick reply. Didn't recognize that your issue targets the same problem. I'll close my issue.
