### ISSUE TITLE
Location is ignored (missing in FilteredPhotonRequestHandler.java)

### ISSUE THREAD

**Issue by d-manske** [komoot/photon#174]
Since using photon (=>0.2.2) I was wondering about location bias of a request.
I couldn't see any effect of the lat/lon parameters. After some digging in the code I found that `withLocationBias(photonRequest.getLocationForBias()).` is missing in `FilteredPhotonRequestHandler.java`.

**Comment by christophlingg** [comment]
@sdole are you going to have a look on it or shall I?

**Comment by karussell** [comment]
Is this already fixed?
I suppose so due to discussion in #179 (?)

**Comment by christophlingg** [comment]
yes, this was fixed fot both request handlers [1](https://github.com/komoot/photon/commit/5137284dfdf8d10f902055dd3efd7fb95b087597) [2](https://github.com/komoot/photon/commit/94c6b975ce221da8aacb5ee73de98f27e1354db0)
