### ISSUE TITLE
--recreate-index does not delete old index

### ISSUE THREAD

**Issue by christophlingg** [komoot/photon#176]
as a result, this error message pops up:

> org.elasticsearch.indices.IndexAlreadyExistsException: [photon] already
> exists

**Comment by karussell** [comment]
Also the ElasticSearch server should be stopped otherwise the command does never exit without CTRL+C

**Comment by karussell** [comment]
And does it make sense to do 'return'? Because if you import and just want to remove the index before the application will then 'return' and no import is done.

**Comment by swen100** [comment]
this bug still exists... :(

**Comment by lonvia** [comment]
#582 has removed --recreate-index.
