### ISSUE TITLE
Automated updated data infrastructure

### ISSUE THREAD

**Issue by karussell** [komoot/photon#178]
To avoid email ping pong and make the process a bit more transparent I've created this issue here.

As a 'joint venture' of graphhopper (for the producing machines) and most importantly @lonvia for setting up nominatim, we will try to produce weekly world wide photon files and provide them to the community. The [first new file](http://photon.komoot.de/data/photon_data_2015-07-17.tar.bz2) is still not automated but created with the new infrastructure.

Todos:
 * [x] test if manual export is producing proper data for photon
 * [x] fix #163
 * [x] write script for 1. updating nominatim and 2. exporting to photon and 3. creating the bz2 and copying to http://photon.komoot.de
 * [x] make process automated - should we provide an auto update script? -> Not yet. Replacing directories and restart should be sufficiently easy.

**Comment by karussell** [comment]
The first automatically created result is now available via:
`wget http://download1.graphhopper.com/public/photon-db-latest.tar.bz2`

Or see Readme how to uncompress at the same time! Then replace with the latest ElasticSearch folder and restart!

Thanks again & a lot @lonvia

**Comment by christophlingg** [comment]
great @karussell !

Are you fine with mentioning your up-to-date dump on the readme? Currently our server has 650 GB Traffic a month. We could also use photon.komoot.de as a mirror if traffic get's to high.

**Comment by karussell** [comment]
ok and 650GB should be fine for now
