### ISSUE TITLE
Running self-hosted server with SSL

### ISSUE THREAD

**Issue by routexl** [komoot/photon#185]
Currently I am setting up my own Photon geocoding server on Amazon EC2. The installation went fine and geocoding works like a charm. But to get it to work with my website I need https.

You have solved this for the public API (https://github.com/komoot/photon/issues/113) but how to implement this on a self-hosted server?

**Comment by christophlingg** [comment]
I don't think I can help you. This is related to you EC2 setup rather than to photon. You should better ask in an EC2 forum.

**Comment by routexl** [comment]
Thank you for your swift answer!

Just to make sure, there are no special settings needed for Photon? It has SSL support out of the box with the basic installation?

`java -jar photon-0.2.5.jar`

**Comment by sdole** [comment]
For ssl, you need a certificate installed on your web server. That
certificate should identify you and should preferably be issued by a known
authority.

**Comment by routexl** [comment]
Solved!

For who is interested in the solution: I have added a Elastic Load Balancing in front of the Photon server. The load balancer has SSL and routes traffic through. Nice advantage is to be able to add more servers, even dynamically, and handhaking is done on the load balancer.

Looking forward to https://github.com/komoot/photon/issues/178 ;-)
