### ISSUE TITLE
make PhotonRequestFactory.setUpTagFilters reusable

### ISSUE THREAD

**Issue by karussell** [komoot/photon#189]
I would like to overwrite some parameters e.g. use locale instead of lang and for that I simple extended PhotonRequestFactory but had to copy the private method setUpTagFilters. So a simple workaround would be to make it protected or make it otherwise easier to reuse this behaviour.

**Comment by lonvia** [comment]
@karussell Is this still relevant?

**Comment by karussell** [comment]
Don't think so :)
