### ISSUE TITLE
AbstractReverseRequestHandler should have a changeable limit parameter

### ISSUE THREAD

**Issue by karussell** [komoot/photon#190]
Currently the [limit for reverse geocoding is 1](https://github.com/komoot/photon/blob/master/src/main/java/de/komoot/photon/searcher/AbstractReverseRequestHandler.java#L25). Sometimes it is interesting to return more than this. And this should be controllable via the same 'limit' parameter as for the forward geocoding. Also [this subListing](https://github.com/komoot/photon/blob/master/src/main/java/de/komoot/photon/ReverseSearchRequestHandler.java#L48) should be removed or extended to match the limit parameter.

And additionally one should be able to filter by osm_tag ... 

So the reverse search should be more align with the forward search

**Comment by vera20** [comment]
I 've tried to change the values ​​but it returned 1 result.  Have I change something else? sorry for my english.

**Comment by masda70** [comment]
This pull should take care of this issue.

https://github.com/komoot/photon/pull/219

**Comment by hbruch** [comment]
Closing this issue as the limit parameter was introduced with #254. Note: it is fixed to an upper bound of 50.
