### ISSUE TITLE
Higher weight to name field

### ISSUE THREAD

**Issue by mannieg** [komoot/photon#193]
Hi,

It is possible to pass on higher weight to exact matches in the name field? 

Thanks

**Comment by karussell** [comment]
Do you have an example where improvement is necessary?

I have an example for a partial match: 'amsterda'

**Comment by lonvia** [comment]
One idea: when the search query consists of only of one term, search in names only.

**Comment by lonvia** [comment]
#580 would help with this. It boosts the name for one term queries.

**Comment by lonvia** [comment]
#580 is now merged which has some improvements on the name preference. If you have more specific issues that are still there in the current version, open a new issue.
