### ISSUE TITLE
ReverseGeocoding performance

### ISSUE THREAD

**Issue by masda70** [komoot/photon#196]
Using photon's provided ~60GB search index, I've tested the performance of forward and reverse queries  using JVM with 4GB on a 2-core (HT) machine (I'm using the index for local processing and I don't have the resources to allocate more). While forward geocoding querying is giving me a reasonable throughput (I don't have the exact figure right now but it's in the order of 10 to 100 queries/s), reverse geocoding leaves a lot to be desired with a throughput of 0.9 queries/s. 
It appears that the first query is usually very slow (the server times out), then subsequent queries quickly reach cruise speed at 0.9 q/s. After investigating, I noticed that photon did not use a disk-based spatial index for improving the performance reverse geocoding queries, rather, it uses `"optimize_bbox": "memory"` queries that might not be as efficient on a low memory JVM (I do not know for sure since I did not test this on a high RAM JVM).
Perhaps a "coordinate" disk index (`"lat_lon": true` in `mappings.json`) and non-memory `optimize_bbox` queries might be a more reasonable default?

**Comment by karussell** [comment]
ElasticSearch has improved in the area a lot over the last few months so it might be indeed wise to revisit the various options for spatial search under different conditions.

(BTW: We are running with roughly twice the RAM and getting twice the q/s)

**Comment by masda70** [comment]
Great. I also forgot to mention that I modified the code to return the 20 closest matches, but I'm glad I'm not too far from the expected performance.

Right now I'm reindexing the whole cluster with a lat_lon index. Will report on the performance improvement when I'm done (if I do not encounter an error creating a dump, this already happened once).

**Comment by masda70** [comment]
I got to reindex it with `lat_lon: true` and I also reduced to lookup radius to 1 kilometer. I'm at 50 requests/sec now.

**Comment by karussell** [comment]
Nice! Would you mind to create a pull request?

**Comment by zheffie** [comment]
Can you share the required steps to achieve your performance?

**Comment by llambda** [comment]
@masda70 can you share the steps to improve the performance?

**Comment by llambda** [comment]
I'll offer a $50 bounty for this.

**Comment by masda70** [comment]
@karussell @zheffie @llambda 
I have not found the time to push a clean solution. Mainly I was not entirely satisfied since as far as I remember there is choice to be made regarding the search radius, the result order. They affect the type of geo index and how the query is performed. My first conclusion was that my initial solution could be improved performance-wise. I will try to take a look at it and post what I have ASAP since I'm interested in benefiting from this change in the latest photon dumps.

**Comment by karussell** [comment]
If you find time would be nice how everything could work for 2.2 :)
https://twitter.com/elastic/status/685177791222947840

**Comment by masda70** [comment]
Oh great!
When are you planning to land ES 2.2 in photon?

**Comment by karussell** [comment]
> When are you planning to land ES 2.2 in photon?

Feel free to provide a PR - it should not be that complicated to upgrade as we do not use many internal classes or crazy concepts

**Comment by masda70** [comment]
I've submitted a PR for ES 2.2 https://github.com/komoot/photon/pull/217
Please test review it and test it as much are you are able to.

I will shortly submitted a PR with performant reverse geocoding.

**Comment by masda70** [comment]
Reverse geocoding API improvement :
https://github.com/komoot/photon/pull/219

**Comment by Muneer94** [comment]
@karussell I have setup photon locally. I am getting 25 ms response time for search but I only problem is with reverse it's response time of 28 to 31 sec which doesn't sound practical.
I don't think hardware is a problem I am running it on 64Gb RAM with SSD. Any suggestions with the reverse respone time improvement.

When would I expect the PR  #219 to be tested and merged, I am awaiting for the PR to be merged

**Comment by karussell** [comment]
Fixed via #254
