### ISSUE TITLE
Cannot search by limit

### ISSUE THREAD

**Issue by KentJacobs** [komoot/photon#201]
Hi,

I've followed the instructions on the regular installation (https://github.com/komoot/photon#installation). 

I am able to curl http://localhost:2322/api?q=berlin or http://localhost:2322/api?q=munich, for example, and get results but as soon as I restrict that to a limit (ie, curl http://localhost:2322/api?q=berlin&limit=2) I get the results for Berlin without a limit (http://localhost:2322/api?q=berlin).

Is this a bug, or am I missing part of the installation?

**Comment by christophlingg** [comment]
seems like a but, but it cannot be reproduced on our public api:

http://photon.komoot.de/api?q=munich&limit=2

are you sure about it? what results do you get instead?

**Comment by KentJacobs** [comment]
I get all the results for Munich when I curl localhost:2322/api?q=munich...

  "type": "FeatureCollection",
  "features": [
    {
      "geometry": {
        "coordinates": [
          11.5754815,
          48.1372719
        ],
        "type": "Point"
      },
      "type": "Feature",
      "properties": {
        "country": "Germany",
        "osm_value": "administrative",
        "osm_type": "R",
        "osm_id": 62428,
        "state": "Free State of Bavaria",
        "name": "Munich",
        "extent": [
          11.3607802,
          48.2482197,
          11.7228777,
          48.0616017
        ],
        "osm_key": "boundary"
      }
    }..... and so on

As soon as I add "&limit=2" (or any search specification for that matter after =munich) it doesn't recognize it in the search and will only search /api?q=munich.

[root@localhost user]# curl localhost:2322/api?q=munich&limit=2

[1] 43159

[root@localhost user]# {"features":[{"properties":{"osm_key":"boundary","extent":[11.3607802,48.2482197,11.7228777,48.0616017],"name":"Munich","state":"Free State of Bavaria","osm_id":62428,"osm_type":"R","osm_value":"administrative","country":"Germany"},"type":"Feature","geometry":{"type":"Point","coordinates":[11.5754815,48.1372719]}},{"properties":{"osm_key":"boundary","extent":[-98.8400979,48.676126,-98.8240889,48.663316],"name":"Munich","state":"North Dakota","osm_id":181652,"osm_type":"R","osm_value":"administrative","country":"United States of America"},"type":"Feature","geometry":{"type":"Point","coordinates":[-98.8326307,48.669174]}}.....

[1]+  Done                    curl localhost:2322/api?q=munich

**Comment by karussell** [comment]
You have to put quotes around the URL otherwise the parameter is not send to photon.

**Comment by KentJacobs** [comment]
Thank you! 

It works with single quotes.
