### ISSUE TITLE
Possible license issue with Nominatim

### ISSUE THREAD

**Issue by utrenkner** [komoot/photon#206]
Hi,

I am following an MIT licensed project which recently started to use Photon. As I want to be sure that we are not running into license issues, I checked and was glad to see that Photon is Apache licensed.

However, digging a little deeper, I found that Photon depends on Nominatim, which is GPLv2 licensed. I have no Java know-how whatsoever and therefore do not know, how exactly you use Nominatim. Depending on the exact "how", Photon may have to be GPL'ed, too.

This is the interpretation of the FSF on the issue (https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#MereAggregation) [excerpt]:
Combining two modules means connecting them together so that they form a single larger program. If either part is covered by the GPL, the whole combination must also be released under the GPL—if you can't, or won't, do that, you may not combine them.

Sorry to come with this license issue. I hate it. I love permissive licenses. But the original author has said you can use Nominatim only of you obey to the GPL.

**Comment by karussell** [comment]
IMO there is no problem as photon just queries a DB and does not use source code of nominatim.
