### ISSUE TITLE
Performance Photon API

### ISSUE THREAD

**Issue by djtak47** [komoot/photon#209]
Hi Guys, just a quick question

We are having response times for a query like berlin around 1.2 seconds. The photon api from http://photon.komoot.de/api is much faster around 50-60ms per request. We are wondering what the problem is, we are running it in a Virtual Machine but not with SSD Harddirves, CPU and RAM is more than enough, 100 MBIT network, any ideas? thanks!

**Comment by karussell** [comment]
Did you assign the photon process enough RAM via the `-Xmx` setting?

**Comment by djtak47** [comment]
yeah we did start it with java -Xmx6G -Xms5G -jar photon-0.2.5.jar -host photon.ourhost.com -listen-port 80

queries are really slow.. also for cached queries we are getting 2seconds and up..

**Comment by karussell** [comment]
Hmmh, maybe the VM you use is constraint? We are also using it successfully with ~10gb but a dedicated server (and SSD disc)

**Comment by christophlingg** [comment]
fyi, photon.komoot.de is running on normal disks and 32 GB RAM

**Comment by djtak47** [comment]
@christophlingg  Interesting. How much ram do you recommend ? 

@karussell, we may try to setup a new instance of the VM just to make sure that this isnt the problem

**Comment by christophlingg** [comment]
I experienced also some warmup time, btw.

I assume a big ram can compensate the absence of fast ssds, via os cache. In your case I would check your disk activity, cup and ram usage while requests are getting in. You should spot the bottleneck then.

**Comment by djtak47** [comment]
Hi, photon is running now on a SSD with 20GB Ram.. performance is now somewhere around 300ms. 
For cache results around 110 ms.

Thanks guys.

**Comment by christophlingg** [comment]
thanks for sharing your insights

**Comment by systemed** [comment]
Just to add a further data point for anyone else encountering this, I've found that moving to SSD has made by far the biggest difference to Photon performance.
