### ISSUE TITLE
Using photon offline

### ISSUE THREAD

**Issue by curiousc0w** [komoot/photon#210]
I was wondering if it is possible to get Photon installed without having an internet connection. If I have the .JAR and search indexes (photon_data), I would like to make sure that when I run ```java -jar photon-0.2.5.jar``` there are no outside net requests. Is it strictly using data I've downloaded and not information from photon.komoot.de?

**Comment by christophlingg** [comment]
it will only use the data you downloaded, you don't need an internet connection

**Comment by curiousc0w** [comment]
Thank you! My workplace does not have access to the outside net so I was wondering if there were any requests.
