### ISSUE TITLE
ElasticSearch failed to list shard for shard_started

### ISSUE THREAD

**Issue by FxKu** [komoot/photon#211]
Hi there,

I'm trying to setup Photon on our Cluster (5 nodes) which works for some minutes after running the jar. I can do requests (from an external machine) and get results back.

Then an infinite number of WARN messages start flooding my console and the service cannot be requested anymore (Bad Gateway):
...
[elasticsearch[Freakmaster][fetch_shard_started][T#6]] WARN org.elasticsearch.gateway.local - [Freakmaster] [photon][0]: failed to list shard for shard_started on node [HqeYYHWGSk6vV8SlWVzfLA]
[elasticsearch[Freakmaster][fetch_shard_started][T#11]] WARN org.elasticsearch.gateway.local - [Freakmaster] [photon][1]: failed to list shard for shard_started on node [HqeYYHWGSk6vV8SlWVzfLA]
[elasticsearch[Freakmaster][fetch_shard_started][T#10]] WARN org.elasticsearch.gateway.local - [Freakmaster] [photon][3]: failed to list shard for shard_started on node [HqeYYHWGSk6vV8SlWVzfLA]
[elasticsearch[Freakmaster][fetch_shard_started][T#7]] WARN org.elasticsearch.gateway.local - [Freakmaster] [photon][2]: failed to list shard for shard_started on node [HqeYYHWGSk6vV8SlWVzfLA]
[elasticsearch[Freakmaster][fetch_shard_started][T#8]] WARN org.elasticsearch.gateway.local - [Freakmaster] [photon][4]: failed to list shard for shard_started on node [HqeYYHWGSk6vV8SlWVzfLA]
... 

When I stop the process and run the jar again, the service doesn't start anymore as the ElasticSearch index seems to be corrupt. Anyone have experiences running Photon on a huge cluster?

Kind regards,
Felix

**Comment by christophlingg** [comment]
No idea why this could happen, I know that @karussell is using photon also on multiple nodes. Probably the problem is more related to elasticsearch than to photon itself. You might get more helpful answers in their community.

**Comment by christophlingg** [comment]
If you find a solution, it would be great if you provide it here!

**Comment by FxKu** [comment]
It's definitely an ElasticSearch problem. I did some research but as I'm new to ES and clusters in general I don't have a clue. I think everything just runs on one cluster node if I look at the messages. 

Of course, I will provide the solution if I will ever find it :)

**Comment by karussell** [comment]
Sorry I have no idea. But why do you need those ES instances to communicate with each other?

**Comment by FxKu** [comment]
I just downloaded the necessary files and ran the the photon.jar. There is no other ES instance installed on the cluster. In the photon_data directory I find five folders inside the indices/photon directory (elasticsearch/data/photon/nodes/0/indices/photon/[0-4] + a _state folder). Is this wrong if just one cluster node is used?

**Comment by karussell** [comment]
> here is no other ES instance installed on the cluster

What do you mean here? Are you using just one server and the other 4 ES instances as client nodes?

Or what do you mean with:

> setup Photon on our Cluster (5 nodes)

**Comment by FxKu** [comment]
Ok, I think I'm getting closer to what the problem is. I'm starting the service on only one node of the cluster. But the files (also the ES index) are lying in HDFS and therefore on each node...

**Comment by karussell** [comment]
Ok, this is reasonable ;)

@christophlingg we can close here
