### ISSUE TITLE
Reverse geocoding radius

### ISSUE THREAD

**Issue by vera20** [komoot/photon#213]
How I can increase the search radius or limit result?

**Comment by Svantulden** [comment]
You could change the distance on this line: https://github.com/komoot/photon/blob/master/src/main/java/de/komoot/photon/query/ReverseQueryBuilder.java#L112

**Comment by vera20** [comment]
How I can get more results in reverse geocoding? I change the distance radius but I still get one result

**Comment by Svantulden** [comment]
I think you can change this line (https://github.com/komoot/photon/blob/master/src/main/java/de/komoot/photon/ReverseSearchRequestHandler.java#L50) to get more results.

**Comment by masda70** [comment]
This pull should take care of this issue.

https://github.com/komoot/photon/pull/219

**Comment by karussell** [comment]
Fixed via #254
