### ISSUE TITLE
Photon Quality of results 

### ISSUE THREAD

**Issue by MartinMekhaiel** [komoot/photon#214]
Hi, 

We are wondering how to improve the results quality example:

If i search für Münch:
http://photon.komoot.de/api?q=M%C3%BCnch 
There is no München in the results which is the most relevant result if you ask me. 

same goes for Berl (Berlin): 
http://photon.komoot.de/api?q=Berl

What can we do here?
Thanks for your response.

**Comment by karussell** [comment]
dup of #193 ?

**Comment by djtak47** [comment]
Yes seems so, is this Feature planned anywhere soon?
