### ISSUE TITLE
Web page demo CORS error on http://photon.komoot.de/

### ISSUE THREAD

**Issue by esyscoder** [komoot/photon#216]
```

GET https://photon.komoot.de/api/?q=havel&limit=5&lat=52.395217918984244&lon=13.053860664367676
	
			
leaflet.photon.js (line 370)
"NetworkError: 404 Not Found - https://photon.komoot.de/api/?q=havel&limit=5&lat=52.395217918984244&lon=13.053860664367676"
?q=have...4367676
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://photon.komoot.de/api/?q=havel&limit=5&lat=52.395217918984244&lon=13.053860664367676. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

**Comment by christophlingg** [comment]
can you please create a [jsfiddle](https://jsfiddle.net/) and let me know which browser you are using. Otherwise it's hard to tell, because in general it works.

**Comment by lonvia** [comment]
@christophlingg The issue is with mixing http and https, not with the CORS headers. Try using '//photon.komoot.de/api/?' in API_URL instead of 'https://photon...'.

**Comment by esyscoder** [comment]
Yes, just like I wrote, using http://photon.komoot.de/ will generate this error. https://photon.komoot.de/ works.

**Comment by christophlingg** [comment]
thanks, fixed
