### ISSUE TITLE
ubuntu autostart nodes remain unassigned

### ISSUE THREAD

**Issue by christophmayrhofer** [komoot/photon#223]
I want to autostart photon and therefore created a shell script:

`java -jar /home/ubuntu/photon.jar`

I then added a new entry to /etc/rc.local to run the script at startup:

`nohup /home/ubuntu/photon.sh &
`
This works fine when I manually run /etc/rc.local. However, all nodes remain unassigned when it is run automatically upon a reboot and the photon API returns: Internal server error 500

**Comment by christophlingg** [comment]
probably it's because you need to run the script from the same folder where `photon_data` is in. something like this:

`cd /home/ubuntu && java -jar /home/ubuntu/photon.jar`

**Comment by christophmayrhofer** [comment]
perfect.. fixed the issue, thanks for the hint.
