### ISSUE TITLE
Reverse geocoding query with tags

### ISSUE THREAD

**Issue by fran320** [komoot/photon#224]
It's possible to define a query with tags, into a reverse geocoding query?

**Comment by SuberFu** [comment]
I would like to know the answer to this too. I've tried the demo page and used the `osm_tag` parameter for reverse geocoding but it doesn't seem to do anything.

**Comment by stephan75** [comment]
Can you give us an example query?

Or describe an example what you expect as result, with what input given.

**Comment by SuberFu** [comment]
`http://photon.komoot.de/reverse?lon=10&lat=52&osm_tag=healthcare`
returns the same as
`http://photon.komoot.de/reverse?lon=10&lat=52`
I would've expected the first query to return the nearest healthcare facility. Granted, I could be very wrong on what osm_tag actually means.

**Comment by hbruch** [comment]
Tag filtering currently is not implemented for reverse geocoding. It would be helpful to filter e.g. for buildings (which often have housenumber information) or to exclude e.g. highway=street_lamp, which seldom has housenumber information.

**Comment by lonvia** [comment]
You can do this now with the `query_string_filter` parameter, e.g. http://photon.komoot.de/reverse?lat=52.9112327&lon=-1.4786067&query_string_filter=osm_key:highway
