### ISSUE TITLE
Avoid osm value 'historic'

### ISSUE THREAD

**Issue by karussell** [komoot/photon#228]
See discussion [here](https://discuss.graphhopper.com/t/geocoding-engine-should-omit-or-demote-historic-names/805) where a not so relevant entry is returned and not expected:

```
osm_id: 6205453
osm_key: "boundary"
osm_type: "R"
osm_value: "historic"
```

**Comment by lonvia** [comment]
Possibly something that should already be excluded by Nominatim.

**Comment by lonvia** [comment]
Tweaked that slightly on the Nominatim side. As long as they don't have a wikipedia tag that unexpectedly boosts importance, historic boundaries don't show up as top results anymore. If you still get them, check the OSM data.
