### ISSUE TITLE
Is there an option to get the access logs?

### ISSUE THREAD

**Issue by arungowtham** [komoot/photon#230]
Hi does photon(jetty server) has its access logs stored anywhere, or is there an option to enable it?
Am in need to monitor the requests that reach photon, so how do i do it ?

**Comment by christophlingg** [comment]
photon does not log requests, maybe there are some ways to have [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/guide/current/logging.html) or [putty](https://www.eclipse.org/jetty/documentation/9.3.x/configuring-logging.html) log their requests.

Normally I run photon behind a webserver like nginx. In that case one could easily configure nginx to log requests.
