### ISSUE TITLE
Photon.db files missing

### ISSUE THREAD

**Issue by SabbeRubbish** [komoot/photon#232]
Hi, the links to the photon database files (35GB) are broken. Are they still begin provided? Or should we abandon the photon project?

**Comment by karussell** [comment]
Why do you think it is broken. See https://github.com/komoot/photon/issues/231

**Comment by SabbeRubbish** [comment]
Sorry, curl did the trick. Maybe you should explicitly state that in the documentation, seeing that you get so many questions about it.
Another thing I was thinking about, is there a way to build these databases myself? I am only looking for geocoding for 1 particular country, making the 35GB download unnecessary.

**Comment by karussell** [comment]
Sure, you need to install nominatim and then use the nominatim import (`-nominatim-import true`)

**Comment by christophlingg** [comment]
@SabbeRubbish I did not get what your problem was. can you let me know how to improve the readme?

**Comment by SabbeRubbish** [comment]
Hi Christoph,
Try to explicitly mention that downloading the photon db files using a webbrowser does not work and that it requires wget or curl to download it properly. That would surely reduce the number of *stupid* questions :-) :+1:

**Comment by christophlingg** [comment]
@SabbeRubbish  https://github.com/komoot/photon/commit/5a42e7908a45a2caacc2f6224472202768dc74be done. Thanks for your feedback
