### ISSUE TITLE
Local interface Server

### ISSUE THREAD

**Issue by FlorianHergo** [komoot/photon#233]
Hello,

I installed Photon on a new server and I note that even if there is no installation of Apache or nginx, JAR create a virtual web server?
In my case that's fine, because I did not install Apache or nginx to limit securisation.

I liked whether it was possible to limit the opening only on interface 127.0.0.1
And therefore to have no opening to the public.

Thank you.

**Comment by karussell** [comment]
Use `-listen-ip 127.0.0.1` or -white-ips option as protection

**Comment by FlorianHergo** [comment]
Perfect.

By chance, would you have expected a console directly, rather than HTTP.
Where possible simply calls from PHP.

My goal is to minimize latency. Here I make a CURL of PHP since 127.0.0.1:2223. Latency is a few hundred milliseconds, that's fine, but I would reduce it.

**Comment by christophlingg** [comment]
local http calls should be very fast. the latency comes from the complex search of the huge address database.
