### ISSUE TITLE
Special house number not working

### ISSUE THREAD

**Issue by karussell** [komoot/photon#235]
And address like this "Emanuel-Geibel-Str. 21, 49143 Bissendorf, Deutschland" has no "house number"-precise match:

http://photon.komoot.de/api/?q=Emanuel-Geibel-Str.%2021%2C%2049143%20Bissendorf%2C%20Deutschland

The underlying data looks [a bit strange](https://www.openstreetmap.org/way/252652694) "19+21" ... not sure if this is properly tagged. But also the other building 3+5 of this street has this and we should support this if this is frequently used.

**Comment by lonvia** [comment]
These are data errors. If at all, the separator between housenumbers should be a semicolon. See also #139.
