### ISSUE TITLE
Search index database link not working

### ISSUE THREAD

**Issue by pawelkania** [komoot/photon#236]
Link http://download1.graphhopper.com/public/photon-db-latest.tar.bz2 is not working. It returns 404 status.

**Comment by karussell** [comment]
Yes, there is a disc related problem. We are investigating.

**Comment by gliwka** [comment]
Any updates on this issue? Would it be possible to create a .torrent or other means of distribution for the time being?

@karussell Thanks for hosting this!

**Comment by karussell** [comment]
We (or more precisely @lonvia) had to setup up a completely new postgresql&nominatim installation (after migrating to the latest OS version). So it still processes the import and we hope for a new photon export on Wednesday.

> Would it be possible to create a .torrent or other means of distribution for the time being?

Sorry, have no experience with this.

> @karussell Thanks for hosting this!

Thanks! And it is not just me: @lonvia :) !

**Comment by karussell** [comment]
The photon export started now and will take 1-2 days. The issue #238 is already merged for this.

For the time being I've restored a ~4 weeks old dump, get it via

`wget http://download1.graphhopper.com/public/photon-db-tmp.tar.bz2`

**Comment by christophlingg** [comment]
thanks @karussell photon will be available again soon

**Comment by yohanboniface** [comment]
Thank you amigos :)

**Comment by gliwka** [comment]
@karussell Thanks a lot!

**Comment by christophlingg** [comment]
the download of the dump takes a lot of time, i assume there is some throttling on graphhopper.com .  70 GB are downloaded until now, should not be much left to download.

**Comment by karussell** [comment]
Ah, yes. I had this protection in place when it was on the same subdomain as our API. Will increase a bit. Export also still going on but looks healthy.

**Comment by karussell** [comment]
The export is done. @christophlingg @lonvia is it normal and expected that it is only ~38gb instead of prev. ~40gb?

**Comment by lonvia** [comment]
I might have been a bit conservative with address interpolations. There is a check in there that start and end number must not be more than 1000 apart, see https://github.com/komoot/photon/pull/238/files#diff-7367625298e9e735a63583c4b0f27452R96.

Currently there are around 9.5k interpolations like this in the database which would expand to around 100 mio documents in photon. A large part seems to be from imports in Canada. Some examples:

http://www.openstreetmap.org/way/96797540
http://www.openstreetmap.org/way/297965980
http://www.openstreetmap.org/way/241053411 (startnumber is -1 here, so clearly a missing value in the import data)

I think it is perfectly fine to leave them all out until photon can handle interpolations on the fly.

**Comment by karussell** [comment]
Ok.

> (startnumber is -1 here, so clearly a missing value in the import data)

What does it mean -1? 'Unknown'?

**Comment by christophlingg** [comment]
been conservative here is totally sensible

**Comment by christophlingg** [comment]
photon is up again, btw. thanks @karussell for the old dump

**Comment by karussell** [comment]
The download link is working again:

wget http://download1.graphhopper.com/public/photon-db-latest.tar.bz2

(keep in mind that due to a server config an access via browser is not intended/possible)

**Comment by piotrek-toolla** [comment]
I'd like to reopen this issue.

**Comment by lonvia** [comment]
Works for me.

**Comment by piotrek-toolla** [comment]
Yes, you're right. I seem to have some temporary problems.
