### ISSUE TITLE
Update the Elasticsearch component

### ISSUE THREAD

**Issue by agastya71** [komoot/photon#241]
Since ES has been rapidly releasing new updates to the search engine, (current version 5.1.1), How difficult would it be to update the photo distribution to a newer version of ES.  The version Photon seems to use is at 1.7.0 (per POM file).  I am not sure upgrading ES is as simple as changing the version numbers as  ES has removed support for groovy scripts in their newer versions. (if scoring and reranking  groovy scripts are being used how would that be affected ?) in short, Are there any plans to upgrade the ES versions ?

**Comment by karussell** [comment]
See #217. Groovy isn't a problem as its still available in a separate module.

**Comment by agastya71** [comment]
as an afterthought it occurred to me, should there be such a tight coupling with specific versions of elasticsearch ? would it more appropriate to have a coupling with the Major version and not so much the minor version of ES

**Comment by LilithWittmann** [comment]
@agastya71 in the past there were multiple times minor changes on geo-related functions in elasticsearch, that would have broken photon. So I think it's a better idea (and my original intention) to couple it with a specific version.
