### ISSUE TITLE
Plans to use it on openstreetmap.org ?

### ISSUE THREAD

**Issue by show0k** [komoot/photon#242]
I just found out photon, and I'm astounded by the results !
OSM has better maps than any other commercial platform, but the Nominatim search engine is very deceptive to use. I think that Photon could really change the public adoption of OSM.

Is there any plan to use it on production at openstreetmap.org  ?

**Comment by lonvia** [comment]
There have been some discussions to do that. The main blocking point for me at the moment is that photon is not actively maintained. If photon goes on the main osm.org page there will be more bug reports and I need to be sure that somebody looks after them.

**Comment by LilithWittmann** [comment]
I think there are still a lot of other issues that would have to be solved before photon could be use on osm.org. For example the reverse geocoding is really expensive regarding hardware resource (due the geo search implementation in elasticsearch). But maybe we should start making milestones what would be needed to bring photon to osm.org. (I mean it's 2017 and we are still using nominatim :smile: Ok and somehow I really want to start working on geo stuff again)

**Comment by lonvia** [comment]
As things stand, I would use photon only for search-as-you-type suggestions on osm.org. Given that photon is simply a search frontend for Nominatim data, that's the only true advantage photon has at the moment. For everything else, Nominatim is still way ahead in development. But that doesn't need to stop us.

**Comment by christophlingg** [comment]
I share your opinion @lonvia and @LilithWittmann . For me it is a question of manpower and long-term dedication. Geocoding is not a trivial business and it will take a lot of effort to be able to replace nominatim for osm.org.
