### ISSUE TITLE
Results for partial match omit city

### ISSUE THREAD

**Issue by systemed** [komoot/photon#246]
When typing 'Luxembourg', the results for http://photon.komoot.de/api/?q=luxemb are (in order):

1. Luxembourg (country node)
2. Luxembourg (country boundary relation)
3. Canton Luxembourg relation
4. (and onwards) some random villages and towns in Luxembourg

The city of Luxembourg is not returned at all. Typing the full name (http://photon.komoot.de/api/?q=luxembourg) returns it in fifth place.

Over-ranking area relations and under-ranking cities/towns seems to be a fairly common occurrence. For a lot of purposes (e.g. routing start/end points) the city/town centre is actually what you want, and the boundary relations are effectively noise. I filter and rerank the results client-side to get round this, but obviously this doesn't work (as per the 'luxem' example) if the city result isn't in the results anyway.

**Comment by lonvia** [comment]
This is an issue with the importance computation in the underlying Nominatim instance, so better reported there.

That said, you are running into https://github.com/openstreetmap/Nominatim/issues/562 here. The [city node](http://www.openstreetmap.org/node/52943358) and the [admin boundary](http://www.openstreetmap.org/relation/407489) have been linked, which is questionable but still ok. But then the wikipedia tag of the relation always wins, which in this case goes to the much less important Luxembourg canton.

**Comment by lonvia** [comment]
Has been fixed on the Nominatim side.
