### ISSUE TITLE
Data Import from Nominatim

### ISSUE THREAD

**Issue by directcontrol** [komoot/photon#247]
Hi,
I have successfully installed Nominatim and can see the data on the map. Trying to feed photon the data from it fails with the following error.

> Error: colum "calculated_country_code" does not exist

Regards,
Shankar.

**Comment by lonvia** [comment]
You are using the latest master version of Nominatim which is not yet compatible with photon. I'll add a pull request soon, can't promise any ETA though.

**Comment by directcontrol** [comment]
Thank you, will wait for the update.

**Comment by directcontrol** [comment]
Hi what is current version of Nominatim does photon support. I will revert back to that to get this working. 
Is this a major upgrade to photo?, could you direct me where exactly the changes are required. I will build it locally and use it. 

Regards,
Shankar.

**Comment by lonvia** [comment]
If you must build your own database (as opposed as using the pre-built one from ) use photon 5a42e7908a45a2caacc2f6224472202768dc74be and the last Nominatim release.

Or try replacing `calculated_country_code` with `coutry_code` in NomiantimConnector.java in photon. That might be enough.

**Comment by lonvia** [comment]
@christophlingg I believe that 5a42e7908a45a2caacc2f6224472202768dc74be was the last version still working with the current Nominatim release 2.5.1. Could you tag this commit somehow, so people know what to use?

**Comment by t3asp00n** [comment]
quick question, I ran into this same issue but I'm having trouble making the .jar after making the change in the NominatimConnector.java.

**Comment by schiegg** [comment]
Hello everyone,
just set up a new Nominatim installation and got stuck to the same problem.

Following your advice @lonvia I replaced `calculated_country_code` with `country_code` at all appearances in NominatimConnector.java and build the new version which has now correctly imported all the documents.

@t3asp00n I got a build success with just a few warnings using the newest versions of Maven and JDK. Note that you have to build from the directory [where the pom.xml is located.](https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html)

**Comment by lonvia** [comment]
@schiegg Nice! Do you feel like doing a PR with your changes for the newest Nominatim version?

**Comment by schiegg** [comment]
Yes, I can make a PR with these changes ;)

But maybe there's still a bug in this... 
After executing  `curl http://localhost:2322/nominatim-update` Photon ends with exception `org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [update placex set indexed_status = 0 where place_id = ?];`. 

Does this also have to do with the new Nominatim version? 
With ` Caused by: org.postgresql.util.PSQLException: ERROR: permission denied for relation placex` it looks like a permission issue but the selected user already has all privileges on the nominatim db.

**Comment by MikaelUlvesjo** [comment]
When will a version be relesed with this change?

**Comment by lonvia** [comment]
There are no releases in photon. The most recent git version of photon works with Nominatim 3.0.0.

**Comment by ParasQ** [comment]
Exception in thread "main" org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT place_id, osm_type, osm_id, class, type, name, housenumber, postcode, extratags, ST_Envelope(geometry) AS bbox, parent_place_id, linked_place_id, rank_search, importance, country_code, centroid FROM placex WHERE linked_place_id IS NULL AND centroid IS NOT NULL ORDER BY geometry_sector; ]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "placex" does not exist

**Comment by mtmail** [comment]
@ParasQ Don't comment on issues that got closed 2 years ago. It's not even the same error message, or version of Photon or version of Nominatim. Open a new issue.
