### ISSUE TITLE
Building with addr:place address is not found at all in nominatim

### ISSUE THREAD

**Issue by hubgitti** [komoot/photon#248]
Hi,

the following address:
Edelstauden 9 8081
on the building:
http://www.openstreetmap.org/way/316761916
is not found in nominatim.

Is there any explanation for that, is this a bug in nominatim?

See also the discussion in the Austrian forum:
https://forum.openstreetmap.org/viewtopic.php?id=53532

**Comment by hubgitti** [comment]
See also the German OSM Forum:
https://forum.openstreetmap.org/viewtopic.php?id=58232

**Comment by karussell** [comment]
> is not found in nominatim.

are you sure you are posting to the correct issue tracker? this here is regarding photon ...

**Comment by hubgitti** [comment]
I'm not sure! I tried to post it at:
https://github.com/openstreetmap/Nominatim
maybe I did something wrong, so it got here?

**Comment by hubgitti** [comment]
This was the wrong spot for my issue. Sorry I did something wrong with my post.
