### ISSUE TITLE
Update to ES 5.x?

### ISSUE THREAD

**Issue by reuschling** [komoot/photon#249]
Hi, I was wondering if it is planned to update photon to a current elasticsearch version. In the 5.x line (released ~one year ago), there were again huge performance optimizations regarding [geopoint search](https://www.elastic.co/blog/elasticsearch-5-0-0-released#data-structures).

"Lucene 6 brought a new Points datastructure for numeric and geo-point fields called Block K-D trees, which has revolutionised how numeric values are indexed and searched. In our benchmark, Points are 36% faster at query time, 71% faster at index time and used 66% less disk and 85% less memory (see Searching numb3rs in 5.0). The addition of Points means that the ip field can now support IPv6 as well as IPv4 addresses. On top of that, we have changed geo_point fields to use Lucene’s new LatLonPoint, which doubles geo-point query performance."

The fact that these are numbers against ES 2.x, and photon is currently at ES 1.7, lets assume that we would really have a huge benefit, maybe factor 20, from this, as reverse lookup is sadly not really fast in photon currently.

**Comment by karussell** [comment]
There is an outstanding pull request that needs a bit work to update to 2.x, maybe you can further test and polish this or even use this to do a bigger upgrade to 5.x?

**Comment by reuschling** [comment]
hm ok, maybe I can arrange it to find the time - what is left on this pull request?

**Comment by karussell** [comment]
See my comments in it #217 and also see #219

**Comment by reuschling** [comment]
I now made an according pull request #254. Further discussions better there.
