### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by sivajyothisandiri** [komoot/photon#252]
Hi Team,

I am trying to use Photon for Geoservices and followed the instructions given in photon/README.md, however, I am just wondering how can I use the service just by having one jar file and a tar extraction? I could not understand how executing this command java -jar photon-0.2.7.jar will actually give an api service at http://localhost:2322. Will this (http://localhost:2322) actually work if I extract the tar in another system, if no, please show some light on correct installation process for this situation. Awaiting your response. Thanks.

**Comment by karussell** [comment]
Questions should go to the mailing list
