### ISSUE TITLE
Problem with area=yes or highway=pedestrian?

### ISSUE THREAD

**Issue by karussell** [komoot/photon#253]
When I search for http://photon.komoot.de/api?q=Recklinghausen%20markt&osm_tag=highway&lang=de I do not get anything relevant. But for one specific amenity [a result is returned](http://photon.komoot.de/api?q=Recklinghausen%20Markt%2011%20Orthop%C3%A4dicum), the street name is missing here.

Now the most confusing thing is when I leave out the word 'Orthopädicum' I [do no longer](http://photon.komoot.de/api?q=Recklinghausen%20Markt%2011) get this result.

**Comment by lonvia** [comment]
The [pedestrian way](http://www.openstreetmap.org/way/31509724) in question does not have a name. Adding only addr:street to a POI is not sufficient as Nominatim takes the name from the attached highway object. You can see that quite well in the [details for the Orthopädicum](http://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=4703375785) in Nominatim. The street is listed as 'No Name' there.

**Comment by karussell** [comment]
Ah, thanks - makes sense. Why is "addr:street" not taken if no highway name is present? Or is this just the contract that the POIs are only connected to each other if the street name is identical?

**Comment by lonvia** [comment]
The information was not really retained until recently. Nominatim now saves the information (see https://github.com/openstreetmap/Nominatim/pull/700), so photon could now in theory use the addr:* tags where available.

**Comment by lonvia** [comment]
This was implemented with #303.
