### ISSUE TITLE
Updates are not commited to the nominatim database when accessing /nominatim-update 

### ISSUE THREAD

**Issue by amirmasud** [komoot/photon#257]
when accessing /nominatim-update it returns 

> nominatim update started (more information in console output) ...

In the  NominatimUpdater.java we have:
`template.update("update placex set indexed_status = 0 where place_id = ?", place.getPlaceId());`
but nothing is committed to the nominatim database even after everything is finished.

(Meanwhile as I logged, the return value of template.update was correctly show the number of rows that should be affected [ = 1])

as `dataSource.setDefaultAutoCommit(false);` I searched about commit() function call in the whole source code but nothing was found.

I manually added
 `template.getDataSource().getConnection().commit();` 
after `updater.finish();` line in update function but it didn't affect the database.
(what is the problem ?)

All in all, Which code line commits these changes to the nominatim database? 
and if it's forgotten and it's a bug how can we commit them? as the aforementioned statement doesn't work.

**Comment by lonvia** [comment]
No longer relevant.
