### ISSUE TITLE
importer NOMINATIM fails when trying to import

### ISSUE THREAD

**Issue by HeadhunterXamd** [komoot/photon#260]
I am trying to import the nominatim database but it crashes when trying:

`[main] INFO de.komoot.photon.App - starting import from nominatim to photon with languages: en
[main] INFO de.komoot.photon.nominatim.NominatimConnector - start importing documents from nominatim ...
Oct 19, 2017 7:27:08 AM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
Oct 19, 2017 7:27:08 AM org.springframework.jdbc.support.SQLErrorCodesFactory <init>
INFO: SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase]
[main] INFO de.komoot.photon.App - error importing from nominatim: StatementCallback; bad SQL grammar [SELECT place_id, osm_type, osm_id, class, type, name, housenumber, postcode, extratags, ST_Envelope(geometry) AS bbox, parent_place_id, linked_place_id, rank_search, importance, calculated_country_code, centroid FROM placex WHERE linked_place_id IS NULL AND centroid IS NOT NULL ORDER BY geometry_sector; ]; nested exception is org.postgresql.util.PSQLException: ERROR: column "calculated_country_code" does not exist`

**Comment by lonvia** [comment]
Make sure you use the latest photon version. The database schema of Nominatim has changed recently and you seem to be using a neweser version of Nominatim.

**Comment by mumins** [comment]
I have the same issue.
Nominatim is installed following http://www.nominatim.org/release-docs/latest/Install-on-Ubuntu-16
Database populated following http://www.nominatim.org/release-docs/latest/Import-and-Update
Nominatim V 3.0.1.
Photon V 0.2.7

postgres@geocode:~$ psql -d nominatim
nominatim=# SELECT place_id, osm_type, osm_id, class, type, name, housenumber, postcode, extratags, ST_Envelope(geometry) AS bbox, parent_place_id, linked_place_id, rank_search, importance, calculated_country_code, centroid FROM placex WHERE linked_place_id IS NULL AND centroid IS NOT NULL ORDER BY geometry_sector;
ERROR:  column "calculated_country_code" does not exist
LINE 1: ...ace_id, linked_place_id, rank_search, importance, calculated...

**Comment by RhinoDevel** [comment]
Which Nominatim + Photon combinations are correct?

Nominatim v3.0.1 + https://github.com/komoot/photon/commit/ccab8efef4f23281f136eefb4c0618d7565595c5

Nominatim v2.5.1 + http://photon.komoot.de/data/photon-0.2.7.jar

?
