### ISSUE TITLE
Photon infrastructure setup - Too much latency. 

### ISSUE THREAD

**Issue by mgshutter** [komoot/photon#261]
Hello,

I am not sure if this is the correct place to ask this question. However, I could not understand where else to ask so using this forum. Please let me know if I could ask it some where else, if this is not the place. 

We have setup a photon infrastructure on a server that has quad core CPU, 16GB RAM, 2 TB 7200 RPM HDD and we are trying to access it over web by using a customized open port on the server. We are seeing too much latency where the auto-complete just waits for a long time and does not show any results for at least upto 10 seconds in most cases. 

I tried understanding if the results could be cached in memory for faster response, but was unable to understand if that could be done. I tried understanding how photon can be tuned further for faster response, but could not understand. 

Could you please tell what is the best way for our current hardware setup to make photon more responsive. Should we use say a 128GB SSD for faster IOPS because photos index is 57GB?

Any guidance for tuning for lower latency and faster response for auto-complete will be greatly appreciated. 

thank you
Mrunal

**Comment by karussell** [comment]
Please see #258

**Comment by mgshutter** [comment]
Thank you very much. I am using now this command about which I have some questions. 
java -Xms7G -Xmx7G -jar photon-0.2.7.jar -listen-port 20131

In the above, is 7GB and 7GB exclusive for each cache or is shared. That is will the above reserve 14GB of memory in my 16GB memory or 7GB memory that is shared. 

Making this configuration above has improved the response time extremely so its working nicely. I am still seeing some response time latency in the initial cold miss characters. I believe this latency is arriving from HDD latency I believe. So will moving to SDD will help get rid of the cold miss latency? and can I use a 120 GB SDD for 57 GB of index data.

Another question is right now the auto-completion starts from 4 character onwards. So it does not work if the name of the place has only 3 characters. Is it possible to change the behavior to start autocompletion
from 1st character itself? Is there a configuration option to set that?

In any case the above caching parameter has improved the performance quite a lot, so we deeply appreciate your quick help. 

thanks
Mrunal

**Comment by mgshutter** [comment]
Also we are noticing that when we use the autocomplete search box on here https://photon.komoot.de/  we are able to find the addresses that we are searching for in autocomplete in correct order, but in our own search boxes, we do not get the autocomplete to show the same sequence of addresses as we start typing them. That is what we see in our search boxes in autocomplete is different than what we see in the URL above search, and our search box addresses are far away from the URL above in terms of their accuracy. For e.g. street name search etc. 

How to ensure we can get similar addresses as the URL above?

**Comment by karussell** [comment]
Please ask on our mailing list for more questions
