### ISSUE TITLE
photon doesnt start / java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by martinmakesitwork** [komoot/photon#269]
![exeptionerr](https://user-images.githubusercontent.com/19605697/32996322-66e1224e-cd81-11e7-9c9e-dcc8c1300423.PNG)

Im not able to start photon. Any ideas how to handle this err?

**Comment by hbruch** [comment]
What JDK version are you using? If JDK9, please try with JDK8.

**Comment by martinmakesitwork** [comment]
Thanks for the superfast reply! It works. 

Anyhow it is working superslow.
If start a get request (like this: http://localhost:2322/api?q=berlin&limit=2) it takes about 10 seconds to get a response. 

Is there something wrong?

![123](https://user-images.githubusercontent.com/19605697/33012409-12f5c030-cde1-11e7-9ea1-f1fe11be4761.PNG)

When i try to make such a request: http://localhost:2322/api?q=berlin&lon=10&lat=52 . It takes somthing like forever.

**Comment by karussell** [comment]
See https://github.com/komoot/photon/issues/209 and #258. For questions please use our mailing list.
