### ISSUE TITLE
Use common white spaces across the project

### ISSUE THREAD

**Issue by karussell** [komoot/photon#278]
I'm against tabs (for no reason ;) !), so I would like to use 4 spaces and apply also the same code formatting to all source files. Currently we have a wild mix it seems.

Using the standard java rules stored in IntelliJ, see [this discussion](https://github.com/graphhopper/graphhopper/issues/770#issuecomment-246490515)

**Comment by lonvia** [comment]
I'm all for cleaning up the coding style. The basic rules in https://github.com/graphhopper/graphhopper/issues/770#issuecomment-246490515 sound sensible. I usually prefer spaces as well.

I don't use any IDE at the moment but when I do, it is Eclipse. So naturally I would prefer a style file for it but I'm happy to configure the formatter manually as well. It looks like all the points you mention are configurable.

**Comment by karussell** [comment]
Ok. Also in the linked thread there is a style settings zip for Eclipse
