### ISSUE TITLE
Use distance_sort=false for backward compatibility

### ISSUE THREAD

**Issue by karussell** [komoot/photon#294]
As written in https://github.com/komoot/photon/pull/254/commits/c321b06a594fcebfe9573c406457280664311e5c we should use the former behaviour as default: distance_sort=false

And the exception message for distance_sort parsing in ReverseRequestFactory is wrong and the exception in PhotonRequestFactory should get the same exception if not false or true e.g.

```java
Boolean locationDistanceSort;
try {
  locationDistanceSort = Boolean.valueOf(webRequest.queryParamOrDefault("distance_sort", "false"));
} catch (Exception nfe) {
  throw new BadRequestException(400, "invalid parameter 'distance_sort', can only be true or false");
}
```

**Comment by lonvia** [comment]
Having played a bit around with the distance-sort-enabled komoot instance, I'm tempted to suggest to completely roll back this feature for now. I could get very few useful results as soon as lat/lon is added.

We obviously also need some tests for queries like '?q=berlin&lat=52.3879&lon=-13.0582'

**Comment by karussell** [comment]
> I'm tempted to suggest to completely roll back this feature for now.

It is not a new feature. IMO it is essential for the location bias but the location bias is too strict with distance_sort=true (see #296 for a potential fix) and kind of nonexistent with distance_sort=false. Can you confirm this? So even if we change the default we still have a problem of an inactive location bias when it is expected.

**Comment by yohanboniface** [comment]
> Having played a bit around with the distance-sort-enabled komoot instance, I'm tempted to suggest to completely roll back this feature for now. I could get very few useful results as soon as lat/lon is added.

I can confirm this, for example if I go to http://photon.komoot.de/ and search "Paris", I'm expecting the city Paris to be first (or at least in the visible results if some relevant result is found very close to the passed lat/lon)

> It is not a new feature. IMO it is essential for the location bias but the location bias is too strict with distance_sort=true (see #296 for a potential fix) and kind of nonexistent with distance_sort=false. 

IMHO the location bias is where all the magic should happen, that is: weighting between different values (string similarity, distance, importance…). So IMHO the sorting by distance when location bias is active will only make troubles.

Is `distance_sort=false` as default now deployed on the Komoot servers?

**Comment by karussell** [comment]
> Is distance_sort=false as default now deployed on the Komoot servers?

Probably not as this was only recently merged. We have no access to their servers.

> So IMHO the sorting by distance when location bias is active will only make troubles.

We do not sort :) .. the parameter name is misleading. We'll likely remove it and replace with a zoom level or some kind of a distance/radius within the results should be preferred a bit.

**Comment by karussell** [comment]
I have to correct myself: for the reverse geocoding we do sort by distance, so the name is only misleading for forward geocoding

**Comment by hbruch** [comment]
Isn't [replacing](https://github.com/komoot/photon/blob/master/src/main/java/de/komoot/photon/query/PhotonQueryBuilder.java#L141)  the query score by the function score in forward geocoding equivalent to a sort by distance only?

**Comment by karussell** [comment]
Oh, yes. You are right.
