### ISSUE TITLE
Worse reverse geocoding

### ISSUE THREAD

**Issue by karussell** [komoot/photon#295]
The changes in #254 seem to lead to worse reverse geocoding in some cases or is this a data issue? 

E.g.

 1. http://photon.komoot.de/reverse?lat=38.337025&lon=-115.043747
 2. http://photon.komoot.de/reverse?lat=45.78205&lon=-108.07531

return an empty response (regardless of distance_sort=false|true), where the old version returned:

 1. [a landuse](https://www.openstreetmap.org/node/357553972) roughly 2.4km away and [a mountain](https://www.openstreetmap.org/node/357551139) roughly 4km away
 2. [a motorway](https://www.openstreetmap.org/way/38106235) roughly 0.5km away (multiple way segments) and as 4. hit we get [this motorway junction](https://www.openstreetmap.org/node/447858552) roughly 4-5km away

Many other request seem to be okay, e.g.

http://photon.komoot.de/reverse?lat=51.435096&lon=14.244375

**Comment by karussell** [comment]
Ah, maybe this is also related to #296?

**Comment by karussell** [comment]
The data is in the storage, e.g. http://photon.komoot.de/api?q=Gap%20Mountain finds the node 357551139 for the "gap mountain" as 7th hit

**Comment by hbruch** [comment]
#254 made limit and radius configurable. (Default) search radius was [5km before #254](https://github.com/komoot/photon/pull/254/commits/fcba44c8762245c32533fb25314ec2e324333471#diff-6ae0a2110b516a025e3d3146947fc3bdL108) and [changed to 1km](https://github.com/komoot/photon/pull/254/commits/fcba44c8762245c32533fb25314ec2e324333471#diff-d01600990743bfdfdbf4a9ba156cd93eR36).

With adding radius=5 both requests return results:
1) http://photon.komoot.de/reverse?lat=45.78205&lon=-108.07531&radius=5
2) http://photon.komoot.de/reverse?lat=45.78205&lon=-108.07531&radius=5
  
I wonder, if the introduced upper bounds of reverse geocoding radius and limit shouldn't be much lower (e.g. [max radius currently is 5000km](https://github.com/komoot/photon/pull/254/files#diff-d01600990743bfdfdbf4a9ba156cd93eR68) and [max result limit is 5000](https://github.com/komoot/photon/pull/254/files#diff-6ae0a2110b516a025e3d3146947fc3bdR39).

**Comment by karussell** [comment]
Thanks, much better! But still not 100% comparable IMO as just 1 hit and shouldn't there be at least 2 in both cases?

**Comment by hbruch** [comment]
Specifying the limit returns 2 results in both cases:

1. http://photon.komoot.de/reverse?lat=38.337025&lon=-115.043747&radius=5&limit=2
2. http://photon.komoot.de/reverse?lat=45.78205&lon=-108.07531&radius=5&limit=2

To me it looks if the limit was 1 ([hard coded](https://github.com/komoot/photon/pull/254/commits/fcba44c8762245c32533fb25314ec2e324333471#diff-6722547327f9fac2f974572c927c296aL25)) before #254 as well, so it shouldn't have returned 2 results, no?

For me, the current defaults are ok. Would you switch back to 5km radius? What's the use case of having a higher radius? Searching for POIs on a zoomed out map?

**Comment by karussell** [comment]
Ah, cool & thanks!

> Would you switch back to 5km radius?

No. I just wanted to understand this :)

**Comment by karussell** [comment]
We also need this radius for forward geocoding ... or probably reverse and forward are not that different and should just use a different location handling (reverse<=>sort vs. forward<=>boost)

**Comment by hbruch** [comment]
I think the radius in reverse geocoding should be a hard limit. 

If used interactivly in maps, radius and filtered tags depend on use case and probably depend on zoom level. E.g. on city level, a user could want to have addresses returned, on region level settlements, and so on. Nominatim has a zoomlevel param and filters on different object types. However, as photon stores point coordinates only and no ways/polygons, reverse geocoding on lower zoomlevels is limited. 

For forward geocoding, what should be the effect of the radius? Hard limit, as in #268? Then I'd prefer a bounding box for clipping to a radius. For boosting, I suggest a zoom dependent radius. Results closer than radius receive max boost, those farer away a decaying boost (see #296).

**Comment by karussell** [comment]
I more meant the current huge complexity and abstraction IMO around forward and reverse geocoding. Where we at the end just convert URL parameters into an ES request. 

But probably we should move this discussion to the mailing list :)
