### ISSUE TITLE
Move from standalone application to ES plugin

### ISSUE THREAD

**Issue by karussell** [komoot/photon#299]
Should we convert this standalone application into an ES plugin to avoid a separate JVM and simplify deployment again? (after embedded is no longer really supported since ES 5).

idea from @reuschling

**Comment by hbruch** [comment]
Wouldn't this publish the complete ES? Currently, it is not secured in any way.

**Comment by karussell** [comment]
Valid point. In general it is recommended to use https in front of ES, so one could try a nginx proxy in front of it or e.g. https://github.com/floragunncom/search-guard-ssl

**Comment by hbruch** [comment]
I'm not only thinking about ssl, but making photon's internals publicly accessible. Would you try to block all ES requests? Admin calls, ill-shaped queries, data manipulation...

So securing such an instance would rather require adding authorization and authentication, as provided by e.g. https://github.com/floragunncom/search-guard.

Or a reverse proxy would be mandatory to block all non-Photon requests?

Not sure, if this would really simplify deployment.

**Comment by reuschling** [comment]
hmm - first, there is a security layer for ES, but only available in x-pack.
Currently we have two different cases:
1. Embedded mode: Here, the whole ES is running in the same VM as the photon part, same IP, different port. Hiding the ES APIs means to not open the according port on this machine to public. Opening just photon would be something like 127.0.0.1:9301/* in your firewall/proxy, e.g. nginx
2. Standalone mode: Photon is running separately from the ES server, different VMs, potentially different IPs with different ports. Hiding the ES APIs can be done by hiding the whole machine or, in the case the machine is the same, by hiding the ES port, as in the embedded mode.

ES plugin case: Same VM, same ports, but still different api endpoints. To hide the ES APIs, just open the specific API URL prefix from the photon calls to public, e.g. 127.0.0.1:9300/esXY/photon/*. This is common use case, we do so, also with nginx.
You have the same situation if you offer an ES instance for searching to the public. You only want to be the searching APIs visible of course.

**Comment by karussell** [comment]
:+1: 

> hmm - first, there is a security layer for ES, but only available in x-pack.

Does not make sense for us as an open source project, so an nginx config or the searchguard should be our promoted candidates.

**Comment by hbruch** [comment]
> ES plugin case: Same VM, same ports, but still different api endpoints. To hide the ES APIs, just open the specific API URL prefix from the photon calls to public, e.g. 127.0.0.1:9300/esXY/photon/*. This is common use case, we do so, also with nginx.

Ok, valid point.

**Comment by lonvia** [comment]
Whatever the future of Photon with regard to upgrading from ES5.5, I don't think an ES plugin is really on the table. So closing as not planned.
