### ISSUE TITLE
Many address features are missing?

### ISSUE THREAD

**Issue by tommedema** [komoot/photon#30]
Address geocoding on a worldwide level is complicated for many reasons, of which one is that every single country lists addresses in different ways. For example, in some countries provinces and states are important (Netherlands), whereas in others districts and sub-districts are more important (Thailand).

When I query your API for a road in Bangkok, Thailand, like so:

    http://photon.komoot.de/api/?q=sukhumvit

I get the following:

		{
		  "features": [
		    {
		      "properties": {
		        "name": "Sukhumvit",
		        "osm_value": "neighbourhood",
		        "country": "Thailand",
		        "osm_id": 2203974487,
		        "osm_key": "place",
		        "postcode": "10110"
		      },
		      "geometry": {
		        "coordinates": [
		          100.565073,
		          13.73384
		        ],
		        "type": "Point"
		      },
		      "type": "Feature"
		    },
		    {
		      "properties": {
		        "country": "Thailand",
		        "name": "Sukhumvit Road",
		        "osm_value": "tertiary",
		        "street": "Sukhumvit Road",
		        "osm_id": 232865089,
		        "osm_key": "highway"
		      },
		      "geometry": {
		        "coordinates": [
		          102.45796,
		          12.18993
		        ],
		        "type": "Point"
		      },
		      "type": "Feature"
		    },
		    ... ETC ...
		  ],
		  "type": "FeatureCollection"
		}

The first entry is the one I need, but the problem is that there is a lot more data in the OSM database about this entry than your API shows. For example, it should return the following entries when available, just like Nominatim does:

    - (Object) administrative
    - (Object) attraction
    - (Object) city
    - (Object) city_district
    - (Object) clothes
    - (Object) commercial
    - (Object) country
    - (Object) country_code
    - (Object) county
    - (Object) house_number
    - (Object) pedestrian
    - (Object) place
    - (Object) postcode
    - (Object) road
    - (Object) state
    - (Object) state_district
    - (Object) suburb
    - (Object) town
    - (Object) village

In the case of my query we already know this data: `postcode = 10110` (given), `country = thailand` (given), `district = Watthana District` (not given, but should be), `sub-district = Sukhumvit` (not given, but should be), `city = Bangkok`, `province = Bangkok Metropolitan Area` (not given, but should be), etc.

Can I make this change myself to  let photon return all known data that is relevant to the query? If I would have queried a US street I want to know all data that is available too, so in that case it should return the state, among other fields.

I hope I expressed my request clearly, if not, please tell me. ;)

**Comment by christophlingg** [comment]
now, we are also returning state information
