### ISSUE TITLE
Addresses in Mannheim's city centre have neither street nor place attribute

### ISSUE THREAD

**Issue by hbruch** [komoot/photon#302]
Photon returns seemingly correct matches for addresses in the city centre of Mannheim, Germany, which are addressed via the name of their place ("Quadrat"/square) instead of street.

E.g. http://photon.komoot.de/api?q=Mannheim,%20D3%204 returns the correct address, but has neither street nor place attribute.

In OSM, most of these osm buildings have a addr:street and addr:place attribute, as e.g. for [Mannheim, D3 4](https://www.openstreetmap.org/way/181662687).

As the address is found, I assume nominatim provides this information and photon should explicitly add it as source field.

Relates to #147

**Comment by hbruch** [comment]
Nominatim seems to store addr:* tags in the placex.address hstore column, which is currently not queried by Photon‘s NominatimConnector (I guess, placex.address did not exist back then(?)).

I think after collecting the address information from parent places, placex.address information should at least overwrite the street name.

Probably the addr:place attribute should be added as PhotonDoc.place as well.

**Comment by lonvia** [comment]
The addresses in Mannheim are actually tagged wrongly. They normally should not have a addr:street tag at all but only a addr:place tag. So #302 is not really a good fix for your particular issue.

Street-less addresses exist in various forms all [over the world](https://taginfo.openstreetmap.org/keys/addr%3Aplace#map). The house number may then refer to a city block (as in Mannheim), a suburb, [a hamlet](https://www.openstreetmap.org/way/512983854), an estate or an [entire village](https://www.openstreetmap.org/way/230608838). There are also a ton of cases where addr:place is used [wrongly](https://www.openstreetmap.org/way/388111697), so when there is a addr:street tag, it is better to ignore it entirely or assume it is meant to be addr:suburb or addr:city.

**Comment by hbruch** [comment]
I see. So you recommend to completly ignore addr:street? Or just not to rely on it for the Mannheim case?

Would you suggest to better assess addr:place? Or better the place:neighbourhood? Should this then become a new field neighbourhood or place? Not sure what would be the best fix then.

**Comment by lonvia** [comment]
I meant to say that Photon needs a generic solution for street-less addresses which should also cover the Mannheim case. I'm not sure how the API should return such a place either. Just copying the value of addr:place into the street field feels a bit hacky. It would still work for the Mannheim case but not for others. So that means adding a different field. I would not recommend calling it 'place' as this turned out to be very confusing. 'neighbourhood' or 'suburb' would fit for some cases but also be confusing for others.
