### ISSUE TITLE
country code invalid while importing data

### ISSUE THREAD

**Issue by Karmadon** [komoot/photon#305]
Version: `0.29`
Command `java -jar photon-*.jar -nominatim-import -host localhost -port 5432 -database nominatim -user nominatim -password nominatim`
```
Error: Exception in thread "main" java.lang.IllegalArgumentException: country code invalid 
        at de.komoot.photon.nominatim.NominatimConnector.readEntireDatabase(NominatimConnector.java:324)
        at de.komoot.photon.App.startNominatimImport(App.java:124)
        at de.komoot.photon.App.main(App.java:59)
```

**Comment by Karmadon** [comment]
resolved with added `-country-codes ua ` for Ukraine 
Closed

**Comment by karussell** [comment]
Without the country code parameter it did not work?

**Comment by Karmadon** [comment]
Yes.

**Comment by karussell** [comment]
Thanks for reporting! This is a bug - see #307 for the fix that will be merged soonish.
