### ISSUE TITLE
I'm trying to find Moscow, for example

### ISSUE THREAD

**Issue by sshikov** [komoot/photon#309]
http://photon.komoot.de/api/?q=moscow&osm_tag=place:city&lang=en

anything with state: Moscow Oblast shouldn't be here at all.

{"features":[
{"geometry":{"coordinates":[37.6176606,55.7507178],"type":"Point"},"type":"Feature","properties":{"osm_id":2555133,"osm_type":"R","extent":[37.290502,55.9574097,37.9674277,55.4913076],"country":"Russia","osm_key":"place","osm_value":"city","name":"Moscow","state":"Moscow"}}
,{"geometry":{"coordinates":[-117.0001651,46.7323875],"type":"Point"},"type":"Feature","properties":{"osm_id":121430,"osm_type":"R","extent":[-117.0395336,46.758882,-116.962068,46.710912],"country":"United States of America","osm_key":"place","osm_value":"city","name":"Moscow","state":"Idaho"}}
,{"geometry":{"coordinates":[-89.4039612,35.0619984],"type":"Point"},"type":"Feature","properties":{"osm_id":197198,"osm_type":"R","extent":[-89.411041,35.066173,-89.371835,35.05075],"country":"United States of America","osm_key":"place","osm_value":"city","name":"Moscow","state":"Tennessee"}}
,{"geometry":{"coordinates":[-90.9181916,38.9478267],"type":"Point"},"type":"Feature","properties":{"osm_id":140611,"osm_type":"R","extent":[-90.943528,38.965236,-90.901428,38.9108554],"country":"United States of America","osm_key":"place","osm_value":"city","name":"Moscow Mills","state":"Missouri"}}
,{"geometry":{"coordinates":[-101.2057164,37.3236349],"type":"Point"},"type":"Feature","properties":{"osm_id":129775,"osm_type":"R","extent":[-101.2126096,37.329613,-101.203097,37.3221469],"country":"United States of America","osm_key":"place","osm_value":"city","postcode":"67952","name":"Moscow","state":"Kansas"}}
,{"geometry":{"coordinates":[37.4195533,54.9155247],"type":"Point"},"type":"Feature","properties":{"osm_id":37294205,"osm_type":"W","extent":[37.3493408,54.9530337,37.4697052,54.8921607],"country":"Russia","osm_key":"place","osm_value":"city","name":"Serpukhov","state":"Moscow Oblast"}}
,{"geometry":{"coordinates":[37.2727963,55.6711507],"type":"Point"},"type":"Feature","properties":{"osm_id":181346,"osm_type":"R","extent":[36.3829921,55.8335177,37.417481,55.4814771],"country":"Russia","osm_key":"place","osm_value":"city","name":"Odintsovo","state":"Moscow Oblast"}},{"geometry":{"coordinates":[38.7670121,55.0938743],"type":"Point"},"type":"Feature","properties":{"osm_id":1703080,"osm_type":"R","extent":[38.6914899,55.132053,38.9049259,55.0334451],"country":"Russia","osm_key":"place","osm_value":"city","name":"Kolomna","state":"Moscow Oblast"}},{"geometry":{"coordinates":[37.5453056,55.4308841],"type":"Point"},"type":"Feature","properties":{"osm_id":1697322,"osm_type":"R","extent":[37.4710057,55.4876619,37.6087053,55.2979647],"country":"Russia","osm_key":"place","osm_value":"city","postcode":"142100","name":"Podolsk","state":"Moscow Oblast"}},{"geometry":{"coordinates":[37.7339358,55.9094928],"type":"Point"},"type":"Feature","properties":{"osm_id":376977,"osm_type":"R","extent":[37.6851245,55.9851894,37.8131885,55.8786424],"country":"Russia","osm_key":"place","osm_value":"city","name":"Mytishchi","state":"Moscow Oblast"}},{"geometry":{"coordinates":[37.4449896,55.8892847],"type":"Point"},"type":"Feature","properties":{"osm_id":181326,"osm_type":"R","extent":[37.2290074,55.9932204,37.5072164,55.8742007],"country":"Russia","osm_key":"place","osm_value":"city","name":"Khimki","state":"Moscow Oblast"}},{"geometry":{"coordinates":[37.9646488,55.8036225],"type":"Point"},"type":"Feature","properties":{"osm_id":3171497,"osm_type":"R","extent":[37.8227949,55.8619646,38.1447747,55.7104856],"country":"Russia","osm_key":"place","osm_value":"city","name":"Balashikha","state":"Moscow Oblast"}},{"geometry":{"coordinates":[38.4411898,55.8553511],"type":"Point"},"type":"Feature","properties":{"osm_id":37202846,"osm_type":"W","extent":[38.3806854,55.9121954,38.517154,55.8251319],"country":"Russia","osm_key":"place","osm_value":"city","name":"Noginsk","state":"Moscow Oblast"}},{"geometry":{"coordinates":[38.9790038,55.8083278],"type":"Point"},"type":"Feature","properties":{"osm_id":1462341,"osm_type":"R","extent":[38.9163868,55.8501853,39.0574981,55.7800897],"country":"Russia","osm_key":"place","osm_value":"city","postcode":"142600","name":"Orekhovo-Zuyevo","state":"Moscow Oblast"}},{"geometry":{"coordinates":[37.2727963,55.6711507],"type":"Point"},"type":"Feature","properties":{"osm_id":1667827,"osm_type":"R","extent":[37.2186192,55.7080548,37.3490287,55.6483399],"country":"Russia","osm_key":"place","city":"Odintsovo","osm_value":"city","postcode":"143000","name":"Odintsovo","state":"Moscow Oblast"}}],"type":"FeatureCollection"}

**Comment by yohanboniface** [comment]
Relates to #294 AFAIK.

**Comment by hbruch** [comment]
Don‘t think so, there is no location bias in this query. Too me, the results look ok: Moscow, Russia is found and returned as first match, other cities with lesser importance follow.
Cities in state Moscow Oblast match because Photon does a full text search... 

I understand that the results for cities in Moscow Oblast are not intuitive, as only matches with name=Moscow where intended.

**Comment by sshikov** [comment]
>I understand that the results for cities in Moscow Oblast are not intuitive, as only matches with name=Moscow where intended.
Exactly. Probable parameters should exists to filter such false positives.

**Comment by lonvia** [comment]
Some kind of post-filtering results to throw away other results when the name matches exactly might help.

**Comment by numair** [comment]
@hbruch @lonvia Somewhat related to this are test queries I've run on Alta and Bergen. These are both cities in Norway, but searching for them doesn't return the cities as options anywhere near the top of the result list. Nominatim, however, gets it right out-of-the-box. How can I fix things so it works correctly within Photon? Thanks!

**Comment by numair** [comment]
Also worth noting is that "alta norway" actually gives worse results than "alta no." Not sure how or why that happens. If you have any ideas, please let me know. I've just set up a self-hosted version to see if that has fixes to these problems, but would appreciate any pointers if there's a way to make things work that I might have overlooked in the docs.

**Comment by numair** [comment]
Oops, sorry -- I realized I was filtering out municipalities, which is what those were considered to be as an osm_tag. My fault. Thanks for creating a great project!

**Comment by numair** [comment]
Actually, sorry, it still seems to be impossible to find places such as Å, a town in Norway whose name is one letter. Searching using Nominatim and Google autocomplete for "å norway" pulls up the right result.. Not so much with Photon. Again, I'll try to debug on my own, but it'd be great if you could look into it!

**Comment by lonvia** [comment]
Fixed in #580. Something of the name must now forcibly appear in the query.
