### ISSUE TITLE
What's the total size of the data after extraction?

### ISSUE THREAD

**Issue by el7r** [komoot/photon#320]
Hello,

I'm trying to setup Photon on a VPS with 80GB SSD, I'm using the command mentioned in the readme, so the files are being extracted as they're being downloaded. However, extraction always stops somewhere in the middle due to there not being enough space left.

What's the size of photon-db-latest.tar.bz2 after extraction, and how much RAM and processing power is required to run Photon?

Thanks,
Ali

**Comment by karussell** [comment]
You probably need at least 120GB SSD at the moment. 80 is definitely too small. For RAM it will work with 8GB but more is much better. Please ask further questions on our forum.

**Comment by yohanboniface** [comment]
> Please ask further questions on our forum.

I didn't know (or forgot? :p) there is a photon forum, do you have a link? :)

**Comment by karussell** [comment]
See contact: https://github.com/komoot/photon#contact

**Comment by karussell** [comment]
Ok, changed it to be more prominent in the Readme: https://github.com/komoot/photon/blob/master/README.md#contribution
