### ISSUE TITLE
Search results are very different for different languages

### ISSUE THREAD

**Issue by autumnus** [komoot/photon#322]
It may sometimes make sense to make the result language-dependent.
But how do I get similar results if the spelling in different languages differs on just one letter?

The two results for

[http://photon.komoot.de/api/?q=kyoto&lang=en](http://photon.komoot.de/api/?q=kyoto&lang=en)
and
[http://photon.komoot.de/api/?q=kyoto&lang=de](http://photon.komoot.de/api/?q=kyoto&lang=de)

are significantly different.

The desired result in the first request is on position 2.
It is not in the result of the second request.

For German I get the desired result with the request

[http://photon.komoot.de/api/?q=ky%C5%8Dto&lang=de](http://photon.komoot.de/api/?q=ky%C5%8Dto&lang=de)

But nobody would search for that!

With the same spelling I do not get the desired result for English.

[http://photon.komoot.de/api/?q=ky%C5%8Dto&lang=en](http://photon.komoot.de/api/?q=ky%C5%8Dto&lang=en)

Is there a possibility to optimise the requests?

Best regards,
Autumnus

Probably related issue: [#171](171)

**Comment by tilmanb** [comment]
Probably related https://github.com/komoot/photon/issues/326 , regarding diacritics

**Comment by lonvia** [comment]
Fixed in #330.
