### ISSUE TITLE
photon installation stuck 

### ISSUE THREAD

**Issue by jicrbuh** [komoot/photon#323]
![image](https://user-images.githubusercontent.com/16512770/38805678-6078f5ae-417f-11e8-9b04-e810254bccbf.png)

hello,
I try to install photon.  but it seems to get stuck.
what can I do?

the output:

C:\Windows\system32>cd /d  C:\Users\ADM7_User\Downloads

C:\Users\ADM7_User\Downloads>java -jar photon-0.2.2.jar
Trying jar:file:/C:/Users/ADM7_User/Downloads/photon-0.2.2.jar!/elasticsearch-wordending-tokenfilter-0.0.1.zip...
Downloading .DONE
Installed ybon/elasticsearch-wordending-tokenfilter/0.0.1 into C:\Users\ADM7_User\Downloads\photon_data\elasticsearch\plugins\wordending-tokenfilter
Trying https://github.com/mobz/elasticsearch-head/archive/master.zip...
Downloading ............................................................................................................................................................................................
........................................................................................................................................................................................................
........................................................................................................................................................................................................
.......................DONE
Installed mobz/elasticsearch-head into C:\Users\ADM7_User\Downloads\photon_data\elasticsearch\plugins\head
Trying https://github.com/polyfractal/elasticsearch-inquisitor/archive/master.zip...
Downloading ...........................................................................................................................................................DONE
Installed polyfractal/elasticsearch-inquisitor into C:\Users\ADM7_User\Downloads\photon_data\elasticsearch\plugins\inquisitor
[main] INFO org.elasticsearch.node - [Kukulcan] version[1.4.1], pid[4820], build[89d3241/2014-11-26T15:49:29Z]
[main] INFO org.elasticsearch.node - [Kukulcan] initializing ...
[main] INFO org.elasticsearch.plugins - [Kukulcan] loaded [lang-mvel, wordending], sites [head, inquisitor]
[main] INFO org.elasticsearch.script - [Kukulcan] compiling script file [C:\Users\ADM7_User\Downloads\photon_data\elasticsearch\config\scripts\general-score.mvel]
[main] INFO org.elasticsearch.script - [Kukulcan] compiling script file [C:\Users\ADM7_User\Downloads\photon_data\elasticsearch\config\scripts\location-biased-score.mvel]
[main] INFO org.elasticsearch.node - [Kukulcan] initialized
[main] INFO org.elasticsearch.node - [Kukulcan] starting ...
[main] INFO org.elasticsearch.transport - [Kukulcan] bound_address {inet[/127.0.0.1:9300]}, publish_address {inet[/127.0.0.1:9300]}
[main] INFO org.elasticsearch.discovery - [Kukulcan] photon/zxr9rKFwT6ee7I5IYmlE7g
[elasticsearch[Kukulcan][clusterService#updateTask][T#1]] INFO org.elasticsearch.cluster.service - [Kukulcan] new_master [Kukulcan][zxr9rKFwT6ee7I5IYmlE7g][WIN-47OTQHP3AV8][inet[/127.0.0.1:9300]], rea
son: zen-disco-join (elected_as_master)
[main] INFO org.elasticsearch.http - [Kukulcan] bound_address {inet[/127.0.0.1:9200]}, publish_address {inet[/127.0.0.1:9200]}
[main] INFO org.elasticsearch.node - [Kukulcan] started
[main] INFO de.komoot.photon.elasticsearch.Server - started elastic search node
== Spark has ignited ...
>> Listening on 0.0.0.0:2322
[Thread-4] INFO org.eclipse.jetty.server.Server - jetty-9.0.z-SNAPSHOT
[Thread-4] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@1647ae7{HTTP/1.1}{0.0.0.0:2322}
[elasticsearch[Kukulcan][clusterService#updateTask][T#1]] INFO org.elasticsearch.gateway - [Kukulcan] recovered [1] indices into cluster_state

Best regards,
Chen

**Comment by karussell** [comment]
What does it say if you request photon at localhost:2322? Also for questions please use [our mailing list](https://github.com/komoot/photon#contribution).

**Comment by jicrbuh** [comment]
It's resolved.
I will use the mailing list next time. 
Thank you

**Comment by karussell** [comment]
How did you resolve it?
