### ISSUE TITLE
Ignore diacritics in query

### ISSUE THREAD

**Issue by systemed** [komoot/photon#326]
Currently Photon is quite fussy about diacritics ('accents'): 

* http://photon.komoot.de/api/?q=Ile+d%27Oleron returns only a track called "Voyeu de l'Ile d'Oleron"
* http://photon.komoot.de/api/?q=%C3%8Ele+d%27Ol%C3%A9ron returns the Île d’Oléron

Usually a placename search would ignore (or downrank) diacritic differences, so that a search for "Ile d'Oleron" still returned Île d’Oléron.

**Comment by systemed** [comment]
It looks like this would be fixed by adding `asciifolding` to the filters for `index_ngram` and `search_ngram` in https://github.com/komoot/photon/blob/master/es/index_settings.json . `german_normalization` is already set which isn't that different. Happy to put a PR in for this though I don't have a dev setup so would be flying blind.

**Comment by lonvia** [comment]
Happy to set up a test instance if you do a PR (as soon as there is a free time slot etc, you know the drill).

**Comment by systemed** [comment]
Excellent - thank you. I've just pushed #330 which should do it if my understanding of Elasticsearch is correct (big if).
