### ISSUE TITLE
Basic example returns no data

### ISSUE THREAD

**Issue by abenrob** [komoot/photon#327]
I was just testing the demo, since the recent release, and the basic example you provide in the readme returns nothing. Why would that be?

`http://photon.komoot.de/api?q=berlin&osm_tag=toursim:museum`

**Comment by lonvia** [comment]
Possibly because there is a typo in the readme. Try: 

`http://photon.komoot.de/api?q=berlin&osm_tag=tourism:museum`

**Comment by lonvia** [comment]
Now also fixed in the README. Thanks for reporting.

**Comment by abenrob** [comment]
ahaha. yep! Thanks!
