### ISSUE TITLE
reverse search default parameter for distance_sort

### ISSUE THREAD

**Issue by pbrugger** [komoot/photon#328]
I updated photon from 0.2.2 to 0.3.0 and reverse geocoding does behave different now. It seems that without parameter distance_sort=true my first result is too far away. (Because distance_sort=false is default now, also for reverse search). Results are ok with distance_sort=true

Is there a way to set distance_sort=true as default for reverse search?

Otherwise I would have to change a lot endpoints in several websites and apps :-/

**Comment by birros** [comment]
I confirm this issue. Nothing dramatic but can be annoying in production.

By the way, thank you very much for this very useful free software ;-)

**Comment by hbruch** [comment]
I confirm this issue and will provide a fix.
