### ISSUE TITLE
Housenumber outbalances city in geocoder

### ISSUE THREAD

**Issue by autumnus** [komoot/photon#329]
Is there a posiblility to prevent this behaviour?

In this case the result with housenumber is 3km away from desired position

Wrong (with housenumber):
http://photon.komoot.de/api/?q=hauptstra%C3%9Fe%2024%20eibelstadt

Approximately right (without housenumber):
http://photon.komoot.de/api/?q=hauptstra%C3%9Fe%20eibelstadt

In Nominatim the behaviour is (more) correct:

With housenumber:
https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&q=hauptstra%C3%9Fe%2024%20eibelstadt

Without housenumber:
https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&q=hauptstra%C3%9Fe%20eibelstadt

Best regards

**Comment by hbruch** [comment]
This happens as currently the names of all administrative areas are stored together with the city name in one collector field 'context', which is searched for best matches. As [Hauptstr. 24 Frickenhausen](https://nominatim.openstreetmap.org/details.php?place_id=80408360) lies in 'Verwaltungsgemeinschaft Eibelstadt', this is matched. As not only street and context match, but housenumber as well, the match ranks higher. 

Preventing this would require changes to the photon indexing and probably searching logic. 

E.g. we could avoid storing such context information (in most cases invisible anyway). I'm not sure if the current behavior is often beneficial and should be retained. This change would only affect indexing process, not index structure or implementation of search.

Another option would be to index city explicitly and add a boosting query term for it. This would require changes to the index structure and the search implementation.

**Comment by lonvia** [comment]
This has been fixed with the improved address computations coming from Nominatim.
