### ISSUE TITLE
Nominatim's 'importance' not being returned in Photon's response

### ISSUE THREAD

**Issue by kurko** [komoot/photon#333]
Nominatim includes `importance` as part of its responses. We augment it internally, aggregating with other data sources.

Photon, on the other hand, doesn't include `importance`, even though it's being [imported](https://github.com/komoot/photon/blob/ad55523f901041f1519713ad1744fb8697b3da0b/src/main/java/de/komoot/photon/importer/XMLExporter.java#L67).

Would it be acceptable if we added that key in Photon's responses? Is there a particular reason why it wasn't included (or perhaps removed some time in the past)?

Thanks.

**Comment by lonvia** [comment]
Would be okay for me. @karussell, any objections?

**Comment by karussell** [comment]
Why should we include it?

**Comment by hannesaddec** [comment]
because one could filter based on importance....

**Comment by kurko** [comment]
@karussell e.g a street and an airport are returned, we want to show the airport first.

**Comment by lonvia** [comment]
This works now in debug mode, see #578. (Change not yet live at photon.kommot.io.)
