### ISSUE TITLE
Steps to install and use photon if nominatim db is already imported

### ISSUE THREAD

**Issue by anilmuvva** [komoot/photon#338]
Dears,
Could you please let me know the necessary steps to follow to install and use photon once the nominatim data is imported and also restrict to a country and language. Thanks for your help.

**Comment by karussell** [comment]
The command should be:

`java -jar photon-*.jar -nominatim-import -host localhost -port 5432 -database nominatim -user nominatim -password <your password> -languages en,de,fr,it -data-dir export-folder`

And for country filter use e.g. `-country-codes de`

**Comment by anilmuvva** [comment]
ok thanks for the info, do we need to download the search index (53GB) mentioned in the installation steps or can we skip it if nominatim db is imported?

**Comment by karussell** [comment]
The resulting data in `data-for-photon` is the only thing you need then, yes. (We provide the search index for others to make starting with photon easier)

Another possibility is to directly feed data into photon using the end point `GET /nominatim-update` but have never used it myself and not sure if this still works (it worked even with partial updates at some point, I think)
