### ISSUE TITLE
Usage with existing Nominatim Database

### ISSUE THREAD

**Issue by Yamakasi** [komoot/photon#341]
Hi guys, this project looks nice but is it possible to use it with an already ready Nominatim database ?

**Comment by lonvia** [comment]
You can create your own photon database from your Nominatim source, see the README. You can also keep it  up-to-date together with the database, see continuously_update_from_nominatim.sh. Note how ever, that photon creates its own database because it uses a complete different storage technique (elasticsearch). So you end up with a new copy of the data essentially.

**Comment by Yamakasi** [comment]
OK, thanks for letting me know, then I know what source I should use to keep things lined up, my own Nominatim. Does it take a long time to create such DB ? When I look to the Nominiatim import times it would be nice to know something about it so I can create some schema/schedule/plan for it.

**Comment by ThomasBarris** [comment]
@Yamakasi 
> Does it take a long time to create such DB ? 

With spinning HDDs and RAID 0 it takes around 2-3 weeks to import the whole world (called [Planet OSM](https://planet.openstreetmap.org/)) and you will not be able to keep the database current by applying updates. 
With a 64GB RAM server with two SSDs and RAID 0 it takes less than 3 days and updates are no issues. The installation instruction are available [>>>here<<<](https://nominatim.org/release-docs/latest/admin/Installation/)

As of now the Nominatim database for whole world has a size of 602GB.

Anyway, I would recommend to continue the discussion on the mailing list for Nominatim, which you can subscribe [>>>here<<<](https://lists.openstreetmap.org/listinfo/geocoding)

**Comment by hbruch** [comment]
Closing this discussion. For further questions, please use the Nominatim or Photon mailing lists.
