### ISSUE TITLE
How to list all streets/housenumbers?

### ISSUE THREAD

**Issue by R1im** [komoot/photon#342]
Im trying to get list of all buildings and current solution is going through all worlds coordinates and reverse geocoding every location to get building, but its painfully slow. 
Is there any other way ?

**Comment by lonvia** [comment]
How about simply downloading the source data used by photon at https://planet.openstreetmap.org/ ? You'll have all data available locally in one go and can process it in any form you like. And in contrast to photon it contains all the buildings available in OpenStreetMap.
