### ISSUE TITLE
nominatim-update should be protected against multiple invocation

### ISSUE THREAD

**Issue by woodpeck** [komoot/photon#345]
An external process that feeds updates into a local Nominatim database and calls Photon's "nominatim-update" function afterwards has no way of finding out whether previous indexing runs have already completed. On a system with minutely updates followed by a call to nominatim-update, you can easily end up with dozens of updater threads clogging the database.

It would be good if Photon would, upon receiving a "nominatim-update" request with an update thread already running, either reject the new request, or message the running thread to restart, instead of creating a new thread.

**Comment by lonvia** [comment]
What makes this issue a bit more difficult: you shouldn't even be starting a new round of Nominatim imports before the photon update isn't finished. So, either the curl call to nominatim-update must only return when the update is actually done or we need a call where you can request the status.

A poor man's version of the latter you can also do by looking for rows with indexed_status > 0 in the placex table. If there are none, then the update is finished. For example, try the query `select true from placex where indexed_status != 0 limit 1;`. If you get no rows back, then photon is done.

**Comment by lonvia** [comment]
Fixed in #382. photon refuses to start another update round while an old one is still running.
