### ISSUE TITLE
Run Photon on Windows

### ISSUE THREAD

**Issue by frankvandenbergh** [komoot/photon#347]
I just found this project. Love the reverse geocoding. But I want to geocode a couple of thousand positions weekly. The public website states "extensive usage will be throttled". I guess this will be called extensive.

I want to use it in a Windows Visual Studio C# project. I read some issues regarding installing Photon on a windows machine. But it isn't documented (yet). Is there someone willing to share his/hers steps to install photon on windows?

**Comment by alex9099** [comment]
The project is java, you might get luck with eclipse or netbeans ;)

**Comment by frankvandenbergh** [comment]
Cool. Didn't know it was that easy.
Thanks Alex.
