### ISSUE TITLE
How to add Autocomplete with your own input field

### ISSUE THREAD

**Issue by etwordpress01** [komoot/photon#351]
Hello,

I have big issue, is there any option to add your own input field? I don't want to display map but map would be hidden and input field will be visible.
![download](https://user-images.githubusercontent.com/31212934/43784659-0995d4c0-9a7e-11e8-8e70-a4f488dd7a57.png)

I just want to search locations and then get latitude and longitude from this searched location and add it in some hidden field.

Something like in this site : https://themographics.com/wordpress/directory

I will appropriate if you can help me to help me if possible

Thanks

**Comment by yohanboniface** [comment]
This is not related to Photon itself.
The pattern is roughly:
- have an input where the user will type some chars
- send those chars to an URL that will respond with json
- consume this json to display choices to the user

As you don't want to do all by yourself, you'll pick a [javascript autocomplete library](https://duckduckgo.com/?q=javascript+autocomplete+library&t=ffab&ia=qa).
And last thing to highlight is that Photon will send you data in [geojson](http://geojson.org/) format.

**Comment by etwordpress01** [comment]
Hi @yohanboniface 

Thank you for response. My concern was with leaflet.photon and by mistake i created a ticket in this library.

I used leaflet library with photon and want to initialize leaflet photon on my custom field but i didn't find solution/example for it. Then i edit  leaflet.photon.js to initialize on my custom field and hide map.

![screenshot_2](https://user-images.githubusercontent.com/31212934/43955790-1cf9ba10-9cbb-11e8-8bb9-0617340068e0.png)

![screenshot_3](https://user-images.githubusercontent.com/31212934/43955923-ab5975de-9cbb-11e8-9526-3146390cf0e7.png)


I get it done by edit your leaflet.photon.js file. I want to allow to use autocomplete without map. I think it was added in commit but didn't found how to use it

https://github.com/komoot/leaflet.photon/commit/107a41cf49fa5446262af58cb30a7041e058bfe7

That is the only one library which can be use for autocomplete geocoding in leaflet. If you can write a an example for library that how users can use it then it would be batter.

Thanks
