### ISSUE TITLE
Weird location lookup issue

### ISSUE THREAD

**Issue by Kibouo** [komoot/photon#352]
I'm playing around with photon, using the API from [komoot](http://photon.komoot.de/) (big thanks to those guys for providing a free server!).

I tried looking up a location called ``Dilsen-Stokkem``. This returns results nicely.

However, let's continue typing out the location. Up till ``Dilsen-Stokkem, Flanders, Belgiu`` we continue to get results.

Now, let's finish the query; ``Dilsen-Stokkem, Flanders, Belgium``. Suddenly there are no results!

I've no idea what causes this as I wasn't able to recreate it with other place-names.

**Comment by lonvia** [comment]
Fixed with #538.
