### ISSUE TITLE
Different results

### ISSUE THREAD

**Issue by toregua** [komoot/photon#355]
Hi,
First thank you very much to komoot to share this nice tool photon :)

I have imported France into a nominatim database (https://download.geofabrik.de/europe/france-latest.osm.pbf) and i have imported data into photon using the following command : 

sudo java -jar photon-0.3.0.jar -nominatim-import -host 54.37.84.91 -port 6432 -database nominatim -user nominatim -password **** -languages fr

Everything seem ok : 
```
2018-08-28 18:09:15,896 [main] INFO  de.komoot.photon.nominatim.NominatimConnector - finished import of 8 556 193 photon documents.
2018-08-28 18:09:15,896 [main] INFO  de.komoot.photon.App - imported data from nominatim to photon with languages: fr
```
But when i search for example : "Le phare chambéry" or "Tour effeil paris" which are very popular theater and tower they are not present in my results while the results from photon.komoot.de shows them.

Query is : `/api/?q=le%20phare%20chambery&lang=fr`

With my photon results are : 

`{"features":[{"geometry":{"coordinates":[3.8751582,43.6237499],"type":"Point"},"type":"Feature","properties":{"osm_id":194112886,"osm_type":"W","extent":[3.8749477,43.6243158,3.8752366,43.6233474],"country":"France","osm_key":"waterway","city":"Montpellier","osm_value":"drain","postcode":"34090","name":"Le Chambéry","state":"Occitanie"}},{"geometry":{"coordinates":[3.8773316,43.6214953],"type":"Point"},"type":"Feature","properties":{"osm_id":304131382,"osm_type":"W","extent":[3.8749119,43.6232662,3.8802239,43.620053],"country":"France","osm_key":"waterway","city":"Montpellier","osm_value":"drain","postcode":"34000","name":"Le Chambéry","state":"Occitanie"}},{"geometry":{"coordinates":[3.874934,43.6232662],"type":"Point"},"type":"Feature","properties":{"osm_id":304131381,"osm_type":"W","extent":[3.874934,43.6233474,3.8749477,43.6232662],"country":"France","osm_key":"waterway","city":"Montpellier","osm_value":"drain","postcode":"34090","name":"Le Chambéry","state":"Occitanie"}},{"geometry":{"coordinates":[-1.2827292,49.686724],"type":"Point"},"type":"Feature","properties":{"osm_id":216351,"osm_type":"R","extent":[-1.3254279,49.6971359,-1.2630709,49.6615385],"country":"France","osm_key":"place","osm_value":"village","postcode":"50760","name":"Gatteville-le-Phare","state":"Normandie"}},{"geometry":{"coordinates":[7.3296531,43.6759128],"type":"Point"},"type":"Feature","properties":{"osm_id":1490092113,"osm_type":"N","country":"France","osm_key":"place","city":"Saint-Jean-Cap-Ferrat","osm_value":"locality","postcode":"06230","name":"Le Phare","state":"Provence-Alpes-Côte d'Azur"}},{"geometry":{"coordinates":[5.9029432,45.5979129],"type":"Point"},"type":"Feature","properties":{"osm_id":2410316165,"osm_type":"N","country":"France","osm_key":"place","city":"Chambéry","osm_value":"neighbourhood","postcode":"73000","name":"Chambéry-le-Vieux","state":"Auvergne-Rhône-Alpes"}},{"geometry":{"coordinates":[-1.9234175,48.4308295],"type":"Point"},"type":"Feature","properties":{"osm_id":2977095677,"osm_type":"N","country":"France","osm_key":"place","city":"Plesder","osm_value":"isolated_dwelling","postcode":"35720","name":"Le Phare Ouest","state":"Bretagne"}},{"geometry":{"coordinates":[3.8905420439790523,43.59903195],"type":"Point"},"type":"Feature","properties":{"osm_id":377779898,"osm_type":"W","extent":[3.8899433,43.5993511,3.8911709,43.5986062],"country":"France","osm_key":"landuse","city":"Montpellier","osm_value":"residential","postcode":"PARK","name":"Le Chambéry","state":"Occitanie"}},{"geometry":{"coordinates":[5.9592136,45.7314561],"type":"Point"},"type":"Feature","properties":{"osm_id":3334333,"osm_type":"R","extent":[5.8730129,45.7417961,6.0173591,45.6832985],"country":"France","osm_key":"waterway","osm_value":"stream","postcode":"73100","name":"Le Sierroz","state":"Auvergne-Rhône-Alpes"}},{"geometry":{"coordinates":[-1.2864489448989187,49.68779855],"type":"Point"},"type":"Feature","properties":{"osm_id":41799527,"osm_type":"W","extent":[-1.2941412,49.6912369,-1.2801108,49.6843367],"country":"France","osm_key":"landuse","city":"Gatteville-le-Phare","osm_value":"residential","postcode":"50760","name":"Gatteville-le-Phare","state":"Normandie"}},{"geometry":{"coordinates":[5.7525881,45.5417589],"type":"Point"},"type":"Feature","properties":{"osm_id":246734585,"osm_type":"W","extent":[5.7525881,45.5419771,5.7531303,45.5417589],"country":"France","osm_key":"waterway","city":"Dullin","osm_value":"river","postcode":"73610","name":"Le Thiers","state":"Auvergne-Rhône-Alpes"}},{"geometry":{"coordinates":[5.7219468,45.5445874],"type":"Point"},"type":"Feature","properties":{"osm_id":246734586,"osm_type":"W","extent":[5.6745713,45.5596558,5.7525881,45.5255838],"country":"France","osm_key":"waterway","city":"Domessin","osm_value":"river","postcode":"73330","name":"Le Thiers","state":"Auvergne-Rhône-Alpes"}},{"geometry":{"coordinates":[5.7591131,45.5433306],"type":"Point"},"type":"Feature","properties":{"osm_id":523403147,"osm_type":"W","extent":[5.7574394,45.5434489,5.760764,45.5427858],"country":"France","osm_key":"waterway","city":"Saint-Alban-de-Montbel","osm_value":"canal","postcode":"73610","name":"Le Thiers","state":"Auvergne-Rhône-Alpes"}},{"geometry":{"coordinates":[5.7551653,45.5430461],"type":"Point"},"type":"Feature","properties":{"osm_id":523403148,"osm_type":"W","extent":[5.7531303,45.5435272,5.7574394,45.5419771],"country":"France","osm_key":"waterway","city":"La Bridoire","osm_value":"river","postcode":"73520","name":"Le Thiers","state":"Auvergne-Rhône-Alpes"}},{"geometry":{"coordinates":[5.7682844,45.543816],"type":"Point"},"type":"Feature","properties":{"osm_id":370626200,"osm_type":"W","extent":[5.760764,45.544456,5.7751634,45.5426158],"country":"France","osm_key":"waterway","city":"Lépin-le-Lac","osm_value":"river","postcode":"73610","name":"Le Thiers","state":"Auvergne-Rhône-Alpes"}}],"type":"FeatureCollection"}`

and with http://photon.komoot.de/api/?q=le%20phare%20chambery&lang=fr : 

`{"features":[{"geometry":{"coordinates":[5.899697829227325,45.5836695],"type":"Point"},"type":"Feature","properties":{"osm_id":108358489,"osm_type":"W","extent":[5.898997,45.584303,5.900496,45.583051],"country":"France","osm_key":"amenity","city":"Chambéry","street":"Avenue du Grand Arietaz","osm_value":"theatre","postcode":"73000","name":"Le Phare","state":"Auvergne-Rhône-Alpes"}},{"geometry":{"coordinates":[5.9012755,45.5836174],"type":"Point"},"type":"Feature","properties":{"osm_id":1674429016,"osm_type":"N","country":"France","osm_key":"highway","housenumber":"1725","city":"Chambéry","street":"Avenue des Follaz","osm_value":"bus_stop","postcode":"73000","name":"Le Phare-Parc Expo","state":"Auvergne-Rhône-Alpes"}},{"geometry":{"coordinates":[5.8046847,45.5433314],"type":"Point"},"type":"Feature","properties":{"osm_id":5203081689,"osm_type":"N","country":"France","osm_key":"historic","city":"Lépin-le-Lac","osm_value":"archaeological_site","postcode":"73610","name":"Site archéologique de Beau-Phare","state":"Auvergne-Rhône-Alpes"}}],"type":"FeatureCollection"}`

Why this difference please and why is not found with me own photon instance ?
Do you have any ideas ?
Maybe I missed something like importing other data than nominatim ?

Thanks in advance,

toregua

**Comment by hbruch** [comment]
Bonsoir Toregua,
I assume you did not [download Wikipedia data](http://nominatim.org/release-docs/latest/admin/Import-and-Update/#downloading-additional-data) before importing France into Nominatim. Wikipedia data supplies importance values, so that important POIs are ranked higher.

Best regards,
Holger

**Comment by toregua** [comment]
Hi hbruch thanks for you suggestion.
You are right i have not used Wikipedia data before importing nominatim data.
I repeat the process with wikipedia inside data folder this time and keep you informed of the results at the end :)

Cordialy,
Toregua

**Comment by toregua** [comment]
I have made a new import inside nominatim database with wikipedia data and reimported data inside elasticsearch db for photon but results are always not the same... I don't understand. Do you have any other suggestions please ?

**Comment by numair** [comment]
There is a definite discrepancy between the dataset used on the Example API server and the dataset provided in the installation instructions. See, for example, two requests for New York using city/muni/etc filters:

<img width="495" alt="screen shot 2019-01-22 at 11 54 00 am" src="https://user-images.githubusercontent.com/625823/51507453-c300ee80-1e3c-11e9-9626-1eb567405dc2.png">
<img width="499" alt="screen shot 2019-01-22 at 11 54 27 am" src="https://user-images.githubusercontent.com/625823/51507456-c5fbdf00-1e3c-11e9-8305-64c5c0352d18.png">

**Comment by lonvia** [comment]
This issue has gone a bit stale and the examples seem to be working at the moment. Closing here. Please open a new issue if you experience similar issues with a current version of photon and the data.
