### ISSUE TITLE
Wrong postal-codes

### ISSUE THREAD

**Issue by autumnus** [komoot/photon#358]
I found two examples of wrong postal-codes (maybe there are more):

The small village Buttendorf (Germany) is inside the correct postal-code boundary in OSM (90574)
http://photon.komoot.de/api/?q=buttendorf
https://www.openstreetmap.org/relation/3351238#map=13/49.3881/10.8899

But it has the postal-code of the neighbouring village Ammerndorf (90614).
https://www.openstreetmap.org/relation/3351240

The same is the case for Escherndorf:
http://photon.komoot.de/api/?q=escherndorf
Correct boundaries (97332)
https://www.openstreetmap.org/relation/1177813#map=12/49.8675/10.2409

Wrong postalcode (97247)
https://www.openstreetmap.org/relation/3352850

**Comment by hbruch** [comment]
Photon relies on Nominatim concerning postal code calculation for places.

For the places you identified, the (wrong) postal codes are the ones currently estimated by Nominatim:
https://nominatim.openstreetmap.org/details.php?place_id=7148728
https://nominatim.openstreetmap.org/details.php?place_id=3302533  

Probably the postcode of the closed centroid is assigned as described in [nominatim issue], an not the one one of the enclosing postal-code boundary (https://github.com/openstreetmap/Nominatim/issues/855). 

@lonvia could you have a look into this issue?

**Comment by lonvia** [comment]
This is indeed a Nominatim issue. I've opened #1209 and close here.
