### ISSUE TITLE
how to get result based on my local language ?

### ISSUE THREAD

**Issue by sogand145** [komoot/photon#360]
Hi,
when I search this place on photon, get the result with the default language (en), since I had imported nominatim data of my local regions. on the other hand my language code (fa) does not support by photon.
for example:
If I put a lang parameter except en, the result appears correct, as I wanted :  
https://photon.komoot.de/api/?q=%D9%85%DB%8C%D8%AF%D8%A7%D9%86%20%D8%A7%D9%86%D9%82%D9%84%D8%A7%D8%A8&lat=35.7012061&lon=51.3924971&lang=de

but when I remove lang paramete, the result return based on en language : 
https://photon.komoot.de/api/?q=%D9%85%DB%8C%D8%AF%D8%A7%D9%86%20%D8%A7%D9%86%D9%82%D9%84%D8%A7%D8%A8&lat=35.7012061&lon=51.3924971

how to solve this problem?

**Comment by hbruch** [comment]
photon.komoot.de service to my knowledge only supports the following languages: en,fr,it,de.
If you want to request language ‚fa‘, you‘ll need to deploy your own photon instance and import from Nominatim with your language code. See the README.md, section Customized Search Data.

For further questions, please use the mailing list.

**Comment by harry-wilson** [comment]
@hbruch, using the -languages en,ru during Nominatim import for customized data, does not change the result. If we get the result as `lang=ru` it gets the following error:

> language fa is not supported, supported languages are: de, en, it, fr

**Comment by JRafiei** [comment]
@harry-wilson You sould also pass the languages option when initializing the server.
java -jar photon-0.3.1.jar -languages en,fa -listen-port 8000
