### ISSUE TITLE
how to get items more than count of limit items while searching on photon?

### ISSUE THREAD

**Issue by mbutler-79** [komoot/photon#362]
when I search a place on photon, how to get result based on pagination?
for example, I know I can use limit parameter in url while requesting, like this : 
    https://photon.komoot.de/api/?q=newyork&lat=40.730608&lon=-73.987770&limit=5000

but I don't want to get all 5000 result at the first time, I wanna to get page by page, for example 100 items at the first time, next 100 items after that.
do you know how to do that ?

Thanks in Advance

**Comment by simonpoole** [comment]
There currently isn't such a facility. Note that the maximum limit value is currently 50.

**Comment by lonvia** [comment]
I'm closing this as a rejected feature request. It is unlikely that we will ever raise the maximum limit over 50 because it makes the queries expensive. With a limit of 50, pagination is not really necessary.
