### ISSUE TITLE
Greedy street duplicate removal removes bus stops

### ISSUE THREAD

**Issue by hbruch** [komoot/photon#367]
Photon removes duplicate results of osm key='highway' with which have the same name and postal code.
This is intended as a street may be split in many ways and only one result should be returned in this case.
However, as results with different osm values get deduplicated, this results in e.g. supressed bus_stops like in the following case:

Searching explicitly for [highway:bus_stop returns the bus_stop Thingstraße](http://photon.komoot.de/api/?q=Thingstra%C3%9Fe%20Stuttgart&osm_tag=highway:bus_stop ), searching [without osm_tag filter](http://photon.komoot.de/api/?q=Thingstra%C3%9Fe%20Stuttgart) does not.

I think, osm_value should be part of the deduplication key. If this results in (too many) street duplicates, e.g. because the value/classification changes for the various ways of the same street, some more thinking would be required (e.g. distinguishing between bus_stop and street importance values).

**Comment by lonvia** [comment]
Fixed in #368.
