### ISSUE TITLE
Poisoned suggestion?

### ISSUE THREAD

**Issue by Kibouo** [komoot/photon#374]
Looking up `Xiangjingh` on [http://photon.komoot.de/](http://photon.komoot.de/) results in `Xiangjinghttp://www.hfbus.cn/Welcome/Specialbus.aspx?NewsClassID=37&page=2, Anhui, China`.

This is most certainly unintended behavior.

**Comment by lonvia** [comment]
That's a typo in the underlying OpenStreetMap data and needs to be fixed there. I have [just done so](https://www.openstreetmap.org/changeset/64847202). The fix will appear in the photon results when the database gets updated next. I cannot say when exactly this will be.

You can also fix these errors yourself, see https://www.openstreetmap.org/fixthemap for details.

**Comment by Kibouo** [comment]
Thanks! I did not know how this worked. Next time I'll gladly submit a fix myself! :smile:
