### ISSUE TITLE
Using DB created by osm2pgsql without Nominatim. Is it possible?

### ISSUE THREAD

**Issue by ifle** [komoot/photon#389]
Is it possible to use photon with db created by osm2pgsql?

**Comment by lonvia** [comment]
No.

**Comment by ifle** [comment]
Is there a way use photon without Nominatim?

**Comment by lonvia** [comment]
Yes, use the dumps we provide for your convenience. See installation instructions in the README.

**Comment by ifle** [comment]
The problem that dumps does not contains my language.

**Comment by simonpoole** [comment]
@ifle could you indicate what your required language(s) is?
