### ISSUE TITLE
Missing photon jar for v0.3.1

### ISSUE THREAD

**Issue by thomasnordquist** [komoot/photon#393]
Not sure if intended, but I didn't find a jar for this release.
https://github.com/komoot/photon/releases/tag/0.3.1

**Comment by karussell** [comment]
See #280

**Comment by lonvia** [comment]
I think we did provide a ready-to-use jar on the release page in the past. I' ll try to do that some time this week unless @karussell beats me to it (hint, hint ;)).

**Comment by karussell** [comment]
Ah, that was meant, sorry @thomasnordquist . Will do :)

**Comment by karussell** [comment]
Done!

**Comment by thomasnordquist** [comment]
Thanks 😊
