### ISSUE TITLE
Field city missing for addresses in Vienna

### ISSUE THREAD

**Issue by dthulke** [komoot/photon#396]
Responses to queries for addresses inside Vienna, Austria do not contain the city attribute. For example http://photon.komoot.de/api/?q=Stephansplatz%20Wien&lang=en .

Is this behaviour intended, due to a mapping error or a bug in Photon?
In contrast, results for other city states always contain both the city and state field (e.g. Hamburg and Salzburg) or only contain the city but note the state field (e.g. Berlin).

**Comment by simonpoole** [comment]
Where the bug is a matter of debate, but photon currently has a hardwired list of these special cases which doesn't contain Vienna. If all goes well I should be able to test if adding Vienna to that list actually fixes the issue and have a look at at least making the list end-user configurable.

**Comment by lonvia** [comment]
#457 will fix this.

**Comment by lonvia** [comment]
This is now fixed in the extracts provided by graphhopper. I expect that the komoot instance gets updated soon.
