### ISSUE TITLE
Problem with Version 0.3.1 causing Access Control Errors

### ISSUE THREAD

**Issue by aimdev** [komoot/photon#397]
Utilising the same elastic search database.the downloaded 0.3.1 version causes the browser to emit error messages and no search results

[Error] Origin http://ndevosm.foo.bar is not allowed by Access-Control-Allow-Origin.
[Error] XMLHttpRequest cannot load http://ndevosm.foo.bar:2322/api/?q=esher&limit=20&lat=51.47685200000001 due to access control checks.
[Error] Failed to load resource: Origin http://ndevosm.foo.bar is not allowed by Access-Control-Allow-Origin. (api, line 0)

photon@ndevosm:/ssd2/photon$ /usr/bin/java -jar photon-0.3.1.jar
2019-04-02 19:37:25,839 [main] WARN  org.elasticsearch.node.Node - version [5.5.0-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
2019-04-02 19:37:30,901 [main] INFO  de.komoot.photon.elasticsearch.Server - started elastic search node
2019-04-02 19:37:30,986 [Thread-1] WARN  org.eclipse.jetty.server.AbstractConnector - Ignoring deprecated socket close linger time

photon@ndevosm:/ssd2/photon$ /usr/bin/java -jar photon-0.3.0.jar
2019-04-02 19:39:27,097 [main] WARN  org.elasticsearch.node.Node - version [5.5.0-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
2019-04-02 19:39:32,087 [main] INFO  de.komoot.photon.elasticsearch.Server - started elastic search node

The downloaded version 0.3.0 works perfectly, but without the enhancements of 0.3.1 :(

Note the WARN on the 0.3.1 startup.

Debian Stretch
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by aimdev** [comment]
Further to my original post I download both version source tgz file, built the jars, but the problem still exists as described.

**Comment by simonpoole** [comment]
Do local queries on the machine running photon work? http://localhost:2322/api/?q=esher&limit=20&lat=51.47685200000001

**Comment by aimdev** [comment]
In all cases (distributed  and complied), all versions the command
curl http://localhost:2322/api/?q=esher&limit=20&lat=51.47685200000001
provides the correct data.
Photon runs on a server, so no gui or browser.

**Comment by simonpoole** [comment]
> 
> 
> In all cases (distributed and complied), all versions the command

> Photon runs on a server, so no gui or browser.
But your browser is accessing a script for the query on a different host that actually makes the query?

**Comment by aimdev** [comment]
Hi
The browser is accessing via javascript, the photon service. 
All the code is on the server (/var/www/gis) 
The web server, photon server and mapserver are all on the same system, same ip address, and all worked ok at version 0.3.0.
Thanks for pointing me in the direction to look, if it is spark (v2.7.1 - v2.8.0), then maybe I can recompile to get it to work.
Having yet another layer to deal with really is not attractive.

**Comment by simonpoole** [comment]
For future reference http://sparkjava.com/tutorials/cors

**Comment by simonpoole** [comment]
> The web server, photon server and mapserver are all on the same system, same ip address, and all worked ok at version 0.3.0.

I would expect (if you are using the same domain throughout), that the problem is caused by the port (aka this being considered different for CORS purposes than a server running with the same domain but a different port). I would consider this something Photon should allow access for as standard.

**Comment by aimdev** [comment]
Not sure I understand the port issue, do you mean change it from 2322?, if so to what?
Recompiling v0.3.1 with spark 2.7.1 did not work, same error.
Looks like I will have to either RE the 0.3.1 bits into a 0.3.0 version, if that fails, more digging into the code.

**Comment by simonpoole** [comment]
Have you tried with a different browser, and have you checked (with the browser console or similar) what is actually happening., in particular what is different between your working 0.0 version and 0.31. 

Wrt the port issue: CORS checks restrict access by scripts to sites other than the original domain (and that means that domains with different ports are considered different for the purpose of such checks).

**Comment by aimdev** [comment]
Brave has the same issue, yes checked in the developers tools to get the errors on both browsers

**Comment by simonpoole** [comment]
> 
> 
> Brave has the same issue
And the other browser is? I would definitely check with FF if you haven't already.

**Comment by aimdev** [comment]
Safari

**Comment by lonvia** [comment]
See also https://github.com/komoot/photon/pull/373

**Comment by aimdev** [comment]
> See also #373

Hi
Thanks for that, added and now working again.
Will this option be included in future releases?

**Comment by simonpoole** [comment]
IMHO something is broken somewhere as I already get a Access-Control-Allow-Origin header in my testing with the stock 0.31, see https://github.com/komoot/photon/issues/81 and we need to get to the bottom of why we are seeing flaky behaviour. 

@aimdev unluckily you still haven't told us what differences you saw in your testing so that we could narrow things down.  But obviously if it is necessary I think you can assume that an option will be added.

**Comment by aimdev** [comment]
@simonpoole @lonvia 

The code additions  to support cors as an option, as pointed out by Ionvia, (#373)  were added .
Testing was then successful, no cors errors., accessing photon without a proxy, ie direct.
I have noticed that if there is any issue calling photon, in my case using javascript and open layers, the error returned always intimates its a cors issue.
I am at the moment not sure why this is, perhaps it's the normal situation.
To simplify, 
the distributed and compiled  v0.3.0 works
the distributed and compiled  v0.3.1 fails with cors errors
the modified 0.3.1 from the source tgz and the modifications in #373 v0.3.1 works

**Comment by simonpoole** [comment]
@aimdev with "differences" I meant headers exchanged during execution of your query, it is clear which version works for you and which not, but to determine the cause it would be helpful to know what the actual behavioural differences are, so if 0.31 (unpatched) is sending different headers than 0.30.

**Comment by aimdev** [comment]
@simonpoole 
Please suggest where this information can been seen, for example  I do not see it in the  apache log?
All browsers as far as i can see only send the error messages, not actual http exchange.

**Comment by simonpoole** [comment]
In Chrome derived browsers: More tools, Developer tools, locate the actual query url starting with ?q=.... then look at the Headers tab (in FF there is a similar facility).
