### ISSUE TITLE
Reverse Geocode To Nearest Road

### ISSUE THREAD

**Issue by T-T-P** [komoot/photon#406]
Is there a way of excluding certain results from a reverse geocode request. For example could I remove buildings so that Photon only returns the nearest road to the latitude / longitude? If this isn't possible could I request as a new feature please.

**Comment by simonpoole** [comment]
There currently isn't a documented way to do this (but potentially an undocumented way that I would need to test first to see if it actually works). 

In any case while filtering would clearly be possible, reverse coding to ways will suffer from the issue mentioned in https://github.com/komoot/photon/issues/357

**Comment by T-T-P** [comment]
@simonpoole Thank you for your response, would it be possible for you to share the undocumented method please? I would be happy to run some tests on the Photon instance I have set up to see if I can get something working?

In terms of the issue mentioned in #357 is "Multi Location Per Document" something that any contributors are looking into at present?

**Comment by lonvia** [comment]
This works these days with the mildy obscure parameter `query_string_filter=osm_key:highway`. The parameter allows you to set a filter, which we here restrict to OSM objects of type highway. You'd still get footways with that but no more buildings or addresses. For example:

http://photon.komoot.de/reverse?lat=52.9112327&lon=-1.4786067&query_string_filter=osm_key:highway

Issue #357 still applies.
