### ISSUE TITLE
Service down?

### ISSUE THREAD

**Issue by opyh** [komoot/photon#414]
Hi,

First of all: thank you so much for providing this service to the open source community! <3

It seems service is down currently, which impacts wheelmap.org: https://photon.komoot.de/api/?q=dortmund&limit=30&lang=en

Do you know when it will be working again? Are there other people hosting public alternative deployments usable as a fallback? I thought about hosting an own instance, but didn't have the time yet.

**Comment by opyh** [comment]
(It's working again. Thanks!)

**Comment by dgoujard** [comment]
Hello,

It's seem like the demo API is down again.

Thanks

**Comment by opyh** [comment]
Can confirm it's broken at the moment…

**Comment by holgerd** [comment]
Photon search seems to be down again right now. Help is appreciated!

**Comment by holgerd** [comment]
... and it's back.
