### ISSUE TITLE
missing system requirements in README

### ISSUE THREAD

**Issue by alexandervlpl** [komoot/photon#416]
I want to run Photon myself instead of abusing your excellent API. :)

It would be really helpful to see system requirements somewhere, so I can immediately pick the right hosting solution!

**Comment by oberhamsi** [comment]
you only need java 8. photon can work with an external elasticsearch cluster but will start its own instance by default.

**Comment by otbutz** [comment]
> can work with an external elasticsearch cluster

Would be good to know which versions of ES are supported though.

**Comment by oberhamsi** [comment]
it's packaged with elastic 5.5. so every elastic that is compatible with that one should work. i'm only familiar with 1.x and 7.x so i can't really say.

**Comment by alexandervlpl** [comment]
I actually meant **hardware** requirements. I have this running very well with 16GB RAM, SSD, 2.1Ghz Intel Xeon (4 core).

Maybe we can establish and document a minimal setup?

**Comment by lonvia** [comment]
Duplicate of #523.
