### ISSUE TITLE
Nearby search without the POI's title

### ISSUE THREAD

**Issue by harry-wilson** [komoot/photon#417]
The search for POIs using the key and value of osm-tags works well, but it is not applicable of searching for a specific POI category like cafes located in the user's nearby without exposing its name in the request. As an illustration, if I want to search for cafes near my location that don't know its name as following, it gives me the empty result:

`http://localhost:2322/api?q=&osm_tag=:cafe&lon=10&lat=52&location_bias_scale=2`

How can I achieve this which is the same as nearby search in Nominatim?

**Comment by ColdDevil** [comment]
Take a look at this issue: https://github.com/komoot/photon/issues/478
I guess for Photon to work properly, a search string is mandatory. For all other search types, such as nearby search, Overpass seems to be the better way 😄

**Comment by lonvia** [comment]
Please use Overpass API for these kind of requests.
