### ISSUE TITLE
Feature request: zoom level parameter

### ISSUE THREAD

**Issue by timautin** [komoot/photon#428]
Hello,

Currently, we can use the location bias to tell Photon to return results closer to the lat/lon position. It works well but I have no idea of which bias should I use at which zoom level. I'm trying different things randomly with mixed results.

Wouldn't it be better if we could directly give Photon a zoom level?

Or at least, could you provide some documentation about the location bias / a formula to convert a zoom level to a bias? Why is it [0.1 .. 10]? Is it linear? What does it do exactly?

Thanks in advance!

**Comment by lonvia** [comment]
Implemented in #580.
