### ISSUE TITLE
bbox not working from mobile app

### ISSUE THREAD

**Issue by DelmarZhao** [komoot/photon#431]
According to the API documentation,  I should be able to filter results using the bbox query parameter. The example from the documentation is:
`http://photon.komoot.de/api?q=berlin&bbox=9.5,51.5,11.5,53.5`
However, when I try to run this query from my FLutter mobile app's http.get() method, I get the following response:
`Error: 400, {"message":"unknown query parameter 'bbox'.  Allowed parameters are: [q, location_bias_scale, limit, osm_tag, lon, lang, lat]`

However, when I run the exact same query from the command line using:
`curl http://photon.komoot.de/api?q=berlin&bbox=9.5,51.5,11.5,53.5`, I get the proper response I was expecting which is:

{"features":[{"geometry":{"coordinates":[13.3888599,52.5170365],"type":"Point"},"type":"Feature","properties":{"osm_id":240109189,"osm_type":"N","country":"Germany","osm_key":"place","city":"Berlin","osm_value":"city","postcode":"10117","name":"Berlin"}},{"geometry":{"coordinates":[13.397482681501469,52.506934799999996],"type":"Point"},"type":"Feature","properties":{"osm_id":62422,"osm_type":"R","extent":[13.088345,52.6755087,13.7611609,52.3382448],"country":"Germany","osm_key":"place","osm_value":"city","name":"Berlin"}},{"geometry":{"coordinates":[13.4385964,52.5198535],"type":"Point"},"type":"Feature","properties":{"osm_id":2050132586,"osm_type":"N","country":"Germany","osm_key":"place","city":"Berlin","osm_value":"state","name":"Berlin"}},{"geometry":{"coordinates":[13.392878175855376,52.518580400000005],"type":"Point"},"type":"Feature","properties":{"osm_id":6647,"osm_type":"R","extent":[13.3924338,52.5191829,13.3948768,52.5175259],"country":"Germany","osm_key":"building","housenumber":"6","city":"Berlin","street":"Unter den Linden","osm_value":"university","postcode":"10117","name":"Humboldt University of Berlin (main building)"}},{"geometry":{"coordinates":[13.393560493637775,52.51875685],"type":"Point"},"type":"Feature","properties":{"osm_id":120456814,"osm_type":"W","extent":[13.3906703,52.5200704,13.3948873,52.5175007],"country":"Germany","osm_key":"amenity","city":"Berlin","street":"Dorotheenstraße","osm_value":"university","postcode":"10117","name":"Humboldt University in Berlin Mitte Campus"}},{"geometry":{"coordinates":[13.239776301622072,52.5147077],"type":"Point"},"type":"Feature","properties":{"osm_id":38862723,"osm_type":"W","extent":[13.2364563,52.5161915,13.2433375,52.5129557],"country":"Germany","osm_key":"leisure","housenumber":"3","city":"Berlin","street":"Olympischer Platz","osm_value":"stadium","postcode":"14053","name":"Berlin Olympic Stadium"}},{"geometry":{"coordinates":[13.377739577932736,52.52585125],"type":"Point"},"type":"Feature","properties":{"osm_id":583306346,"osm_type":"W","extent":[13.3739245,52.528547,13.3818019,52.5229778],"country":"Germany","osm_key":"amenity","city":"Berlin","street":"Hufelandweg","osm_value":"hospital","postcode":"10117","name":"Charité Universitätsmedizin Berlin"}},{"geometry":{"coordinates":[13.3814231,52.5127537],"type":"Point"},"type":"Feature","properties":{"osm_id":1078631331,"osm_type":"N","country":"Germany","osm_key":"historic","city":"Berlin","street":"Gertrud-Kolmar-Straße","osm_value":"battlefield","postcode":"10117","name":"Battle of Berlin"}},{"geometry":{"coordinates":[13.3696614,52.5249451],"type":"Point"},"type":"Feature","properties":{"osm_id":3856100103,"osm_type":"N","country":"Germany","osm_key":"railway","city":"Berlin","street":"Washingtonplatz","osm_value":"station","postcode":"10557","name":"Berlin Hauptbahnhof"}},{"geometry":{"coordinates":[13.381504320489928,52.50786655],"type":"Point"},"type":"Feature","properties":{"osm_id":1154556,"osm_type":"R","extent":[13.3807495,52.5083344,13.3822459,52.5074359],"country":"Germany","osm_key":"office","housenumber":"5","city":"Berlin","street":"Niederkirchnerstraße","osm_value":"government","postcode":"10117","name":"Berlin House of Delegates"}},{"geometry":{"coordinates":[13.3083771,52.5121441],"type":"Point"},"type":"Feature","properties":{"osm_id":289404068,"osm_type":"N","country":"Germany","osm_key":"amenity","housenumber":"35","city":"Berlin","street":"Bismarckstraße","osm_value":"theatre","postcode":"10627","name":"German Opera Berlin"}},{"geometry":{"coordinates":[13.3869884,52.5201744],"type":"Point"},"type":"Feature","properties":{"osm_id":530812080,"osm_type":"N","country":"Germany","osm_key":"railway","housenumber":"14-18","city":"Berlin","street":"Georgenstraße","osm_value":"station","postcode":"10117","name":"Berlin Friedrichstraße"}},{"geometry":{"coordinates":[13.4349112,52.5103817],"type":"Point"},"type":"Feature","properties":{"osm_id":3419894993,"osm_type":"N","country":"Germany","osm_key":"railway","city":"Berlin","street":"Berlin Ostbahnhof","osm_value":"station","postcode":"10243","name":"Berlin Ostbahnhof"}},{"geometry":{"coordinates":[13.4082985,52.519961],"type":"Point"},"type":"Feature","properties":{"osm_id":539358887,"osm_type":"N","country":"Germany","osm_key":"place","city":"Berlin","osm_value":"locality","postcode":"10178","name":"Alt-Berlin"}},{"geometry":{"coordinates":[13.339242089653244,52.50827195],"type":"Point"},"type":"Feature","properties":{"osm_id":9393789,"osm_type":"W","extent":[13.3337324,52.5111342,13.3461375,52.5054269],"country":"Germany","osm_key":"leisure","housenumber":"8","city":"Berlin","street":"Hardenbergplatz","osm_value":"zoo","postcode":"10787","name":"Berlin Zoological Garden"}}],"type":"FeatureCollection"}

Is there a reason the API doesn't support bbox when I am requesting from my mobile app, but does when using curl?

**Comment by lonvia** [comment]
`bbox` is a new feature that has not been released yet and is therefore not available on https://photon.komoot.de.

**Comment by DelmarZhao** [comment]
Is there a reason it seems to work, or at least doesn't return me an API error, on https://photon.komoot.de when I send the get request using cURL?

**Comment by lonvia** [comment]
I suspect your curl line is not doing what you think it is. Try `curl 'http://photon.komoot.de/api?q=berlin&bbox=9.5,51.5,11.5,53.5'` (i.e. with a properly quoted command line parameter).

**Comment by DelmarZhao** [comment]
I see. Does this mean I must set up and run photon locally if I wish to use bbox? Or are there plans to move this feature to photon.komoot soon.

Thank you for your help

**Comment by lonvia** [comment]
It likely happens with the next release. There are no immediate plans for making on e at the moment.

**Comment by geekdenz** [comment]
This is definitely a feature that we would welcome as well.
