### ISSUE TITLE
Some bus stops don't show in the results

### ISSUE THREAD

**Issue by mlundblad** [komoot/photon#432]
Some bus stops such as this one, OSM relation 2814490 (with the name "Bandstolsvägen") does not appear in the search results (I found some similar cases, and all seems to be ones using a relation to tie together several stop positions).
Running the following as a test: curl https://photon.komoot.de/api?q=Bandstolsvägen
Also adding location bias doesn't change.
This place shows up when using Nominatim. Maybe there is something strange going on regarding indexing of OSM relations (other types of relations works though, such as administrative borders).

**Comment by lonvia** [comment]
The `highway=bus_stop` nodes show up as expected as the second result. Nominatim also only shows the node. It does not import relations of `type=public_transport` and likely never will. Consequently photon doesn't get the relations either.
