### ISSUE TITLE
Reverse Geocoding results have no city attribute in Hong Kong

### ISSUE THREAD

**Issue by moritzbruder** [komoot/photon#434]
When reverse geocoding for Coordinates in Hong Kong, the resulting features are missing the city attribute and have no indicator that they are in Hong Kong. They only have China set as the country and then street and house no.
Example: [http://photon.komoot.de/reverse?&lat=22.2727979&lon=114.1802923](http://photon.komoot.de/reverse?&lat=22.2727979&lon=114.1802923)

Some actually have a city field (see following example), but nothing that indicates towards Hong Kong / Hong Kong SAR:
[http://photon.komoot.de/reverse?&lat=22.442126&lon=114.125092](http://photon.komoot.de/reverse?&lat=22.442126&lon=114.125092)
The cities that do show up here don't even seem to be districts, although I am not certain about that part. (The "city" in this example seems to be a bus stop...)

PS: Never submitted an issue before, I hope this is fine :pray:

**Comment by lonvia** [comment]
#457 would improve the situation here and add Hong Kong as state. It will still show up with country code `CN` but that is a Nominatim issue, see https://github.com/osm-search/Nominatim/issues/202#issuecomment-417842519.

**Comment by lonvia** [comment]
This is now fixed in the extracts provided by graphhopper. I expect that the komoot instance will be updated soon.
