### ISSUE TITLE
Use alias 'photon' instead of index

### ISSUE THREAD

**Issue by karussell** [komoot/photon#44]
Instead of creating an index called 'photon' it should be thought about creating an index called e.g. 'photon_1' or 'photon_<date>' and add an alias then called 'photon'. This could make it easy in production to feed a new index without touching the old and fast switching. Not sure if this should be part of this project but this is an easy change and increases flexibility.

**Comment by hbruch** [comment]
PR #47 closed this issue, but it seems to me, that this feature was not migrated to the Java version?

I wonder, if currently most Photon users use continuous Nominatim updates, or just build a new standalone ES index, so there is no demand for this feature anymore?
