### ISSUE TITLE
When querying without lang param, return name instead of name_en

### ISSUE THREAD

**Issue by nighto** [komoot/photon#441]
Hello,
I am facing some inconsistencies using Photon that I believe could be classified as a bug. Let's consider, for instance, the query for [`Maracanã`](http://photon.komoot.de/api/?q=Maracan%C3%A3) **without `&lang=en`:**

```json
{
  "features": [
    {
      (...)
      "properties": {
        "osm_id": 4587734,
        "name": "Maracanã Stadium",
        (...)
      }
    },
  ]
}
```

However [relation 4587734](https://www.openstreetmap.org/relation/4587734) doesn't have "Maracanã Stadium" as its `name`, but rather as its `name_en`, which is not optimal for countries that have their language as other language than english.

![image](https://user-images.githubusercontent.com/397851/68416887-1d70fe80-0174-11ea-9ec1-da03798b324b.png)

Would it be possible that Photon would return the `name` tag value instead of `name_en` when there are not lang specified in the URL call?

Thanks in advance.

**Comment by lonvia** [comment]
I've run into this recently while setting up the geocoder-tests. I tend to agree that we should return `name`, when lang is missing.

I just wonder if we can still change this after the API has returned `name:en` for so many years. One option would be to add a parameter that sets the default language returned. Then people who need it could run their instance in backward-compatibility mode. @karussell any opinion on this?
