### ISSUE TITLE
"Gemeinde" nodes from Austria are not invisible

### ISSUE THREAD

**Issue by chriswalg** [komoot/photon#445]
When asked the street Flugfeldstraße 3 in 2752 Wöllersdorf-Steinabrückl.
As an answer, however, the "Gemeinde Wöllersdorf-Steinabrückl" will be returned. According to OSM for Austria, the word "Gemeinde" should not be returned.

**Comment by lonvia** [comment]
That's clearly a data issue then. It is tagged as "Gemeinde Wöllersdorf-Steinabrückl" in OSM: https://www.openstreetmap.org/relation/110407

**Comment by chriswalg** [comment]
I changed it now in OSM. When is it up to date in photon?

**Comment by lonvia** [comment]
Earliest some time next week.

**Comment by chriswalg** [comment]
https://wiki.openstreetmap.org/wiki/AT/Gemeinden
Vom Hauptort im Bezirk gibt es zwei Nodes (Orts- und Gemeindenode), den Ortsnode beschriften und den Gemeindenode daneben und unsichtbar machen (name= und place= leer).

https://www.openstreetmap.org/changeset/78425810#map=14/47.8649/16.1790
