### ISSUE TITLE
Elastic cluster Basic Auth

### ISSUE THREAD

**Issue by ambrusadrianz** [komoot/photon#446]
Cannot connect photon to an elastic cluster with basic authentication. The logic which parses the `-transport-addresses` argument goes for the first `:` and the port integer parsing fails.

Example: username:password@elastic-cluster-host:elastic-cluster-port

**Comment by karussell** [comment]
Basic Auth is not part of the open source ElasticSearch version and so we won't support it. Still you can provide a pull request where you make this working.
