### ISSUE TITLE
Reverse Geocoding to show house names

### ISSUE THREAD

**Issue by Dr-Mx** [komoot/photon#448]
Showing the `addr:housename` tag in results would be a lovely feature to have, especially for us UK folks. Cheers.

**Comment by lonvia** [comment]
I would expect this to appear in the `name` field. Do you have an example?

**Comment by Dr-Mx** [comment]
Sure!

https://photon.komoot.de/reverse/?lat=50.83764116413087&lon=0.4698291420936585&distance_sort=true&radius=0.05

Returns this way: https://www.openstreetmap.org/way/385566026 without making use of the "addr:housename"="Beach Towers" tag.

Thanks.

**Comment by lonvia** [comment]
Thanks. Should be fairly simple to add and not cause too much issues with the index.

**Comment by lonvia** [comment]
Fixed in #458.

Note that you can't really search for the house name because it is not possible to search for any of the extra names. This needs fixing in general, so I'm closing this issue here.

**Comment by Dr-Mx** [comment]
Excellent, thank you.
