### ISSUE TITLE
Missing countrycode in result

### ISSUE THREAD

**Issue by chr-sk** [komoot/photon#450]
With photon-0.3.2, I don't get a countrycode in the GeoJSON output. It does not work on photon.komoot.de either (though I don't know which version of photon is running there). See e.g.: http://photon.komoot.de/api/?q=berlin

**Comment by lonvia** [comment]
Duplicate of #183.

**Comment by lonvia** [comment]
Hmm, I see. The country code should be there.

**Comment by lonvia** [comment]
This is actually a problem with the dumps we provide.

**Comment by lonvia** [comment]
The dumps now contain the country code. The komoot instance should update to the new dumps in the next couple of days.

**Comment by rastapopougros** [comment]
Hello @lonvia, you announced "couple of days", but… 2 months later, it seems there is still no country_code in the Komoot response, for any request (tested with few european cities)

Is it broken again for another reason, or not updated?

**Comment by rastapopougros** [comment]
Allo allo? :) 
There is still no country code at all in any response of the komoot.de instance. I really think this issue has to be re-opened. No?
