### ISSUE TITLE
How to configure photon for specific region(.pbf)

### ISSUE THREAD

**Issue by lasanthaa** [komoot/photon#452]
Hi, 
How can i configure photon with specific region result set?

**Comment by FlavioBayer** [comment]
According to the README file, if you need to customize your search data (specific region, for example) you should first import your data (may be your .pbf file) into [Nominatim](https://github.com/osm-search/Nominatim) and then import it to Photon.
Please see [Customized Search Data
](https://github.com/komoot/photon#customized-search-data) for details.

**Comment by lonvia** [comment]
Nothing to add to @FlavioBayer answer.
