### ISSUE TITLE
Photon name definition

### ISSUE THREAD

**Issue by lucamp** [komoot/photon#456]
Hi,
in another app "acastus photon", which is based on Photon, the name Photon was translated in Italian Spanish and Portuguese to something like "Photo of Acastus", missing the final n and resulting in something related to phograph.
To me Photon means an elementary particle as described by wikipedia, am I wrong?

Thanks
Luca

**Comment by lonvia** [comment]
The name comes from the light particle. But shouldn't you be raising the issue in the acastus repo?

**Comment by lucamp** [comment]
Hi,
Acastus Photon uses Photon, they have not made it neither decided its name. So I asked here where Photon has been developed.
Now that it is clear Photon's origin name, I can correct the translation and I can open an issue in Acastus Photon making clear that translator of the three languages above made a mistake.

Thanks
Luca
