### ISSUE TITLE
Updates no longer index Nominatim database

### ISSUE THREAD

**Issue by lonvia** [komoot/photon#474]
When running updates both via `-nominatim-update` and via `curl http://localhost:2322/nominatim-update` the Nominatim data is no lober indexed. The reason is that the SQL statement `update placex set indexed_status = 0` gets rolled back. (In fact, all transactions get rolled back but we don't care much about read-only queries.)

This might be a fall-out from the recent switch to newer postgresql libraries.

Initially reported by @leonardehrenfried, who noticed that updates needed more and more time.

**Comment by leonardehrenfried** [comment]
Seems like I broke it myself in this commit: https://github.com/komoot/photon/commit/ac3b37add97558916a2cfd1d473b86dfedfbaef9

**Comment by leonardehrenfried** [comment]
Even more reasons to add an integration test.
