### ISSUE TITLE
Get all points within bbox without passing query paramater.(q=)

### ISSUE THREAD

**Issue by lasanthaa** [komoot/photon#478]
Hello Photon,

Is it possible to get all locations within bbox without passing query parameter?

**I assume if we pass query parameter ,then it won't output all results within the bbox.**
(if query not match any of  properties it will not show in output)

**Comment by ColdDevil** [comment]
Has someone found a workaround yet? I was wondering if this can be achieved using the Overpass API? https://wiki.openstreetmap.org/wiki/Overpass_API

**Comment by mtmail** [comment]
@ColdDevil Yes, Overpass API is usually suggested for this type of query.

**Comment by ColdDevil** [comment]
My current workaround is to collect all nodes with the tag "amenity" and "shop" within a bbox. Here an example for Berlin :) https://overpass-api.de/api/interpreter?data=%5Bout%3Ajson%5D%5Btimeout%3A25%5D%5Bbbox%3A52.51338070431167%2C13.383783102035522%2C52.51828394522958%2C13.392269611358643%5D%3B%0A%28%0A%20%20node%5Bamenity%5D%5Bname%5D%3B%0A%20%20node%5Bshop%5D%5Bname%5D%3B%0A%29%3B%0Aout%3B

Or as code for https://overpass-turbo.eu/ 
```
[out:json][timeout:25][bbox:{{bbox}}];
(
  node[amenity][name];
  node[shop][name];
);
out;
```

**Comment by lonvia** [comment]
Overpass is definitely the better tool for the task. Closing here as won' t fix.
