### ISSUE TITLE
"extensive usage will be throttled"

### ISSUE THREAD

**Issue by matkoniecz** [komoot/photon#479]
"extensive usage will be throttled" on http://photon.komoot.de/ is a bit unclear.

Is it OK to make 10 requests a day? 10 000? 1 000 000? At least 1 second between requests? No continued use?

I am not trying to game it, I just want to avoid mistakes by many orders of magnitude.

It would be sad to run 1 request every two seconds while expected use is <100 requests a day. And to worry about 1 req/s while "extensive usage" would be in millions of requests.

**Comment by lonvia** [comment]
There is no hard limit and no definitive answer to this question. The server is meant as a demo instance and to give people a chance to play with geocoding. As a rule of thumb: if you have to ask, you are quite likely better off running your own local instance. It's really easy to do with the data dumps we provide.
