### ISSUE TITLE
Search Index Download not working

### ISSUE THREAD

**Issue by nivangio** [komoot/photon#481]
I am getting a connection refused when trying to download the search index out of 

https://download1.graphhopper.com/public/photon-db-latest.tar.bz2

Is there any other place I can get it from?

Thx!

**Comment by lonvia** [comment]
The link is **http**://download1.graphhopper.com/public/photon-db-latest.tar.bz2. Please be mindful of forwarding in your browser because of HSTS.

**Comment by lonvia** [comment]
HTTPS now works as well.
