### ISSUE TITLE
Photon index file does not contain states for India anymore

### ISSUE THREAD

**Issue by prasadrajuv** [komoot/photon#482]
as observed code it implemented all district and state fields. but in reality it reads placex table from nominatim. but in placex those information is missing but it produce all information using recursive parent id.

https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=245636751&class=place
it gives 
bhimavaram, west godavari,, Andhra Pradesh, India.  (place, district, state, india).

but in placex table dont have info district and state. 
photon result like :   bhimavaram, india. but in same state lot of similar names and also some other states have similar names. district and state info is necessary to distinguish them.
it should calculated using recursive using parent_id like below link

https://github.com/osm-search/Nominatim/blob/master/sql/functions/placex_triggers.sql

**Comment by lonvia** [comment]
Photon already uses the `place_addressline` table to get the state, district etc information.

**Comment by ozambrano** [comment]
The issue might be in the index files. The new files are not providing the State field. The last index that provided the State is from June 14. I've compared with that index and the newest index and in the indices that provide the locality we don't get the state.

**Comment by lonvia** [comment]
Thank you. It helps to report the problem instead of the perceived solution. ;) I can confirm that all states are missing. Fix coming up soon.

**Comment by lonvia** [comment]
A new data dump is in the works. It should arrive in a day or so at the usual place.
