### ISSUE TITLE
area -> point reduction is not ideal for complex shapes and may place returned location far away from center

### ISSUE THREAD

**Issue by matkoniecz** [komoot/photon#487]
area->point reduction used is quite poor and places result in a weird position (mapnik library used by default layer places label in the same position, so it is not unusual - still, I would be ideal to place them differently

https://photon.komoot.de/ -> enter `Rynek, Kraków` search term

![screen02](https://user-images.githubusercontent.com/899988/92018908-1b58db80-ed56-11ea-87f4-95827c437e4b.png)

I expected it at https://www.openstreetmap.org/?mlat=50.06185&mlon=19.93690#map=18/50.06185/19.93690 or https://www.openstreetmap.org/?mlat=50.06153&mlon=19.93775#map=18/50.06153/19.93775

**Comment by lonvia** [comment]
Not really a Photon issue. It just takes the centroid as provided by Nominatim. It does not compute one itself. Nominatim in turn  just uses standard PostGIS functions.

**Comment by matkoniecz** [comment]
So it would be WONTFIXed also in Nominatima and therefore is not worth reporting?

**Comment by mtmail** [comment]
The difference between the screenshot and the expected results is less than 100m. All three position are inside the Main Square and I'm not sure any is much better than the other.

**Comment by lonvia** [comment]
It would end up very, very far down on the todo list, exactly for the reasons mentioned by @mtmail. You can provide a PR with a better computation, if you like to do some research. Just keep in mind that any alternative implementation would have to prove that it does not degrade indexing performance.
