### ISSUE TITLE
Support PlusCode alongside Housenumber

### ISSUE THREAD

**Issue by aerotypebharat** [komoot/photon#495]
I am running local nominatim with addr:pluscode for my project because mostly of the time houses are not numbered. I want to search by pluscode https://plus.codes/ as well as the house number. How can I add this functionality in my custom build? I have included the image for reference
![image](https://user-images.githubusercontent.com/10284102/93829613-a3ceeb80-fc33-11ea-9b50-6437c775d496.png)

**Comment by lonvia** [comment]
Have a look at the [completeFromAddress()](https://github.com/komoot/photon/blob/967bd997d9ea79d028213fb7f2f777e6538817d8/src/main/java/de/komoot/photon/PhotonDoc.java#L153) function to add support for other addr: tags.

That said I'd like to point out that it doesn't make sense to add PlusCodes to a geocoding database, neither for Nominatim nor for Photon. They should be parsed and handled on the query-side, either as a front end to the server or better directly on the client side.
