### ISSUE TITLE
Issues with 0.3.4 / plugin descriptor for wordending-tokenfilter - unable to launch photon

### ISSUE THREAD

**Issue by robertharm** [komoot/photon#498]
I tried to update from 0.3.0 to 0.3.4 to be able to use the newest index - unfortunately I get the following error when trying to launch photon: 

`Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [wordending-tokenfilter]. Was the plugin built before 2.0?`

I search for a related file plugin-descriptor.properties but unfortunately couldnt find it in this repo (nor via Google).
Any hint on what I am missing here would be much appreciated!
thx!

**Comment by lonvia** [comment]
How exactly did you update? What version of Java do you use?

**Comment by robertharm** [comment]
I uploaded photon-0.3.4.jar into a new directory on the webserver and ran "java -jar photon-*.jar" - then I tried to start photon as before with "java -jar photon-0.3.4.jar -listen-ip photon.mapsmarker.com -data-dir /home/htdocs/html/search-index/ &".

The following Java version is installed and used on the server:

```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

thx for your help!

**Comment by lonvia** [comment]
Have you also downloaded the latest dump from https://download1.graphhopper.com?  The data directories for 0.3.0 and 0.3.4 are not compatible. I would even recommend to start with a freshly unpacked new datadir as older versions of photon leave jars in the datadir that cause issues.

**Comment by robertharm** [comment]
Yes, I also downloaded the latest dump and used it as new datadir.

**Comment by robertharm** [comment]
closed the issue as we are not using photon anymore
