### ISSUE TITLE
Strange results for Dutch provinces

### ISSUE THREAD

**Issue by bopjesvla** [komoot/photon#499]
Using the 0.3.4 release and the Graphhopper database from yesterday, I'm getting strange and inconsistent results for Dutch provinces. http://localhost:2322/api?q=friesland gives me:

```
        "country": "The Netherlands",
        "osm_key": "boundary",
        "osm_value": "administrative",
        "name": "Friesland",
        "county": "Netherlands",
        "type": "region"
```

The Netherlands are returned as both country and county. Friesland is a province. In the operation version at http://photon.komoot.de/api/?q=friesland, a simpler but correct result is returned:

```
        "country": "The Netherlands",
        "osm_key": "place",
        "osm_value": "state",
        "name": "Friesland"
```

When running http://localhost:2322/api?q=leeuwarden (Leeuwarden being a city in Friesland):

```
        "country": "The Netherlands",
        "osm_key": "boundary",
        "city": "Leeuwarden",
        "osm_value": "administrative",
        "name": "Leeuwarden",
        "county": "Friesland",
        "state": "Netherlands",
        "type": "locality"
```

Here, Friesland is considered the county, rather than the Netherlands. The result at http://photon.komoot.de/api/?q=leeuwarden is again correct:

```
        "country": "The Netherlands",
        "osm_key": "place",
        "osm_value": "city",
        "name": "Leeuwarden",
        "state": "Friesland"
```

I assume this is a regression of some sort. Which version is currently running at photon.komoot.de?

**Comment by lonvia** [comment]
The data dumps until last week were accidentally produced with the old 0.3.2 version. This has been fixed and this Sunday's dump has more sensible results.

The one odd thing that remains is that Friesland has `state: Netherlands` in its result. This comes from the distinction between [Netherlands](https://www.openstreetmap.org/relation/47796) and the [kingdom of Netherlands](https://www.openstreetmap.org/relation/2323309) made in the OSM data. We really should be more consistent here between the results for 'Friesland' and 'Leeuwarden'.
