### ISSUE TITLE
Wrong city name

### ISSUE THREAD

**Issue by hendrikmoree** [komoot/photon#503]
Hi,

This node (https://www.openstreetmap.org/node/5098143907) returns city "Im Stillen Winkel" but this should be "Mülheim an der Ruhr"

I see this query `SELECT p.place_id, p.name->'name', p.class, p.type, p.rank_address,p.admin_level FROM placex p, place_addressline pa WHERE p.place_id = pa.address_place_id and pa.place_id = ? and pa.cached_rank_address > 4 and pa.address_place_id != ? and pa.isaddress order by rank_address desc,fromarea desc,distance asc,rank_search desc;` returns 1 item with a rankAddress between 13 and 17 so that's the reason.

But in a previous version you also requested `p.extratags->'place' as place` which resulted in city "Mülheim an der Ruhr" which is the correct one.

**Comment by lonvia** [comment]
Looks good to me for the latest data dump: https://photon.komoot.de/api/?q=pandora,%20m%C3%BClheim

**Comment by lonvia** [comment]
Note that when you do your own exports then you should use Nominatim >= 3.5 for Photn 0.3.3+ or results are odd at times. If you feel adventurous, then Nominatim master yields even better results.

**Comment by hendrikmoree** [comment]
Ah I think that's the issue. We're still on 3.4.1 and I did a fresh import. 
Thanks, we will update nominatim first!
