### ISSUE TITLE
No Access-Control-Allow-Origin on resource when requesting via AJAX

### ISSUE THREAD

**Issue by derwaldgeist** [komoot/photon#507]
Photon worked fine until recently. But now we're getting this error in Chrome:

Access to XMLHttpRequest at 'https://photon.komoot.de/api/?q=erlangen' from <domain> has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

The strange thing is: the header is present if we use Postman, but accessing photon via  the `axios` library fails now.

**Comment by derwaldgeist** [comment]
Update: this also happens if I try to use `fetch()` directly.

**Comment by derwaldgeist** [comment]
Update: I now sometimes get another response with a redirect to photon.komoot.io, but the resource there cannot be found.

**Comment by derwaldgeist** [comment]
![image](https://user-images.githubusercontent.com/3984535/96986119-7e2e4e00-1521-11eb-8b5a-f6673c9876b5.png)

**Comment by derwaldgeist** [comment]
Even stranger, sometimes the query works fine.

**Comment by lonvia** [comment]
We switched the server from `photon.komoot.de` to `photon.komoot.io` yesterday, not considering that permanent redirects like that are not possible with CORS. I've reinstated photon.komoot.de/api for now to not break services. The odd behaviour you have seen was just a temporary glitch because of the switching. We'll do an official announcement later about the URLs. For now everything should work as before.

**Comment by derwaldgeist** [comment]
@lonvia Ok, thanks for the fast response. Is it safe to switch to .io now?

**Comment by christophlingg** [comment]
@derwaldgeist yes it is

**Comment by derwaldgeist** [comment]
@christophlingg Thanks!

**Comment by lonvia** [comment]
I've reinstated the redirects. CORS headers are now set up in a way that the redirect should work with any reasonably modern browser. If you have nonetheless ended up at this issue:

***Please switch the photon base URL to `https://photon.komoot.io`***

**Comment by derwaldgeist** [comment]
Just wanted to report back that the old endpoint does not work if you do requests on the server side (using `axios` under `nodejs`). Switching to the `.io` domain resolved this.

**Comment by lonvia** [comment]
@christophlingg It looks like you have switched photon.komoot.de to point to one of your servers. Could you please set CORS headers in all the responses and make sure that OPTIONS requests return a 200 instead of 301.

**Comment by christophlingg** [comment]
@JorgenG could you please have a look on it?

**Comment by JorgenG** [comment]
@lonvia we have added an in-between load balancer which basically just redirects to the new domain. Is the CORS an active issue you observe with the new redirect?

I have assumed that the CORS are only relevant at the final target after the client is redirected? (The same with OPTIONS)
I will try to do some additional experiments with some examples tomorrow, and if we have broken something we will try to restore it. If you do have an example where the CORS / OPTIONS 200 is required that would be great. 🙂

**Comment by lonvia** [comment]
@JorgenG You need CORS headers along the whole redirection chain. At least that was the only way I could make it work. You can simply test this with the photon webiste from this repo. Check out the repo, copy `website/config.js.example` to `website/photon/config.js`. Edit `website/photon/config.js` and change the API_URL to `'https://photon.komoot.de/api/?'`. Then open `website/photon/index.html` in your browser. Type something in the search box and you'll see that the request already fails on the OPTIONS call to photon.komoot.de.

**Comment by JorgenG** [comment]
@lonvia Ah, thanks a lot for the elaboration. Apologies for having misunderstood this and potentially broken it for web ui clients. I made the wrong assumption that web client redirects would only care about CORS for the "end" destination, i.e. the redirected target. I'll redirect the traffic back to the server as before and continue investigating a proper solution.
