### ISSUE TITLE
geocoding quality decreased since version 0.3.4 

### ISSUE THREAD

**Issue by choesterle** [komoot/photon#512]
Hi,

I've noticed some quality deterioration for geocoding between version 0.3.2 and 0.3.4.

In earlier versions, when executing
https://photon.komoot.io/api?q=Ausstellungsgasse%2011%20Wiener%20Neustadt%20%C3%96sterreich&lang=de
a result was returned that explicitly matched the search criteria. That means the result contained the properties
_street: Ausstellungsgasse, 
housenumber: 11, 
city: Gemeinde Wiener Neustadt
etc._
With the new version 0.3.4, we don't get such a result containing all search criteria. The closest match is

```
properties": {
"osm_id": 459950166,
"country": "Österreich",
"city": "Wiener Neustadt",
"countrycode": "AT",
"postcode": "2700",
"locality": "Musikantenviertel (Gartenstadt)",
"type": "house",
"osm_type": "N",
"osm_key": "amenity",
"housenumber": "5",
"street": "Ausstellungsgasse",
"osm_value": "kindergarten",
"name": "NÖ Landeskindergarten Ausstellungsgasse",
"state": "Niederösterreich"
}
```

but with a wrong housenumber _5_ instead of _11_

BR,
Christian

**Comment by lonvia** [comment]
This particular case actually has a data error. [way 107802295](https://www.openstreetmap.org/way/107802295) has ` addr:city=2700`. But I don' t think this is what is causing the issues here. It looks like we have a problem with cross language lookups. This used to work. I need to find out what changed.

**Comment by lonvia** [comment]
The example has been fixed in the meantime which fixed the query. #538 should also fix the underlying mixed-lingual issue.
