### ISSUE TITLE
Import ES photon_data directly from OSM

### ISSUE THREAD

**Issue by akatie** [komoot/photon#522]
Current State:

- `photon` imports directly from `postgres` database designed for Nominatim
- `osm2pgsql` et al import from .osm to `postgres` designed for Nominatim

Preferred State:
- codify intermediate format (like the json dump of nominated) for import into photon_data
- disconnect the creation of intermediate format from photon service .jar

**Comment by lonvia** [comment]
OSM data isn't suitable for geocoding in its raw form. It needs quite some heavy preprocessing which is exactly what Nominatim does for photon.

Regarding an intermediate json format, there are #291 and #438 already which suggest and implement a direct json import.
