### ISSUE TITLE
Docker Image on Docker Hub

### ISSUE THREAD

**Issue by kurtisane** [komoot/photon#536]
Hi ,
I'm not entirely sure if there is one already, but it would be great if there is a Container that contains Photon. 

If there is one out already can someone maybe put it in the readme for newcomers like me to find easily. 
Regards !

**Comment by lonvia** [comment]
Sorry, there won't be any official docker images, as I don't have the capacity to maintain them. In any case, installing photon should be easy enough that you can create your own docker image in a couple of minutes.

**Comment by hbruch** [comment]
Though there is no official docker image, and documentation is missing, you might be interested in the way we [package photon via docker](https://github.com/mfdz/photon/blob/main/Dockerfile). 

Note, that we somewhat lag behind current Komoot/photon master.
