### ISSUE TITLE
Discrepancy between Parisian suburbs (Paris arrondissements)

### ISSUE THREAD

**Issue by tvaudelin** [komoot/photon#537]
Hello,

Thank you very much for offering this API, it's fantastic!
I am currently working on a map that highlights French cities or districts/suburbs in the case of big cities. 

Everything just works fine although I just noticed that all Parisian suburbs (arrondissements) are defined the same way (osm_key: place - osm_value: suburb) except one: Paris 2e arrondissement, which has the osm_key: boundary and the osm_value: administrative.
![image](https://user-images.githubusercontent.com/51421128/106160903-a06de280-6186-11eb-8198-0a726434c033.png)

I checked the nominatim ddb and couldn't find such discrepancy. All Parisian suburbs, including the 2nd arrondissement, appear at both a Relation and a Node level.

Any idea of where this difference could come from and how to fix it? I'd rather not go through a complex filter of boundary/administrative components.

Thanks

**Comment by lonvia** [comment]
If you check the Nominatim details page, you' ll see that for example the [1st arrondissement](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=20727&class=boundary) Nominatim is able to make the link between the boundary and the suburb node (you'll find a sction ' Linked places'  with the suburb node). For the [2nd arrondissement](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=9542&class=boundary) there is no such link. There are two sure ways to get Nominatim to make a link with the place node: add it with role ' label'  (not 'admin_centre'!) to the boundary relation or make sure that boundary and place node have the same wikidata link. In this particular case the wikidata tag is missing on the suburb node of the 2nd arrondissement while all other suburb node have one. Once you fix that, Nominatim should pick up the connection. And if it's there, photon will pick it up as well with the next weekly update.

**Comment by tvaudelin** [comment]
Thank you Sarah for the clear explanation. I just added the wikidata tag in OSM and will wait for the weekly update !
Closing the issue now.
Cheers

**Comment by lonvia** [comment]
Nominatim didn't pick up the change by itself through the updates. Or rather: it picked up the new wiki tag but didn't quite figure out that the boundary needs updating too. I was afraid of that, because it is a bit tricky to figure out that there is a new connection (there is an open ticket about that). I've manually updated them now, so you'll see the change in next weeks update. Just something to be aware of, when doing changes like that.

**Comment by tvaudelin** [comment]
Got it, thank you vm for your help.
