### ISSUE TITLE
Import from nominatim

### ISSUE THREAD

**Issue by azzahrah** [komoot/photon#554]
Get data from nominatim without download 

[wget -O - https://download1.graphhopper.com/public/photon-db-latest.tar.bz2 | bzip2 -cd | tar x](url)

any option to direct TCP/UDP connection without http server? 

Is possible?

**Comment by lonvia** [comment]
I don't understand this question. The command just downloads a file and unpacks it. You can do this any other way you like but the data is only available via http or https.

**Comment by azzahrah** [comment]
@lonvia , i mean can we import data from nominatim without download https://download1.graphhopper.com/public/photon-db-latest.tar.bz2 firstly

note: i have success import from nominatim

**Comment by lonvia** [comment]
https://github.com/komoot/photon#customized-search-data
