### ISSUE TITLE
Wrong search result

### ISSUE THREAD

**Issue by Hummel37** [komoot/photon#579]
If we make a call to https://photon.komoot.io/api/?q=Werlte%20Westerkamp
(City and street)
we find city Werlte with the postcode of 49757 and the street Westerkamp.

If we make a call to  https://photon.komoot.io/api/?q=49757%20Westerkamp
(postcode and street)
we don't find the street anymore. Although we only search for the postcode and the street.

**Comment by lonvia** [comment]
This seems to be fixed with #580.
