### ISSUE TITLE
Photon does not find a street

### ISSUE THREAD

**Issue by droppy2014** [komoot/photon#586]
There is a street in St. Petersburg, Russia, which has name "Чапаева" (Chapaeva street). When I query /api?q=Чапаева it doesn't find it. Also, any search with house addresses /api?q=Чапаева 5 does not work as expected.
![2](https://user-images.githubusercontent.com/10504051/121783701-cf767500-cbb8-11eb-90f9-cef4735f90bc.png)

Though the address exists in OpenStreetMap base
![3](https://user-images.githubusercontent.com/10504051/121783706-d0a7a200-cbb8-11eb-9bf7-87a91af91f90.png)

**Comment by lonvia** [comment]
Works fine on the demo instance when adding 'St Petersburg' to the search: https://photon.komoot.io/api/?q=%D0%A7%D0%B0%D0%BF%D0%B0%D0%B5%D0%B2%D0%B0%205,%20St.%20Petersburg . Чапаева is such a common name, you get a random selection of results without further specification. Same for 'Чапаева 5'.

**Comment by droppy2014** [comment]
Unfortunately, not many people from St. Petersburg guess to add "St. Petersburg" or even "Санкт-Петербург" to query when searching, because it is too long. Even they can add "спб" (short name) which usually local citizen uses but it still does not work - https://photon.komoot.io/api/?q=%D1%87%D0%B0%D0%BF%D0%B0%D0%B5%D0%B2%D0%B0%205%20%D1%81%D0%BF%D0%B1
![4](https://user-images.githubusercontent.com/10504051/121788935-4b34e980-cbda-11eb-8f71-cd0d8bbf2e21.png)

Also, does not work if use location bias https://photon.komoot.io/api/?q=%D0%A7%D0%B0%D0%BF%D0%B0%D0%B5%D0%B2%D0%B0%205&lat=59.958460&lon=30.333080&location_bias_scale=10 (the exact coordinates of чапаева 5)

**Comment by lonvia** [comment]
Photon does not use `short_name` at the moment. The search works with location bias if you use the default location_bias_scale: https://photon.komoot.io/api/?q=%D0%A7%D0%B0%D0%BF%D0%B0%D0%B5%D0%B2%D0%B0%205&lat=59.958460&lon=30.333080

Essentially this is the same issue as #277. Guessing which city is the most important, when there are streets in many cities to choose from. Closing as duplicate here.
