### ISSUE TITLE
[Question] Location bias

### ISSUE THREAD

**Issue by bambax** [komoot/photon#59]
How does location bias work?

On http://photon.komoot.de/api results seem to be only loosely influenced by different lat|lon parameters, and some results that are much farther from the given point, come before others that are much nearer.

Is it possible to order results based on distance from the point given as lat|lon?

Would it be possible to provide a bounding box to search, so that search wouldn't return results outside that box?

**Comment by christophlingg** [comment]
we plan to include a bounding box search see #158

**Comment by karussell** [comment]
> Is it possible to order results based on distance from the point given as lat|lon?

that is already possible, see the docs
