### ISSUE TITLE
problem while indexing document

### ISSUE THREAD

**Issue by imaxkhan** [komoot/photon#616]
i am indexing docs to elasticsearch version 7.9 and 471 docs will be inserted successfuly but some of them fails and this is the error:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=10,endOffset=17,lastStartOffset=15 for field 'collector.default'"}],"type":"illegal_argument_exception","reason":"startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=10,endOffset=17,lastStartOffset=15 for field 'collector.default'"},"status":400}

**Comment by lonvia** [comment]
ElasticSearch 7.9 is not supported at the moment. Please use ElasticSearch 5.6.

**Comment by imaxkhan** [comment]
Hi i solved the issue now photon works with elastic 7.9 and java high level
rest client if u are interested ,i can share

**Comment by lonvia** [comment]
Feel free to do a draft PR.
