### ISSUE TITLE
continuously_update / out of disk space

### ISSUE THREAD

**Issue by quargh** [komoot/photon#649]
Hello,

i am running Nominatim 4.0.1 and Photon 0.3.5.
I imported an extract of germany into the database and then imported it to photon_data.
Now i am running continuously_update_from_nominatim.sh and the process is flooding my disk with tons of gigabytes very quickly.
I have only catched up 3 days in the backlog in 30 minutes and it consumed already 60 G of free disk space leading to out of disk space error.

Is this normal / a known issue or is there a way to solve this?

Thank you

**Comment by lonvia** [comment]
First, of all. Have you seen pinned issue #638?

That said, the issue with Nominatim 4 shouldn't be with disk space. You need to be a bit more specific though, which process is filling the disk?

**Comment by quargh** [comment]
Thank you for your answer. I havent seen #638 before.

What I have done to find out is run iotop -a for accumulated disc writes, and what I can see is that the following is already consuming nonstop disk space with a speed of 100 mb / min, directly after reboot without having started anything.

  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
32187 be/4 postgres   1634.19 M   1756.27 M  0.00 %  0.16 % postgres: 10/main: autovacuum worker process   nominatim
  
When running continuously_update_from_nominatim.sh, disk space is consumed at a speed of 2.91 G / min.
I monitored it for 10 minutes: 

iotop -a

Total DISK READ :      11.89 M/s | Total DISK WRITE :       8.85 M/s
Actual DISK READ:      11.88 M/s | Actual DISK WRITE:       0.00 B/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
32187 be/4 postgres    918.80 M    1041.50 M  0.00 %  0.06 % postgres: 10/main: autovacuum worker process   nominatim
 7877 be/4 postgres    232.01 M     232.02 M  0.00 %  4.35 % postgres: 10/main: autovacuum worker process   nominatim
 1498 be/4 postgres     36.00 K     974.67 M  0.00 %  0.00 % postgres: 10/main: writer process
 1499 be/4 postgres      0.00 B     507.95 M  0.00 %  0.00 % postgres: 10/main: wal writer process
 1497 be/4 postgres     16.00 K     458.59 M  0.00 %  0.00 % postgres: 10/main: checkpointer process
...

However this doesnt explain 29.1 G of consumed disk space in this time span of 10 minutes.
If there is another way to find out which process is writing so much data to disk please let me know.

**Comment by lonvia** [comment]
It would be more interesting to know **what** is written. Into which directories/files are the 30G of data saved?
