### ISSUE TITLE
Street does not appear when trying to filter by city

### ISSUE THREAD

**Issue by HenrikZabel** [komoot/photon#675]
https://photon.komoot.io/api/?q=Markgrafenstr&osm_tag=place:name=Berlin

I get nothing:
![image](https://user-images.githubusercontent.com/54895728/170558397-f1035fb3-b28a-4b78-99f5-73760df584ca.png)

When removing the osm_tag I get tons of results.
How to implement the filter differently to this? :)

**Comment by lonvia** [comment]
I suspect, what you want to do is: https://photon.komoot.io/api/?q=Markgrafenstr,Berlin , i.e find the Markgrafenstr in Berlin?

**Comment by HenrikZabel** [comment]
@lonvia Thank you! That's exactly what I wanted to have
