### ISSUE TITLE
US postcode are imported even for non US instances

### ISSUE THREAD

**Issue by josefcs** [komoot/photon#69]
This is only reproduceable on local installations:

Some queries have after their results several fields with completely wrong results. E.g. using an extracted part of austria, the query

http://localhost:2322/api?lang=de&q=Kaisersch%C3%BCtzenstra%C3%9Fe%2017

returns normal results and afterwards there are several fields:

```
{
            "properties": {
                "osm_id": 31344,
                "postcode": "17503",
                "osm_value": "postcode",
                "country": "Vereinigte Staaten von Amerika"
            },
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -76.08483701582313,
                    39.93753065153189
                ]
            }
        },
```

Which shouldn't even be in the extract. Is there an error in the extraction, or does photon "invent" these results?

**Comment by christophlingg** [comment]
that's a nominatim issue
