### ISSUE TITLE
Additional languages & v0.4.0 - Possible regression

### ISSUE THREAD

**Issue by macolu** [komoot/photon#691]
With Photon 0.3.5, in order to customize language list, you only add to specify your list at import step (with `-languages` attribute).

Then, when starting Photon, you didn't have to provide language list anymore. Photon fetched list from internal `DATABASE_PROPERTIES` ES document.

With 0.4.0, this no longer works. You need to specify language list a second time, when starting Photon instance. Otherwise you're back with default language list (or more precisely, intersection between default list and list defined at import).

I think this has been introduced in 5290f8be. By moving default list in `CommandLineArgs`, it's used in both **import** and **run** contexts.

Looks like a regression to me

Thanks

**Comment by lonvia** [comment]
Thanks for pointing to the right commit. Can you give #693 a quick test to see if it fixes things for you?

**Comment by macolu** [comment]
Just tested your PR, issue is fixed for me, it brings back previous behavior.

Thanks a lot!

**Comment by lonvia** [comment]
Thanks for testing. New release is on the way.
