### ISSUE TITLE
Provide filters

### ISSUE THREAD

**Issue by josefcs** [komoot/photon#71]
It always depends on how the search mechanism should work, but from my point of view filters could be generally very usable (and would be for our case).

Filters:
Provide a way to filter results, e.g.

    q=Hauptstraße&city=Salzburg

and the result will only show results from the city of Salzburg.

and as an idea:

    q=Hauptstraße&city=Salzburg&city:mode=fuzzy

this result will also include fuzzy matches, like
`Salzberg` and `Salzbrug` (typo).

Filters could be:
* city
* country
* postcode (e.g. 5020 with high fuzzyness would match 5* and low fuzzyness 502?)
* name
* osm_key (or generalized version)
* osm_value (or generalized version)

Why:
Often, when searching for addresses, the user is confronted with impartial and incorrect addresses. The only thing he knows is a part of the name and in which city or part of the city the address is in. This would help greatly for people who have to research addresses.

For frontend-development (i.e. the komoot main site), the query could be totally adjusted to the needs or even user preferences just by the passed parameters.

Additionally as crazy idea (don't know if it is possible with elasticsearch):
Provide a "near" parameter, so you have:

    q=Haubdstr&near=(Salzburg  OR lat/lon)

and the search parameter can have lesser matching the nearer it gets to the point provided by "near".

**Comment by christophlingg** [comment]
@sdole provided filters in photon
