### ISSUE TITLE
Suggest street houses instead of street only?

### ISSUE THREAD

**Issue by evsgp** [komoot/photon#715]
Hello, currently when typing out the street name I am only getting street itself as the response in autocomplete, while I'd like to get a list of houses to pinpoint more precise location that user is choosing, is that possible with photon? I tried some filters by tags, nothing worked so far. Photon doesn't seem to provide any tool to fetch something like all houses by osm_id out of box too. Maybe I'm missing out on something.

**Comment by lonvia** [comment]
This is indeed not a function that Photon provides and there are no plans to add something like this.
