### ISSUE TITLE
Photon API is unstable

### ISSUE THREAD

**Issue by RolandMostoha** [komoot/photon#719]
In the last couple of days the Photon API became quite unstable. It usually returns HTTP-404 or responds very slowly and unreliably.

What I've tried:
1. The Search field in https://photon.komoot.io/
2. Calling the API directly: https://photon.komoot.io/api/?q=berlin

What I got:
Most of the times HTTP-404, other times slow (~5 sec) responses.

Can you please check for its availability?

**Comment by lonvia** [comment]
There was an app which was sending massive amounts of search queries. I've blocked the app and tried to notify the responsible parties. Service should be back to normal.
