### ISSUE TITLE
Get Details for osm_id

### ISSUE THREAD

**Issue by kw005** [komoot/photon#720]
Hi,

Is there a way to get the details from an osm_id, selected from user before? 

Thank you

**Comment by mtmail** [comment]
Nominatim has a lookup by id (https://nominatim.org/release-docs/develop/api/Lookup/)  and Overpass API does (https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#By_element_id), but photon has no lookup method to search by osm_id.

**Comment by lonvia** [comment]
Not planned.
