### ISSUE TITLE
[Typeahead suggestion] Missing street numbers

### ISSUE THREAD

**Issue by baneJack** [komoot/photon#738]
When I enter an address (number and street), **the suggestions are not exhaustive**.

Example: When I enter an address (number and street): "14 Rue des Annonciades, Meulan-en-Yvelines" the suggestion is only "Rue des Annonciades, Meulan-en-Yvelines" **without the street number.**
For some addresses, I have all the information (number and street).

**Comment by mtmail** [comment]
Photon uses data from OpenStreetMap. OpenStreetMap data doesn't contain any house number 14 for this street https://www.openstreetmap.org/way/599926487

**Comment by lonvia** [comment]
There are housenumbers but 14 is missing, which I would expect around here: https://www.openstreetmap.org/way/599926487#map=19/49.00613/1.91066

The end result is the same. Photon can only suggest house numbers that are in the underlying data. Closing as data issue.
