### ISSUE TITLE
layer=city does not work for some larger german cities

### ISSUE THREAD

**Issue by Joshua-Ko** [komoot/photon#744]
I am using photon 0.4.3 with the database from here:
https://download1.graphhopper.com/public/photon-db-latest.tar.bz2
(ls -l shows last mod = Jul  9 20:41
,sha256sum gives d6e0f5552874a76a3be39dd2b44ae193c39244d68006d1a94e69cb14fa7e5293)
Java: openjdk version 18.0.2-ea
OS: Ubuntu 22.04.2 LTS

missing wanted result:

`curl -s 'http://127.0.0.1:2322/api?q=mainz&layer=city' | jq`
-> "Mainzac" in France.

`curl -s 'http://127.0.0.1:2322/api?q=potsdam&layer=city' | jq`
-> "Potsdam" in United States.

`curl -s 'http://127.0.0.1:2322/api?q=kiel&layer=city' | jq`
-> Lots of places that are not in Germany.

no result:

`curl -s 'http://127.0.0.1:2322/api?q=wiesbaden&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=duisburg&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=dortmund&layer=city' | jq`

works:

`curl -s 'http://127.0.0.1:2322/api?q=berlin&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=hamburg&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=frankfurt&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=köln&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=nürnberg&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=hannover&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=dresden&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=bremen&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=leipzig&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=düsseldorf&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=stuttgart&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=münchen&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=schwerin&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=saarbrücken&layer=city' | jq`
`curl -s 'http://127.0.0.1:2322/api?q=erfurt&layer=city' | jq`

**Comment by lonvia** [comment]
I can't reproduce that on https://photon.komoot.io which also uses the dumps from graphhopper and the 0.4.3 release. It's been a while since that was reported. Did the problems go away with a new download?
