### ISSUE TITLE
Make timeout configurable

### ISSUE THREAD

**Issue by karussell** [komoot/photon#747]
It would be nice to reduce [this timeout](https://github.com/komoot/photon/blob/master/src/main/java/de/komoot/photon/elasticsearch/ElasticsearchSearchHandler.java#L66) to protect us from problematic queries bringing the server down. Or make this configurable as some machines are more powerful and don't need a tight timeout.

**Comment by lonvia** [comment]
#769 has an implementation of this. My tests show that this does have an effect on long-running nonsense queries but they still tend to run for a few seconds, even when the timeout is set to 1 s.

We might need a some extra protection against nonsense queries that might become a problem for ES.
