### ISSUE TITLE
CORS Basic Support

### ISSUE THREAD

**Issue by TheRealPanPan** [komoot/photon#81]
Hi,

I'm using photon in a cross domain way.
I've just add 
response.header("Access-Control-Allow-Origin","*");
in app.java inside the api route handler.
This enable photon to answer to CORS request by accepting any origin to access its ressources (I.E. the response of ?q= queries).

A more in depth support would be to have these authorized domains to be configurable.

I Hope this helped.

Regards,
TheRealPanPan

**Comment by Defozo** [comment]
Any update on this?
