### ISSUE TITLE
Close matching POIs missing, faraways ones are listed

### ISSUE THREAD

**Issue by matkoniecz** [komoot/photon#833]
https://photon.komoot.io/api/?q=Nest%20Bank&lon=19.9323&lat=50.0599&zoom=14&lang=default finds https://www.openstreetmap.org/node/6881940885 as its first match which is great and fine

But it fails to list: https://www.openstreetmap.org/node/6780544486 and https://www.openstreetmap.org/node/6863954432 

Instead it lists some far-away banks.

I originally reported it as https://github.com/zbycz/osmapp/issues/226 - and it seems that it is an upstream Photon issue.

**Comment by dbapl** [comment]
This is probably same as #746
With lang=en it returns those results:
https://photon.komoot.io/api/?q=Nest%20Bank&lon=19.9323&lat=50.0599&zoom=14&lang=en

**Comment by matkoniecz** [comment]
I am still confused why `lang=default` throws away this matches but either way solution seems clear

sorry for not finding that and reporting a duplicate
