### ISSUE TITLE
Krakow appears twice in results

### ISSUE THREAD

**Issue by matkoniecz** [komoot/photon#95]
to replicate: type 
Krakow
into search box on http://photon.komoot.de/ and select the first/second result

expected: single result for a city, maybe some towns with the same name
result: the second entry is duplicate of the first one

**Comment by hbruch** [comment]
geocoder_tester tests currently fail for a couple of polish cities, as the center of their admin level 6/7 boundaries is distinct from the admin level 8 center.:

```
geocoder_tester/world/poland/test_cities.csv::Szczecin
geocoder_tester/world/poland/test_cities.csv::Bydgoszcz
geocoder_tester/world/poland/test_cities.csv::Świętochłowice
geocoder_tester/world/poland/test_cities.csv::Rybnik

```

Should they really be merged? If yes, I think admin level 8 center should have higher precedence.

**Comment by lonvia** [comment]
Closing this as a mapping issue. The three relations are exactly the same except for the admin_level. There is no way for photon to make an informed decision here.

**Comment by matkoniecz** [comment]
> There is no way for photon to make an informed decision here.

Take the most important one, with the lowest admin level?
